### ISSUE TITLE
Configurable Ethernet Mesh

### ISSUE THREAD

**Issue by nomaster** [freifunk-gluon/gluon#102]
In Expert Mode, the user can switch the device's LAN ports mode to 'Mesh'. In this mode, the client bridge does not longer apply to them, but B.A.T.M.A.N. frames are exchanged over the ports. If the device has a vswitch, individual ports can be configured.

**Comment by tcatm** [comment]
I think this has been superseded by https://github.com/freifunk-gluon/gluon/issues/284
