### ISSUE TITLE
gluon-config-mode-geo-location: unable to leave Long/Lat empty

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#1024]
Using current master, I'm having some trouble with leaving the geo position undefined.

I have left "Show node on the map" unticked and left Long/Lat empty then. However, the wizard then complains with a "One or more required fields have no value!":

![gluon-geo-issue](https://cloud.githubusercontent.com/assets/350145/22616392/48dd9858-eaac-11e6-8247-942b936406e6.png)

The browser I've tried is Midori 0.4.3 on an ARM based system.

**Comment by rubo77** [comment]
Ia this reproducible?

Maybe you entered a space somewhere?

And is js enabled?

**Comment by NeoRaider** [comment]
Anything in your Js console? The problematic fields should not be shown at all when "Show node on the map" is unset.

**Comment by T-X** [comment]
Hrm, it was reproduceable for the second device.

Now I had rebuilt Gluon with a more recent version of LEDE, restarted midori with logging - and the issue is gone. Probably some browser caching issue, I guess *sigh*.
