### ISSUE TITLE
LEDE: bridge multicast snooping is disabled

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#1025]
With the switch to LEDE bridge multicast snooping was disabled, because two people were reporting issues with multicast.

http://lists.infradead.org/pipermail/lede-dev/2017-January/005482.html

For one of the two, the issues were confirmed to lie somewhere else, not within the bridge. For the other one, investigations are still pending:

https://bugs.lede-project.org/index.php?do=details&task_id=253

I did some quick retries with a current Gluon master based on LEDE and for me, the bridge multicast snooping seems to be working as expected, just like it did with OpenWRT.

For testing, I installed the gluon-ebtables-segment-mld package and added "option igmp_snooping '1'" and "option multicast_querier '1'" to the client section in /etc/config/network.

I marked this issue as a regression for now, as there might already be people relying on a reduced multicast level in neighborhoods with many, close nodes.

**Comment by NeoRaider** [comment]
@T-X Can you prepare a PR to enable multicast snooping again?

**Comment by T-X** [comment]
Sure, will do today or tomorrow.

I haven't heard of any complains with 2016.2.x even together with the gluon-ebtables-segment-mld package so far and the LEDE bug report [253](https://bugs.lede-project.org/index.php?do=details&task_id=253) mentioned above progresses very slowly, is more confusing than helpful so far and therefore is still unconfirmed. So I think it is safe to reenable it, yes.
