### ISSUE TITLE
autupdater: incomplete code comment [low priority]

### ISSUE THREAD

**Issue by SimJoSt** [freifunk-gluon/gluon#1043]
While looking at the inner workings of the autoupdater and the origin and behavior of the minute being randomly set, I discovered that the code comment for the fallback job is an incomplete sentence: https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-autoupdater/luasrc/lib/gluon/upgrade/500-autoupdater#L44

I didn't provide a PR, as I am not contributing code to gluon (yet™) and are unfamiliar to the agreed upon and generally used syntax as well as having no idea how that sentence from @NeoRaider ([commit](https://github.com/freifunk-gluon/gluon/commit/9510d03b8b7c80549cbd4215713f7451604664be#diff-03835bf19e44371ceaaa03565f20351aR51)) was suppose to end.

**Comment by rotanid** [comment]
maybe @rubo77 could include this in his PR #907
