### ISSUE TITLE
Ubiquity AC Lite/Pro have 5GHz device as client0/mesh0 and 2.4GHz as client1/mesh1

### ISSUE THREAD

**Issue by smoe** [freifunk-gluon/gluon#1052]
Hello,

I am not certain if this is of much concern, but compared with other dual band devices (like the WDR4300) I got the impression that the client/mesh device numbers are ordered by their frequency. This affects someone's routine to for instance run scripts changing the channel on the 2.4GHz band via uci for which the device number needs to be known.

Nothing dramatic, but, anyway.
 
Steffen

**Comment by NeoRaider** [comment]
The ordering depends on the hardware and is completely arbitrary. I think it should be the same on most ath10k devices.
