### ISSUE TITLE
Kernel download

### ISSUE THREAD

**Issue by jjsarton** [freifunk-gluon/gluon#1059]
ftp://ftp.all.kernel.org/pub/kernel/v3.x/ and  http://ftp.all.kernel.org/pub/inux/kernel/v3.x/ seem no more to be provided.
The URL https://www.kernel.org/pub/linux/kernel/v3.x/  work after inserting the irl in the file gluon/build/ar71xx-generic/openwrt/scripts/download.pl

**Comment by NeoRaider** [comment]
Fixed in 9994eebe3e03dc827944ec3ddcf7d096cd0173d1.
