### ISSUE TITLE
Gluon 2016.2.3: TL-WA801NDv3 Region Code required?

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-gluon/gluon#1064]
We got an issue with Gluon 2016.2.3 (factory image) in combination with a new TL-WA801NDv3 router.

The factory firmware (version unknown) has canceled the update flash process with following error message: "Error code: 18005 (file was incorrect)"

Unfortunately, no further information is available.

**Comment by Adorfer** [comment]
probably another ETSI300328-routerlockdown. 

is there an "(EU)" on the boilerplate?

**Comment by oszilloskop** [comment]
I got following information update:
The router works fine with a Gluon 2016.2.3 factory image flashed via TFTP.

**Comment by NeoRaider** [comment]
I've extracted the necessary data from the stock firmware images and will push an update soon.

**Comment by NeoRaider** [comment]
There is a fix in my LEDE staging tree at https://git.lede-project.org/?p=lede/neoraider/staging.git;a=summary now, it would be great if someone could test that this yields images flashable from both EU and US firmwares.

**Comment by NeoRaider** [comment]
Still nobody who can check this? Would it help if I provide a test image?

**Comment by rotanid** [comment]
closing as there hasnt been any feedback.
