### ISSUE TITLE
PoE Passthrough option falsely available Ubnt Loco M2 (XM)

### ISSUE THREAD

**Issue by dersch81** [freifunk-gluon/gluon#1069]
v2016.2.3-2-g242e6361 as well as 2016.2.4

![20170313_212902](https://cloud.githubusercontent.com/assets/13754891/23874084/b4c2d6dc-0834-11e7-94f2-d57e17eaa5f0.jpg)

**Comment by NeoRaider** [comment]
This is likely the result of using the wrong image: using the normal NanoStation image on the Loco will mostly work, but it will make the system think it has two Ethernet ports.

After a NanoStation image was installed once, you need to upgrade to the correct image (ubiquiti-nanostation-loco-m2) *without keeping the configuration* to get rid of incorrect settings.

**Comment by dersch81** [comment]
I've checked it several times but really took the loco m2 FW of my community. I attach it for double checking but also will talk to our firmware builder.


[gluon-ffda-0.9.4-ubiquiti-nanostation-loco-m2.zip](https://github.com/freifunk-gluon/gluon/files/840585/gluon-ffda-0.9.4-ubiquiti-nanostation-loco-m2.zip)

**Comment by NeoRaider** [comment]
Please post the contents of `/tmp/sysconfig/board_name` and `/etc/config/system`.

**Comment by dersch81** [comment]
Ok i will do. But it takes a couple of days until the node is reachable for me

**Comment by dersch81** [comment]
Here you go:

`cat /etc/config/system

config system
        option timezone 'CET-1CEST,M3.5.0,M10.5.0/3'
        option hostname '64283-in-vagranti-nord-west-ladida'

config timeserver 'ntp'
        option enabled '1'
        option enable_server '0'
        list server 'ntp.services.ffda.io'

config gpio_switch 'gpio_switch_poe_passthrough'
        option name 'PoE Passthrough'
        option gpio_pin '8'
        option value '0'

config led 'led_rssilow'
        option name 'RSSILOW'
        option sysfs 'ubnt:red:link1'
        option trigger 'rssi'
        option iface 'rssid_wlan0'
        option minq '1'
        option maxq '100'
        option offset '0'
        option factor '13'

config led 'led_rssimediumlow'
        option name 'RSSIMEDIUMLOW'
        option sysfs 'ubnt:orange:link2'
        option trigger 'rssi'
        option iface 'rssid_wlan0'
        option minq '26'
        option maxq '100'
        option offset '-25'
        option factor '13'

config led 'led_rssimediumhigh'
        option name 'RSSIMEDIUMHIGH'
        option sysfs 'ubnt:green:link3'
        option trigger 'rssi'
        option iface 'rssid_wlan0'
        option minq '51'
        option maxq '100'
        option offset '-50'
        option factor '13'

config led 'led_rssihigh'
        option name 'RSSIHIGH'
        option sysfs 'ubnt:green:link4'
        option trigger 'rssi'
        option iface 'rssid_wlan0'
        option minq '76'
        option maxq '100'
        option offset '-75'
        option factor '13'
`


`/tmp/sysinfo# cat board_name
bullet-m
`

**Comment by NeoRaider** [comment]
The `gpio_switch_poe_passthrough` section is created by the script `/etc/board.d/03_gpio_switches`, which only adds it when the board name is *nanostation-m*. Even though you are using the correct image now, you must have had installed the NanoStation one at least once in the past. Reinstalling the firmware **without keeping your configuration** will solve the issue.
