### ISSUE TITLE
Include Patch for Hyper-V Target support

### ISSUE THREAD

**Issue by Nurtic-Vibe** [freifunk-gluon/gluon#1070]
To expand the x86 target, there is a Hyper-V patch for OpenWRT [https://github.com/tedaz/Hyper-V-support-for-OpenWrt-Chaos-Calmer](here).

**Comment by NeoRaider** [comment]
Hyper-V support is already included in the Gluon master in the x86-64 target, the patches have been accepted into LEDE a while ago.
