### ISSUE TITLE
Kernel panic - Out of memory

### ISSUE THREAD

**Issue by Joachim-Wolff** [freifunk-gluon/gluon#109]
Have observed randomly reboots on both of my TL-WR841ND v8 since running Gluon v2014.1a (Hamburg v0.4a), occurred 8 times in 3 weeks on each of it. Seams to have noting to do with issue #93.

Now I have found a crashlog file at /sys/kernel/debug/crashlog which make it really easy to report and identify this problem.

On whangarei there was 5 clients, 2 WLAN and 0 VPN at this time.
On opua 3 clients, 1 WLAN and 0 VPN at the time of his reboot, based on the Verbindungsstatistik from ohrensessel.net

Unfortunately I have no programing skills, so I don't have any idea what's going wrong...

**Comment by NeoRaider** [comment]
Closing, since the switch to Barrier Breaker there should be no random reboots any more (all reboots should have specific reasons for which separate tickets should be opened)
