### ISSUE TITLE
support for TL-WR841N v12

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1093]
it seems the newest revision v12 of the popular TP-Link TL-WR841N has exactly the same hardware as  v11.
LEDE support is already there: https://github.com/lede-project/source/commit/539e2a78f08860ea37442639d52b5d3c62cdfb67
@NeoRaider will add support to upstream branch lede-17.01 and lede-based gluon master (and possibly v2016.2.x ) after LEDE 17.0.1.1 has been released.

**Comment by Adorfer** [comment]
"same hardware": What a pitty... i really had hoped for 8MB flash. (But off course...) anways, thanks for the quick action.

**Comment by NeoRaider** [comment]
The Gluon master has support for the TL-WR841N/ND v12 now, please test.
