### ISSUE TITLE
Backport support for TP-Link TL-WR841ND v12 in gluon v2016.2.x

### ISSUE THREAD

**Issue by Tarnatos** [freifunk-gluon/gluon#1103]
I've written a patch for gluon v2016.2.x to support the v12 models.

https://github.com/freifunk-gluon/gluon/pull/1117/commits/378ef3d73b107b977972813b1f3dcc5e80409bb8

I don't have any v12 models here, so if someone can confirm the function of the images I will start a pull request.

**Comment by Tarnatos** [comment]
PR:
https://github.com/freifunk-gluon/gluon/pull/1117

**Comment by NeoRaider** [comment]
Done.
