### ISSUE TITLE
ar71xx-tiny overwrites ar71xx-generic packages

### ISSUE THREAD

**Issue by belzebub40k** [freifunk-gluon/gluon#1126]
If the ar71xx-tiny target is build after ar71xx-generic it will overwrite the packages from ar71xx-generic.
And because [CONFIG_SIGNED_PACKAGES](https://github.com/freifunk-gluon/gluon/blob/master/targets/ar71xx-tiny#L1) is not set for the ar71xx-tiny target the ar71xx-generic packages directory will not include a Packages.sig.

**Comment by NeoRaider** [comment]
Hmm, yes, the ar71xx-tiny target should not output packages to *output/packages* at all, as it doesn't have opkg. I'll fix this.
