### ISSUE TITLE
fastd Knoten werden in Statuspage nicht mehr angezeigt

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#1130]
siehe z.B. 
![screenshot 01 06 2017 02 12 54](https://cloud.githubusercontent.com/assets/8403794/26659302/f26d5a38-466f-11e7-9bd9-c293f06d8e81.jpg)

http://[2a03:2260:300b::32b5:c2ff:fe0e:8b6a]/

**Comment by Gammelknup** [comment]
Kann es sein, dass es sich um einen L2TP Knoten handelt? siehe rechts ->Mesh-VPN

**Comment by A-Kasper** [comment]
Nein. 
Weitere Info:
http://[2a03:2260:300b:0:62e3:27ff:fec6:d990]/
Hat die gleiche Firmware aber direkt per sysupgrade aufgespielt. Da geht alles wie es soll.

Vermutung:
- Umstellung der Syntax in der site.conf (es gibt ja jetzt die unterebene fastd) führt beim update irgendwie zu Irritationen. 
- Bug im neuen Format

**Comment by MTRNord** [comment]
@A-Kasper PS: die ipv6 bringt den meisten hier nix da sie in einem anderem netz sind ;)

**Comment by NeoRaider** [comment]
@MTRNord Ist ne öffentliche IP-Adresse :)

**Comment by MTRNord** [comment]
@NeoRaider ok dann ist mein vodafone anschluss mal wieder gegen mich :)

**Comment by NeoRaider** [comment]
The fact that it works on your other node is quite confusing...

Could you also provide your */lib/site.json*? The issue is somewhere in the gluon-mesh-vpn-fastd respondd provider.

**Comment by A-Kasper** [comment]
I've used jq . to make it better readable
https://pastebin.com/PbT366w4
