### ISSUE TITLE
mac address only as fallback if hostname field is empty or unchanged

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#1139]
>Die MAC-Adresse könnte Fallback sein, wenn das Feld leer ist (wenn die site.conf leere Namen erlaubt, oder der Config Mode übersprungen wurde), Es wäre sinnvoll die MAC da nicht per Default da im Feld stehen zu haben

1. the default entry for the hostname should not end with the mac address, but better just the default value from site.conf as it is.
2. if the user left the default value or emptied the hostname, in both cases the mac address should be added as suffix

**Comment by mweinelt** [comment]
Rephrased with explanation from neoraider on the Gluon Developer Meeting 2017/02/15

The hostname field in config mode should allow an empty preset - instead of defaulting to the nodes mac address, when empty or not set in `site.conf`.
