### ISSUE TITLE
D-Link DIR-615 Rev. Hx

### ISSUE THREAD

**Issue by HACKER-3000** [freifunk-gluon/gluon#1164]
Whats about a gluon for the "D-Link DIR-615 Revension Hx"?
OpenWRT is avaible for it!

Thanks☺️

**Comment by NeoRaider** [comment]
I've added support to the ramips-rt305x target, it is completely untested though. Also, ramips-rt305x is not officially supported by Gluon at the moment, to BROKEN=1 must be passed to build the target.
