### ISSUE TITLE
Default settings for local wireless acces

### ISSUE THREAD

**Issue by jerix777** [freifunk-gluon/gluon#1170]
Hi ! I've installed gluon on my TP-Link WA801ND V3 through WIFI cause the single ethernet port on the device is bricked in my case.
So now, i can't access the device. But, leds blinks normally (power first, ethernet after... no wifi).
 Is there a way to access the device ?

**Comment by jerix777** [comment]
Normally (i think...) wireless must be ON and available on after boot ! non ?

**Comment by NeoRaider** [comment]
After flashing initially, a Gluon node will be in "Config Mode", the first-setup wizard. For security reasons, only wired access is available in Config Mode.

If your Ethernet is broken, the only way to access the device is to open it and connect to the serial console.

**Comment by jerix777** [comment]
Wow ! serial connector ! ok, i'm going to buy it and hope that it will solve the problem. 
But, i think that wireless must be available on "Config Mode" too. That will make life easier for us.
Thanks for your response **NeoRaider** !

**Comment by NeoRaider** [comment]
@jerix777 This has been discussed before, and there is simply no way to provide wireless access in a secure way without previous configuration of credentials. Therefore, we'll always require Ethernet access for the initial configuration.

**Comment by jerix777** [comment]
Okay. But I regret my imprudence anyway. Thanks

**Comment by jerix777** [comment]
Please may i have the related link of that thread ?

**Comment by jplitza** [comment]
@jerix777 See for example #683 and the links in there.

**Comment by jerix777** [comment]
@jplitza  Ok. If I was able to turn back hte time...
Anyway, if A=B and B=C then B **could be** equal C.
Thanks a lot ;)

**Comment by Adorfer** [comment]
> This has been discussed before, and there is simply no way to provide wireless access in a secure way without previous configuration of credentials. 

There is one, which hardly anybody will like to use: setup a private wifi with random password. 
Put out the password (12 digits. numbers and letters) as morse code, there are LEDs on most devices...<g>
