### ISSUE TITLE
Share local internet connection

### ISSUE THREAD

**Issue by jplitza** [freifunk-gluon/gluon#119]
It would be nice if there was an option to disable the anonymizing mesh routing and share the local internet connection (i.e. be DHCP server myself and route directly with NAT via my internet connection) in order to make the internet more usable (less delay).

Disadvantages:
* Advanced routing like ICVPN isn't available.
* Obviously, Störerhaftung.

Advantages:
* (Much) faster internet (RTT would be reduced by 2/3 in my case)
* Less reliance on central systems

I scrabbled together the needed points, because someone asked:
* have an IPv4 mesh address, preferably via DHCP
* set default route via br-wan
* be a DHCP server
* ignore DHCP requests from mesh: `ebtables -p IPv4 --ip-protocol udp --ip-destination-port 67 --logical-in br-client -i bat0 -j DROP` 
* don't send DHCP requests to mesh: `ebtables -p IPv4 --ip-protocol udp --ip-destinatino-port 67 --logical-out br-client -o bat0 -j DROP` (does this block the node's own requests?)
* enable NAT: `iptables -t nat -A POSTROUTING -o br-wan -j MASQUERADE`

**Comment by tcatm** [comment]
There's no good solution for how this could work with IPv6 so I'm marking this as wontfix.
