### ISSUE TITLE
Request for preserving the gw_mode over upgrades

### ISSUE THREAD

**Issue by jerix777** [freifunk-gluon/gluon#1196]
gw-mode is not preserves on sysupgrade.

**Comment by mweinelt** [comment]
Gluon blocks traffic from Mesh to WAN by default, batman's gateway mode isn't the only thing in your custom setup, is it?

**Comment by jerix777** [comment]
No, it's not the only. have try to have a special config mode too.

**Comment by jerix777** [comment]
Great ! I confirm it works now. Thanks @NeoRaider .
