### ISSUE TITLE
Autoupdater läuft als Zombie

### ISSUE THREAD

**Issue by MPW1412** [freifunk-gluon/gluon#1212]
Hallo,

wir haben jetzt beim Update von 2016.2.1 auf 2016.2.6 an vielen Stellen das Problem gehabt, dass Knoten sich nicht aktualiaisert haben, weil der Autoupdater als Zombie-Prozess lief. Ist das Problem bekannt? Die Knoten funktionierten ganz normal, daher kommen die Betreiber auch nicht auf die Idee, die Dinger neu zu starten. 

Gibt es da Erfahrungen zu?

Grüße
Matthias

**Comment by rotanid** [comment]
Das Problem ist bekannt und in aktuellen Versionen behoben.
Siehe dazu auch folgende issues:
#1160 
#1010 
#987

**Comment by MPW1412** [comment]
Ah danke für die Info. Hatte nach Autoupdater und zombie gesucht, aber war wohl blind. Danke für's Raussuchen!

**Comment by rotanid** [comment]
kein Problem. Meine Suche war:
https://github.com/freifunk-gluon/gluon/issues?utf8=%E2%9C%93&q=is%3Aissue%20autoupdater
