### ISSUE TITLE
VLAN not working in 11s config

### ISSUE THREAD

**Issue by mokkin** [freifunk-gluon/gluon#1213]
The configured VLAN isn't working since switching to 11s.
```
batctl if
mesh0: active
primary0: active
```
site.conf:
https://github.com/freifunk-leipzig/freifunk-gluon-leipzig/commit/f2fccb34a691b9bc4825f6e9c50a72b64a782508

**Comment by A-Kasper** [comment]
There is no VLAN support for 802.11s mode. So everything works fine.

VLAN support is already on the roadmap.

**Comment by NeoRaider** [comment]
As @A-Kasper correctly noted, Gluon does not support VLAN over 11s; it is simply not implemented. The VLAN support code adds unnecessary complexity to the network configuration without significant gain, so we don't intend to support it (and the current VLAN over IBSS code will be removed when we drop IBSS support).
