### ISSUE TITLE
Upgrading from a firmware to another firmware with different updateservers shows updateserver from previous firmware in Configmode even they are another site

### ISSUE THREAD

**Issue by MTRNord** [freifunk-gluon/gluon#1219]
When updating from gluon freifunk nord to freifunk schleswig-flensburg and keeping config (known that this isn't the correct behaviour) the new firmware shows old branches in the config mode. I know it is intended to keep the selected branch, when keeping configuration but all other bin existent should be cleaned up I think except the one selected. Maybe it should check if the side code changes and in that case also reset the autoupdater branch to not break the node on the next update. (Edit: correct spelling ;) )

**Comment by Adorfer** [comment]
this is a normal behavior, even if you migrate Nodes to another domain/community.
Same goes for vpn servers if you named them differently.
In such case you definitely have to operate with a dedicated migration-FW which blanks out the "non desired entries" of the old old domaindo

**Comment by rotanid** [comment]
as @Adorfer pointed out, this is expected behaviour.
