### ISSUE TITLE
Neither README nor repository description tells what gluon is.

### ISSUE THREAD

**Issue by vi** [freifunk-gluon/gluon#1220]
Repository description should at least mention "a modular framework for creating OpenWrt-based firmwares for wireless mesh nodes".

**Comment by rubo77** [comment]
It sais "This is the main repo of gluon. Start here! http://gluon.readthedocs.org/ " which tells you exactly that sentence.

But yes, I agree, that on the Github site, It would help if the title would contain describing keywords, so interested users in wifi mesh networks would find Gluon from around the world (SEO).

**Comment by rotanid** [comment]
as this can only be changed by an owner, i assigned the ticket to neoraider.

**Comment by rotanid** [comment]
fixed.
