### ISSUE TITLE
TL-WR1043NDv4: wrong MAC on devices that had newer stock-firmware

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1223]
if you get a TP-Link TL-WR1043ND with the stock firmware version 170401/2017-04-01 or you update an older one to this version - then the flashed LEDE or gluon doesn't find the MAC address anymore and uses something like "0000100000".

@NeoRaider created a patch ( https://paste.debian.net/plain/985485 ) that fixes the issue.
i tested this and it works as intended.

this ticket is intended to keep track of the status of integration into all the upstream & local branches as well as serve as an informational piece for people experiencing the same problem.

**Comment by Adorfer** [comment]
same issue on 2016.2.7
![grafik](https://user-images.githubusercontent.com/10302493/30270109-b5c731cc-96eb-11e7-9fd1-a0b1e12d4048.png)

**Comment by Adorfer** [comment]
btw: As a quickfix for affected nodes, you may assign a new ID manually: 

```
export NEWMAC=00:60:2f$(dd bs=1 count=3 if=/dev/random 2>/dev/null |hexdump -v -e '/1 ":%02x"'); echo $NEWMAC>/lib/gluon/core/sysconfig/primary_mac; export NEWKEY=$(fastd --generate-key|grep Secret|cut -d" " -f 2)
uci set fastd.mesh_vpn.secret=$NEWKEY; uci set network.client.macaddr=$NEWMAC; uci set network.bat0.macaddr=$NEWMAC; uci commit; echo NEWMAC  $NEWMAC; echo NEWFASTDKEY $NEWKEY
reboot;


```

**Comment by rotanid** [comment]
yup, has nothing to do with the gluon version, i already tested gluon v2016.2.x, gluon v2017.1.x, gluon master and lede-17.01 and lede-master -- all of these branches need the fix.

**Comment by Adorfer** [comment]
Do we have "hope" to have a patch in the v2016.2.x-release?
If not (since it's perhaps EOLed), then i would make a quickfix-script to run after installation in order to randomize the MAC.

**Comment by NeoRaider** [comment]
The backport was easy enough, so I pushed it to v2016.2.x, too.
