### ISSUE TITLE
Devices that don't support IBSS shouldn't be marked as BROKEN

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1242]
Currently four targets (ralink/mediatek) are marked as broken with the remark:
> BROKEN: No AP+IBSS support

This is not necessarily anything that will ever be resolved.

Since 802.11s is working quite well and seems to be the successor of IBSS those devices are hardly broken, but only useful if the site already uses 802.11s mesh networking. In turn these could be marked conditional with a flag like `MESH_11s` instead of `BROKEN`.

**Comment by rubo77** [comment]
You could also add a tag 2.4GHZ_ONLY i.e. for the C25

**Comment by rotanid** [comment]
@rubo77 please, separate issue, no derailing ;)

**Comment by NeoRaider** [comment]
I think a nice solution would be to change the *GLUON_ATH10K_MESH* variable to a generic *GLUON_WLAN_MESH*. It would default to 11s, skip building images for models that don't support the chosen mode (unless *BROKEN* is set), and select ath10k firmwares.

**Comment by FreifunkUFO** [comment]
yes, blame ath10k to NOT support ad-hoc.. 
we need more compatibility < https://github.com/libremesh/chef/issues/24

**Comment by rotanid** [comment]
FYI: @2tata created a patch #1298 to fix this issue. maybe take a look at it to check if it works for you, too.
