### ISSUE TITLE
support for TP-Link Archer C7 v4

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1252]
there's a new revision of the Archer C7 Dual-Band router.
https://wikidevi.com/wiki/TP-LINK_Archer_C7_v4.x
it has the QCA9563 chip instead of the QCA9558 the v2 had.
it has 750 instead of 720 MHz.
LEDE supports it in the master branch for a few weeks now, the backport should be similar in volume to the C25 backport.
https://git.lede-project.org/?p=source.git;a=commit;h=9887afb1afcf387f6892315413e610a6816df463
maybe a country code fix is necessary:
https://github.com/lede-project/source/pull/1490

**Comment by blocktrron** [comment]
Does someone have a Archer C7v4 and is able to tell me
a) the MAC-Address on the bottom
b) the MAC-Address used on the 5GHz WiFi

I'm currently working on a Gluon backport and i am not aware of a way to restore the Device to stock firmware once LEDE is flashed 😕
