### ISSUE TITLE
soft-brick on sysupgrade with UAP AC Pro with v2016.2.7 and later

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1253]
there may be a bug or at least problem in some cases with updates of the Ubiquiti UAP AC Pro devices.
i have four of these devices running Gluon, all have been bought in the 2nd half of 2016.

two of them soft-bricked reproducibly if they are updated from Gluon v2016.2.7 to a later build (e.g. v2017.1.3) or also from v2017.1.3 to any later commit of v2017.1.x.
the updates of earlier version worked well.
the device does look "dead" after the failed sysupgrade.
you have to do a TFTP flash of the stock firmware and afterwards flash Gluon again and configure it to make the device work again. which gluon version you flash doesn't matter as the "mtd" flash via the stock firmware works well even with newest builds.

two other devices don't show this problem.
the difference between those groups of devices is, that the ones showing the problem are mounted at the ceiling of a fashion boutique and get their power from HP PoE switches via rather long cables.
the working ones use PoE, too - but with cables <10m.

my guess is, that the changes to sysupgrade starting with v2016.2.7 someshow resulted in increased power usage that results in problems together with long cables?
sounds crazy, other ideas are very welcome!

**Comment by Adorfer** [comment]
just for curiosity: What is the "result" of the "softbrick"? What is the state the unit is to be found after the failed upgrade?
defective image -> kernel panic when booting LEDE image, in other words: bootloader o.k, TFTPserver-rescue still possible?
More drastic? Or just "loss of config data, after powercycle without old parameters in setup-mode"?

**Comment by rotanid** [comment]
thanks for asking, i added that information above. the image isn't defective, it can be flashed after reverting to stock via TFTP.

**Comment by mweinelt** [comment]
Does the sysupgrade work on plain LEDE?

It would probably be helpful if you provided a serial log of the upgrade process and the boot after that.

**Comment by rotanid** [comment]
you already wrote that on IRC and you know the answer. how should i pack a serial console at the ceiling of a store? and they wouldnt be happy if i crack their devices open anyways.
as i already said, the sysupgrade works on other devices of the same type with a much shorter cable. at lease i don't see any other difference between the similar devices than the cable length.

**Comment by NeoRaider** [comment]
Maybe you could try to replicate the situation with a long cable on a device you can get a console log from?

**Comment by rotanid** [comment]
thanks, this is already on my todo list. have to find time for that...

**Comment by rotanid** [comment]
this issue is probably the same as #1301

**Comment by rotanid** [comment]
i tested it today in depth and it indeed seems to be #1301
