### ISSUE TITLE
autoupdate url with ipv6 address not possible in gluon 2017 (lede wget ommits square brackets on ipv6-addresses)

### ISSUE THREAD

**Issue by TomSiener** [freifunk-gluon/gluon#1254]
We use the ipv6-address as fallback mirror for our firmware updates in case of dns not working.
Since gluon 2017 (LEDE) this is not working anymore (server is returning error 400 Bad Request)

The analysis of this phenomenon was leeding to the following issue:
The wget that comes with lede does not sourround the ipv6-address in square brackets in the http request:
- OpenWrt:...Host: **[**2a03:2260:300c:999::b**]**
- LEDE:............Host: 2a03:2260:300c:999::b

The newer apache versions are rejecting this by default for secutiry reasons.
As a workaround, it is prossible to set the apache  HttpProtocolOptions Directive to Unsafe, which is not really recommended.

**Comment by NeoRaider** [comment]
Fixed since a8067e0a2f8cee3bcbf40cbb302f624e62d2f02d / 491e8e03328168206e2446cf804b405f1ccc76b4, fix released in v2017.1.3.
