### ISSUE TITLE
build dies when GLUON_SITE is a relative path

### ISSUE THREAD

**Issue by edeso** [freifunk-gluon/gluon#1264]
#$ make GLUON_TARGET=ar71xx-generic DEVICES=tp-link-archer-c25-v1 -j 1 BROKEN=1 GLUON_SITEDIR=../site-ffkbuk/ V=s

```
make[4]: Entering directory '/raider/foo/gluon/gluon2017.1.4/package/gluon-site'
GLUON_SITEDIR='../site-ffkbuk/' lua -e 'print(require("cjson").encode(assert(dofile("../../scripts/site_config.lua"))))' > /raider/foo/gluon/gluon2017.1.4/lede/build_dir/target-mips_24kc_musl-1.1.16/gluon-site/site.json
lua: ../../scripts/site_config.lua:9: ../../scripts/site_config.lua:5: attempt to index a nil value
stack traceback:
        [C]: ?
        [C]: in function 'load'
        ../../scripts/site_config.lua:9: in main chunk
        [C]: in function 'dofile'
        (command line):1: in main chunk
        [C]: ?
stack traceback:
        [C]: in function 'assert'
        ../../scripts/site_config.lua:9: in main chunk
        [C]: in function 'dofile'
        (command line):1: in main chunk
        [C]: ?
Makefile:60: recipe for target '/path/gluon2017.1.4/lede/build_dir/target-mips_24kc_musl-1.1.16/gluon-site/.built' failed
```

the probably easiest fix would be to assure that GLUON_SITEDIR is absolute by modifying it in the gluon buildroot Makefile. stackoverflow suggests realpath if gluon is Gnu make specific
  https://stackoverflow.com/questions/5969129/makefile-expand-relative-prefix-path

..ede

**Comment by NeoRaider** [comment]
Using realpath to allow passing a relative path would be fine, LEDE requires GNU Make anyways. If someone wants to propose a patch, the same should be done for all paths defined at the top of the Makefile, not just GLUON_SITEDIR.
