### ISSUE TITLE
Config interface: missing :checked-state for mesh_wan_legacy/mesh_lan_legacy

### ISSUE THREAD

**Issue by ArwedSchmidt** [freifunk-gluon/gluon#1269]
I noticed that mesh_lan/wan_legacy state is reset to off whenever you leave the config -> advanced interface (e.g. back to wizard or after re-entering config mode).

Code that implemented this checkbox can be found at 0ceb25e3e7775a356ac01cc455bc411978fe9d1f

**Comment by bobcanthelpyou** [comment]
@ArwedSchmidt Do you use the submit button to save your changes before leaving the page?

**Comment by ArwedSchmidt** [comment]
Ofc
