### ISSUE TITLE
sysupgrade on alfa network n2/n5 fails

### ISSUE THREAD

**Issue by heini66** [freifunk-gluon/gluon#1271]
factory flashing 2016.2.7 works.
flashing 2017.1.4 via config mode and scp/ssh sysupgrade over 2016.2.7 fails.
flashing 2016.2.7 sysupgrade over 2016.2.7 fails.

contact me via irc / mail if any information form the node is required.

**Comment by heini66** [comment]
flashing 2016.2.3 over 2016.2.7 works.
flashing 2017.1.4 over 2016.2.3 works.

**Comment by mweinelt** [comment]
It would probably be helpful if you could provide a serial log of update progress, otherwise this seems to be guesswork.

**Comment by heini66** [comment]
pls close the ticket, havn't the hardware in my hands...
