### ISSUE TITLE
ath9k wifi stops working occasionally

### ISSUE THREAD

**Issue by lost-tty** [freifunk-gluon/gluon#130]
This issue tracks the sporadic loss of wireless functionality on ath9k based nodes running **Gluon 2014.2**. Before reporting new information from hung nodes, make sure the node is actually running a firmware based on this specific Gluon version.
# What to report

If you notice this particular problem on your node, please report at least the following information by posting a comment on this issue:
- Gluon version (tag or commit) the node is running.
- output of `cat /tmp/sysinfo/model`
- uptime
- contents of these files:
  - `/sys/kernel/debug/ieee80211/phy0/ath9k/reset`
  - `/sys/kernel/debug/ieee80211/phy0/ath9k/queues`
- Check the contents of `/sys/kernel/debug/ieee80211/phy0/ath9k/interrupt` twice with about 10 seconds inbetween. Report whether the `RXLP`, `RXHP` and `TX` values are increasing. 
- Check the last few lines of `dmesg`. Report anything mentioning `ath9k` or `phy0` with timestamps close to the event (compare with uptime). Do not post repeated messages.
# Symptoms

We are aware of the following indicators related to the loss of wifi functionality.
## Best Effort queue stopped

In the output of `cat /sys/kernel/debug/ieee80211/phy0/ath9k/queues` the `(BE)` entry will read `stopped: 1`. This seems to be a very strong indicator.

If possible, let your node continue running in this state for up to 12 hours, while checking regularly whether for the queue to be still stopped. In some cases this problem will resolve itself. Should your node recover on its own, please _edit_ your original report instead of adding a new comment.

If you can't wait, running `wifi` is enough to get your node working again. There's no need to reboot.
## Mesh partners lost

In some cases `batctl o|grep wlan0` will not show mesh partners anymore, yet the Best Effort queue is **not stopped**. If you notice this problem, please file a complete report.
# Misc.
- ath9k is instable since http://git.openwrt.org/?p=12.09/openwrt.git;a=commit;h=d29f21c84e2d8af8a5c18ceae80426c026ddac07
- http://kbu.freifunk.net/wiki/index.php?title=Ath9k-Probleme

**Comment by rotanid** [comment]
as we (Freifunk Altdorf) and also Freifunk München (derkalle) are experiencing problems which seem to be closely related to this one i'd like to reopen this issue.
for a start i have a first report with the data you asked for in the starting post of this issue:

gluon version:
v2016.1
model:
TP-Link TL-WR1043N/ND v2
uptime:
9 days, 8:50
(issue on this device started at around uptime 7 days 14:50)

# cat /sys/kernel/debug/ieee80211/phy0/ath9k/reset
```
Baseband Hang:  0
Baseband Watchdog: 18860
   Fatal HW Error:  0
      TX HW error:  0
 Transmit timeout:  0
     TX Path Hang:  4
      PLL RX Hang:  0
         MAC Hang:  0
     Stuck Beacon: 401
        MCI Reset:  0
Calibration error:  7
Tx DMA stop error: 385
Rx DMA stop error:  0
```

# cat /sys/kernel/debug/ieee80211/phy0/ath9k/queues
```
(VO):  qnum: 3 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(VI):  qnum: 2 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(BE):  qnum: 1 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(BK):  qnum: 0 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(CAB): qnum: 8 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
```

# compare 10s /sys/kernel/debug/ieee80211/phy0/ath9k/interrupt
--> only the TX value increased

dmesg:
only
[658158.970000] ath: phy0: Timeout while waiting for nf to load: AR_PHY_AGC_CONTROL=0xc05da
(but timestamp not related to event)


batctl o|grep phy0
--> shows now mesh partners

**Comment by Adorfer** [comment]
i can't provide logs for the moment, but with 2016.1.3 we see regularly nodes dropping wifimesh links from stable >70% TQ to about 2-3%TQ on ALL ibss0-neighbors. 
And recovery after invoking _wifi_

**Comment by rotanid** [comment]
gluon version:
v2016.1
model:
TP-Link TL-WR1043N/ND v2
uptime:
74 days, 18:49

cat /sys/kernel/debug/ieee80211/phy0/ath9k/reset
```
    Baseband Hang:  0
Baseband Watchdog: 61172
   Fatal HW Error:  0
      TX HW error:  0
 Transmit timeout:  0
     TX Path Hang: 99
      PLL RX Hang:  0
         MAC Hang:  0
     Stuck Beacon: 52706
        MCI Reset:  0
Calibration error: 345
Tx DMA stop error: 53180
Rx DMA stop error:  1
```
cat /sys/kernel/debug/ieee80211/phy0/ath9k/queues
```
(VO):  qnum: 3 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(VI):  qnum: 2 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(BE):  qnum: 1 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(BK):  qnum: 0 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
(CAB): qnum: 8 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
```

compare 10s /sys/kernel/debug/ieee80211/phy0/ath9k/interrupt
--> only the TX value increased

dmesg:
only very often
[6412447.740000] ath: phy0: Timeout while waiting for nf to load: AR_PHY_AGC_CONTROL=0xc05da
(but timestamp not related to event)

batctl o
--> shows now mesh partners other than on mesh-vpn


it seems the "Calibration error" counter is a good sign, the problem is that it doesn't reset after issuing "wifi".
if you stop wifi, unload the ath9k kernel module and load it again, the wifi starts with an increased phy# number every time until you reboot... not ideal, there has to be a nicer way
