### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by HACKER-3000** [freifunk-gluon/gluon#1375]
Just getting:

make[1]: Leaving directory '/home/arvid/ffgluon/lede'
Configuration failed:
 * unable to enable package 'gluon-ebtables-segment-mld'
Makefile:124: die Regel für Ziel „config“ scheiterte
make: *** [config] Fehler 1

**Comment by kpanic23** [comment]
Just remove the line "gluon-ebtables-segment-mld" from site/site.mk

**Comment by mweinelt** [comment]
`gluon-ebtables-segment-mld` was merged into core.

**Comment by HACKER-3000** [comment]
thx
