### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by HACKER-3000** [freifunk-gluon/gluon#1376]
getting:

lede/staging_dir/hostpkg/bin/lua: scripts/site_config.lua:10: scripts/site_config.lua:6: attempt to index a nil value
stack traceback:
	[C]: ?
	[C]: in function 'load'
	scripts/site_config.lua:10: in main chunk
	[C]: ?
stack traceback:
	[C]: in function 'assert'
	scripts/site_config.lua:10: in main chunk
	[C]: ?
Your site configuration (site.conf) did not pass validation.
Makefile:148: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 1

**Comment by NeoRaider** [comment]
There is a syntax error in your site.conf.

This is a bug tracker. If you have questions about the Gluon build, use the mailing list or IRC.
