### ISSUE TITLE
Scheduled domain migration

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#1377]
As proposed in #1364, there should be a way to automatically migrate between mesh domains, ideally scheduled to avoid breaking meshing for longer than necessary. Such a scheduled migration could be used for a number of migration scenarios, like switching between VXLAN and legacy wired, IBSS and 11s, or to another wifi channel. Switching routing protocols, e.g. batadv 14 -> 15 or batadv -> babel are not possible though, as we can't install them in the same firmware. We could also do away with IBSS support when we drop VXLAN this way.

I think a scheduled migration is superior to parallel operation of mesh technologies (like IBSS+11s, or VXLAN+legacy), as weak nodes don't deal well with the additional traffic (especially in dense meshes where there are already multiple neighbours without seeing each twice).

One open question would be how to handle the scheduled switch when the time can't be determined because there is no mesh connection. Possible approaches include:
* Signalling between nodes (broadcasts on wired mesh, beacon stuffing for wireless)
* Alternating between both domains periodically (maybe switching every hour?) until an uplink connection is possible again

**Comment by T-X** [comment]
> I think a scheduled migration is superior to parallel operation of mesh technologies

In my opinion this depends. For Freifunk networks which often have many nodes and nodes with a limited amount of RAM I agree.

However I wouldn't say "superior". A parallel operation has its own advantages, too:

* Safer upgrade process: The new protocols can be verified before disabling the old one.
* With a scheduled update we have one shot and no more updates spread over weeks. Though some fallback/alternating between domains might mitigate this, this would still add complexity and might potentially cause unintended network splits?
* Parallel operation would be nice to have for comparisons and to be able to test new protocols in a large mesh network without affecting users before fully switching to it.
* Backup: Regarding protocols we so far have a very homogeneous setup. This makes us vulnerable to yet unknown but critical bugs in a mesh protocol. Running a secondary, auxiliary mesh protocol with slower update intervals could be interesting as a backup to increase the overall robustness.

But like I said, this only works if devices are beefy enough and/or if the network isn't too large.

**Comment by mweinelt** [comment]
Fixed in https://github.com/freifunk-gluon/gluon/pull/1555
