### ISSUE TITLE
gluon-status-page: show additional info

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1415]
inspired by #1402 
related and maybe partly depending on #644
show the pretty names for additional data and hide the labels for unavailable fields

- ~~site~~ 21397ce678c32539247196135e3c30d914d5c592
- ~~domain~~ 21397ce678c32539247196135e3c30d914d5c592
- ~~roles~~ 490c522351e237ad43ab06c9d0bb8774feaca01e
- ~~wifi channels~~ 0ce961eb8c27df967e2dc3599ed2518a1d2e0faf
- bandwidth limit #2217 #2216
- ~~VPN type (active / fastd / l2tp / ...)~~ 16c5c64141ff0147943408cf7483ac64caa4479a
- ~~batman version / babel~~ 0ac3061225b255ecf81224e96ee3b80862f2d853
- ~~nexthop~~ #1878

**Comment by mweinelt** [comment]
Domain pretty names is pretty expensive right now. We get the value in `nodeinfo.system.domain_code` and have to look at all files in `/lib/gluon/domains/*.json`.
A package that does this is `gluon-config-mode-domain-select` but that's because it shows all pretty names anyway.

**Comment by rotanid** [comment]
showing the non-pretty names would still be an improvement ;)

**Comment by mweinelt** [comment]
Really? `ffda_da_220_230` doesn't sound like anything I'd put on a status page.

**Comment by rotanid** [comment]
more than nothing, although not ideal.
judging from our experience, no one except people with deep technical knowledge uses the status page anyway...

**Comment by ambassador86** [comment]
I am preparing a patch for this in https://github.com/FreifunkChemnitz/gluon/tree/status-page-extension I will add a PR as soon as I am happy with it.

**Comment by mweinelt** [comment]
If traffic limits are in place it would be great to publish them on the status-page as well.

**Comment by rotanid** [comment]
added wifi channels, from #1727

**Comment by lemoer** [comment]
@rotanid nexthop is done

**Comment by AiyionPrime** [comment]
Something I lacked in the last years  and compensated by memorizing more and more router models was the base frequency of a nodes processor, as well as his installed ram. Is that something someone else missed as well?

@rotanid May you explain what `roles` is expected to contain?
Like whether a node is a supernode or not, based on `nodeinfo.vpn`?

**Comment by AiyionPrime** [comment]
TIL: site.conf provides a 'roles' parameter:

> Nodes will announce their role inside the mesh. This will allow in the backend to distinguish between normal, backbone and service nodes or even gateways (if they advertise that role). It is up to the community which roles to define.

example:
```
roles = {
  default = 'node',
  list = {
    'node',
    'test',
    'backbone',
    'service',
  },
},
```

https://gluon.readthedocs.io/en/latest/user/site.html

**Comment by AiyionPrime** [comment]
Huh, seems like I did not commit the related changes back then. Sorry.
Find the implemenatation of `system.role` in https://github.com/freifunk-gluon/gluon/pull/2200.

**Comment by Adorfer** [comment]
please add **"batman  MainIF/MAC"**
(nodeid is in most (all?) cases different, many batctl-functions require the MainIF-MAC, not the one from the status page)

**Comment by Adorfer** [comment]
please add 
- "Mesh-Interface-Names"  (to see if MoW/MoL is enabled, or if mesh on radio0/1 is on)
- "Client interface names" (so see if Lan-Client or AP on radio0/1 is enabled)

**Comment by blocktrron** [comment]
> or if mesh on radio0/1 is on

This is already provided by the mesh signal histogram

**Comment by AiyionPrime** [comment]
@rotanid 
> roles

is done since 490c522351e237ad43ab06c9d0bb8774feaca01e and

> wifi channels

as well: 0ce961eb8c27df967e2dc3599ed2518a1d2e0faf.

**Comment by AiyionPrime** [comment]
@rotanid
> VPN type (active / fastd / l2tp / ...)

is done since 16c5c64141ff0147943408cf7483ac64caa4479a
