### ISSUE TITLE
next: dnsmasq not started at boot

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1429]
On `next` since roughly end of may the dnsmasq instance for clients/mesh doesn't start on boot.

The configuration in `/etc/config/dhcp` looks the same as on `master`. It can be started through `/etc/init.d/dnsmasq start` without problems.

**Comment by blocktrron** [comment]
Seems to be related with https://github.com/openwrt/openwrt/commit/ecd954d5302b2d135005ca68c206bb2d544b0bde

**Comment by NeoRaider** [comment]
http://lists.openwrt.org/pipermail/openwrt-devel/2018-June/012876.html
