### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1433]
We need a pull request template to improve on applying our guidelines and better able to track progress of pull requests.

@skorpy2009 and @rotanid wanted to take care of that. I recommend HackMD to collaborately build the text and neoraider recommended to use HTML comments to hide explanations etc..

Make use of our notes from the meeting here: https://md.darmstadt.ccc.de/gluon-device-support-policy#

**Comment by skorpy2009** [comment]
This depends on #1438 & #1434

**Comment by mweinelt** [comment]
GitHub allows for several different types of ISSUE_TEMPLATEs, probably the same for pull requests, so we don't need to cram everything into a single template.

https://blog.github.com/2018-05-02-issue-template-improvements/

via https://github.com/ffrgb/meshviewer/tree/develop/.github/ISSUE_TEMPLATE

**Comment by rotanid** [comment]
@mweinelt you can only add a single PR template at the moment, as far as i can see it

**Comment by mweinelt** [comment]
Sure, but better start somewhere, GitHub will follow at some point.

**Comment by rotanid** [comment]
sure, feel free to do a pull request adding templates ;)

**Comment by christf** [comment]
which problem are we addressing with these templates?

**Comment by mweinelt** [comment]
Lack of information and structure in pull requests. Like when you add a new device you'd get the device checklist by default. 

The issue is that we currently can only have on PR template as it looks.

**Comment by mweinelt** [comment]
This did not pan out, which is fine, since nobody seems to be complaining about the current state of PR descriptions.
