### ISSUE TITLE
migrate protocol of the 2018/02 meeting to gluon's Github wiki

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1439]
the protocol of the 2018/02 meeting was drafted on a pad:
https://pad.freifunk.net/p/gluon-dev-meeting-2018-2

it has to be migrated into the github wiki, including better structure and wording, looks like a memo in some places at the moment
https://github.com/freifunk-gluon/gluon/wiki/Meeting-2018-02

**Comment by Brother-Lal** [comment]
I migrated a first draft already.
Improvements very welcome - markdown is weird...

**Comment by rotanid** [comment]
thanks, i only made minor changes and consider it done.
