### ISSUE TITLE
Nach Firmware Update automatisch ins Menü zurück

### ISSUE THREAD

**Issue by klausdint** [freifunk-gluon/gluon#1461]
Bei den Firmware Update einer FritzBox wird man automatisch nach dem Progress Bildschirm auf die Anmeldeseite weitergeleitet, sobald der Router neu gestartet und wieder erreichbar ist. Lässt sich dies auch für die Freifunk Firmware umsetzen?

**Comment by rotanid** [comment]
@klausdint dazu gibt es bereits ein Issue #339 , bitte dort weitermachen, ich schließe hier.
