### ISSUE TITLE
Konfiguration sichern, wiederherstellen, zurücksetzen

### ISSUE THREAD

**Issue by klausdint** [freifunk-gluon/gluon#1462]
Bitte eine Möglichkeit hinzufügen, auf der Config-Seite und ggf. über CLI die aktuelle Konfiguration des Routers zu sichern (download auf PC) und gespeicherte Konfigurationen wiederherzustellen. Außerdem sollte es möglich sein, den Router auf "Freifunk Werkseinstellungen" zurücksetzen zu lassen.

**Comment by Adorfer** [comment]
Für "Werkseinstellungen" würde ein Package reichen, was "firstboot" auf einen Button legt.. wobei bei X86 (also wo ein ext-fs drunter liegt) geht das afaik nicht.

**Comment by rubo77** [comment]
Werkseinstellungen ist ja einfach: Firmware updaten ohne den Haken

**Comment by rubo77** [comment]
Eine Sicherung erstellen, geht ja wohl per SSH: das Verzeichnis /etc backuppen

**Comment by Adorfer** [comment]
at the moment you enable "restore" of configs, you will have to deal with configs of potentially "very old versions" 
or even "from incompatible communities" (like l2tp vs fastd...)
there is a lot to check before accepting a dump to be dropped into /etc. 

in other words: implementation will not be easy, even to check "if it's compatible at all."

**Comment by rotanid** [comment]
i understand that this would help a user, but as others already wrote it would be very complex to implement, therefore we won't do it.
/
Die Idee verstehe ich aus Anwendersicht, hat jedoch - wie von anderen bereits beschrieben - so viele Fallstricke bei der Implementierung, dass wir das nicht machen werden.
