### ISSUE TITLE
doc: add list with possible features

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#1464]
It would be nice if there would be a list with all possible features addable to site.mk in the documentation with short explaination and if needed link to more information.

**Comment by rubo77** [comment]
It is already quite well explained here:

https://github.com/freifunk-gluon/gluon/blob/master/docs/user/site.rst#feature-flags

>The file package/features in the Gluon repository (or features in site feeds) can specify additional rules for deriving package lists
> ...
> For convenience, there are two feature flags that do not directly correspond to a Gluon package...

the only thing I would add is a link on the filename, so it is more clearly, where to find more information:
https://github.com/freifunk-gluon/gluon/blob/master/package/features

**Comment by rotanid** [comment]
issue already answered by by @rubo77 , the release notes make this clear, too.

**Comment by A-Kasper** [comment]
Sorry, but I can't find it.
Where can I read which feature flags exist and what they are doing? Should everybody read sourcecode instead of  documentation?

**Comment by rubo77** [comment]
in the link i posted, it sais, 

> For convenience, there are two feature flags that do not directly correspond to a Gluon package:
>
>  -  web-wizard
>...
>  -  web-advanced

those are the only two features that exist right now.

apart from that you can put every gluon package without the prefix "gluon-" as feature in the feature list

so for example the package `gluon-status-page` can be added as single package, or as feature `status-page`.

It is of no concern to a "user" that the package `gluon-status-page-mesh-batman-adv` is also included in the feature `status-page`

just remove all the packages that are includedin those two features (web-wizard and web-advanced) and move all other packages from the old GLUON_SITE_PACKAGES variable into GLUON_FEATURES (removing the prefix `gluon-` everywhere) as you see here: https://github.com/freifunk-kiel/site-ffki/commit/8a05f8797356802cfd853e4f2db2f26e761f2602

**Comment by rubo77** [comment]
so this would be the complete list:

```
web-wizard
web-advanced

alfred
authorized-keys
autoupdater
client-bridge
config-mode-core
config-mode-domain-select
config-mode-theme
core
ebtables-filter-multicast
ebtables-filter-ra-dhcp
ebtables-limit-arp
ebtables-source-filter
ebtables
l3roamd
lock-password
mesh-batman-adv
mesh-vpn-core
mesh-vpn-fastd
mesh-vpn-tunneldigger
neighbour-info
node-info
radv-filterd
radvd
respondd
setup-mode
site
status-page
wan-dnsmasq
web-logging
web-mesh-vpn-fastd
web-model
web-node-role
web-private-wifi
```

**Comment by rubo77** [comment]
# short:

### 1) add those features:

    web-wizard
    web-advanced
    autoupdater
    status-page

## 2) remove those packages:

    gluon-web-admin
    gluon-web-network
    gluon-web-wifi-config
    gluon-config-mode-hostname
    gluon-config-mode-geo-location
    gluon-config-mode-contact-info'
    gluon-config-mode-autoupdater
    gluon-config-mode-mesh-vpn
    gluon-web-autoupdater
    gluon-status-page-mesh-batman-adv

## 3) move

all remaining packages starting with `gluon-` to features without prefix

**Comment by rubo77** [comment]
You can create a database automatically filled with data from the Makefiles of all packages with a script.

I created a script that generates a Markdown file:   
https://gist.github.com/rubo77/aee2886a78c62f5e3059d40a0c28b9b3#file-generate_markdown_of_packages-sh

If I put more time into this, I could also fill a database with that information and then generate a list with only packages that are non-linked by other packages
