### ISSUE TITLE
Status LED bei FW Update

### ISSUE THREAD

**Issue by ghost** [freifunk-gluon/gluon#1467]
lässt es sich vielleicht einrichten, dass wenn ein Firmware Update beim FF
Router durchgeführt wird (egal ob automatisch oder manuell durch
autoupdater -f oder über das Webinterface) dies durch das Blinken einer
Status LED wie der Power LED wie auch bei der Originalfirmware angezeigt
wird? So könnte verhindert werden, dass die Firmware gebricked wird, wenn
man das Gerät mal neu starten möchte, sich aber nicht sicher ist, ob nicht
gerade ein Firmware Update stattfindet. Man könnte dies dann direkt am
Gerät feststellen, ähnlich wie es z.B. auch beim Update der FritzBoxen der
Fall ist.

**Comment by blocktrron** [comment]
@klausdint I've just tried sysupgrading an Archer C7 and it's status LED was blinking while flashing the image. Maybe you've tried a device which LED is statically powered and therefore can't be controlled by OpenWRT?

**Comment by Adorfer** [comment]
Wenn man es rabulistich angehen wollte würde ich behaupten: Topic kann geschlossen weren, da zumindest bei >80% der Gluon-Router TP-Link-Geräte zum Einsatz kommen. Bei diesen blinkt während des Firmwareupdates auch bei Original-FW nicht die PowerLED. 
Die dahingehende Behauptung des Threadstarters ist nicht nachvollziehbar. 

Umgekehrt: Ja, irgendwelche Status-LEDs blinken zu lassen ist gut. Das Softbrick-Risiko ist bei aktuellen Firmwares aber geringt, da z.B. mit zwei Images (UBNT) gearbeitet wird oder aber heute schon während des Upgrades die Online-LED rasch blinkt "in der kritischen Phase" (siehe Post von blocktrron, aber beim 841er ist das ebenfalls so.)

**Comment by NeoRaider** [comment]
In OpenWrt, this is currently solved on a per-target basis (ar71xx does not have any upgrade indication at the moment AFAICT from the code).

I generally don't care about what the devices do with stock firmware - I would prefer to have consistent behaviour on all devices with OpenWrt/Gluon (as far as we have a status LED that can be controlled). In any case, this must be decided and solved in OpenWrt.

**Comment by klausdint** [comment]
Done: https://bugs.openwrt.org/index.php?do=details&task_id=2120

**Comment by blocktrron** [comment]
@klausdint This is no upstream issue as all targets in OpenWRT support update indication except for ar71xx. As ar71xx in the meantime became legacy, don't expect a fix there.

For the next time: upstream issues are best created in english (just like gluon issues)

**Comment by rotanid** [comment]
@blocktrron and for us, is there anything that can be improved or has to be done to support it like upstream?

**Comment by mweinelt** [comment]
@rotanid As we just make use of the upstream sysupgrade utility I would think it is completely within OpenWrt's purview.

**Comment by blocktrron** [comment]
@rotanid Maybe my statement was a bit misunderstanding - it is an upstream issue BUT as ar71xx ist considered legacy, i'm not sure if we should add a patch for this minor feature/bugfix (not sure what it is)

Anyway - this should be everything there is needed to let the status LED blink on a running update. It's not tested but maybe @klausdint wants to test and give feedback? https://github.com/blocktrron/openwrt/commit/01f12589873412ac3e9231a0d6eb6cf7897518c2

**Comment by klausdint** [comment]
Hello, I've tried it with a TP Link WR841n and it didn't worked there

Am Di., 12. Feb. 2019 um 22:58 Uhr schrieb David Bauer <
notifications@github.com>:

**Comment by klausdint** [comment]
Also it was not working with a TP Link WDR 3600 v1. The WR841n were v9 and
v8

Am Di., 12. Feb. 2019 um 22:58 Uhr schrieb David Bauer <
notifications@github.com>:

**Comment by CodeFetch** [comment]
Does it work with ath79?

**Comment by blocktrron** [comment]
Was implemented upstream with https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=9e1e4324690ecf3874acfab76566e856f133bf6f

If anybody wants this implemented in 2020.1, a backport PR can be opened. That said, it works on OF-platforms since 2018.2.
