### ISSUE TITLE
master: "make update" broken on fresh git clone

### ISSUE THREAD

**Issue by achterin** [freifunk-gluon/gluon#1471]
The following error occurs if you clone gluon and execute "make update":
> awk: fatal: cannot open file `openwrt/feeds.conf.default' for reading (No such file or directory)

The error is caused by line 5 of "scripts/modules.sh" because there is no openwrt folder existent after a fresh git clone.

**Comment by NeoRaider** [comment]
Fixed in 63c16c01a0923acc70edb9e32011335e637bb361.
