### ISSUE TITLE
Archer C2600 – Mesh-on-LAN interface unavailable

### ISSUE THREAD

**Issue by jotzt** [freifunk-gluon/gluon#1481]
On my Archer C2600 v1.1, the Mesh-on-LAN interface is not available after installation (gluon master 2018-07-13).

*EDIT: The interface is indeed available – and working –, however, I did not succeed running an IPv6 multicast-Ping between my computer and the MoL-interface.*

`/etc/config/network`
```
config interface 'mesh_lan'
	option igmp_snooping '0'
	option ifname 'eth1.1'
	option index '4'
	option proto 'gluon_wired'
	option disabled '0'
	option transitive '1'
	option macaddr 'xx:xx:xx:xx:xx:xx'
```
The *multicast ping receives replies* after adding the following lines (copied from a WR1043 config)

```
	option type 'bridge' 
	option auto '1'
```

**Comment by NeoRaider** [comment]
We do not make mesh_lan a bridge anymore since Gluon v2018.1; *auto* defaults to 1. (I also see the obsolete option `mesh 'bat0'`, which isn't used anymore since Gluon v2016.2.x; it seems our upgrade script do not clean this up completely...).

Is it possible that your eth1 interface appears in any other interface definitions like 'client'? I can't think of any other reason why the interface wouldn't come up.

**Comment by jotzt** [comment]
> I also see the obsolete option mesh 'bat0', which isn't used anymore since Gluon v2016.2.x; 
... and had been pasted into the issue by accident, see the edited version. Sorry for that.

I figured out that this is not an issue but a feature as I was used to connect my laptop to a MoL port before and and connecting to the router via its link local address of the MoL-port.

**Comment by NeoRaider** [comment]
That didn't really answer my question, and you changed the interface name in the example... Is eth1.1 used by any other interface definition?

**Comment by jotzt** [comment]
As far as I can recall, the situation was as follows:

* first firmware installation with Gluon V2018.1 -> eth1
* `sysupgrade -n <gluon-master>` -> eth1
* `firstboot` -> eth1.1

There was no manual interface configuration except the brigde/auto-setting

**Comment by NeoRaider** [comment]
How did you enable Mesh-on-LAN? If you did so via the command line, did you also disable the LAN port in the 'client' interface?

`firstboot` and `sysupgrade -n` should always yield the same configuration; I assume you did not upgrade to master with `-n`, so the old (untagged) switch configuration was retained (which is fine).

**Comment by jotzt** [comment]
Mesh-on-LAN was enabled by default. `site.config`: `mesh_on_lan = true,`

**Comment by NeoRaider** [comment]
I just read your edit. Everything seems in order, multicast pings might well be filtered by the firewall.
