### ISSUE TITLE
v2018.1.x: g0cb9888: x86 images may corrupt ext-fs

### ISSUE THREAD

**Issue by Adorfer** [freifunk-gluon/gluon#1504]
since https://github.com/freifunk-gluon/gluon/commit/0cb98882d05924878775196fcdfa600c3d846215
(this is kernel  4.4.140)
it looks that all images on x86/x64 (img.gz/kvm/vmdk) suffer from corrupt fs after 2nd or 3rd reboot. 
Kernel is stuck during mount on fs-check at about 4s in... sometimes after about 340 seconds anothter short message that stuff is really damaged. 

can be reproduced on multiple builds. On v2018.1-8 it was working fine. 
there are systems affected "running sysupgrade" and systems "fresh install from img.gz".

**Comment by rotanid** [comment]
as my builds are working OK, i added a "may" to the bug title.
@NeoRaider is already on it to get it fixed upstream (a kernel update in OpenWrt 17.01 branch is necessary) and probably update gluon master branch, too
