### ISSUE TITLE
RFC: Mention updater Bug and workarounds in 2018.1.0 Release notes

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#1519]
I think it would be good, if the bug (and also how to avoid that the problem appears) is mentioned in the Release notes.

**Comment by rotanid** [comment]
changing existing release notes doesn't help anyone, because the content of the following page will not be changed by your suggested change:
https://gluon.readthedocs.io/en/v2018.1/releases/v2018.1.html
we can only do this on v2018.1.1 release notes and i'm sure @NeoRaider will do this

**Comment by A-Kasper** [comment]
that is correct. sorry.

**Comment by NeoRaider** [comment]
We generally link the release notes in the stable branch rather than the release tag (  https://gluon.readthedocs.io/en/v2018.1.x/releases/v2018.1.html ), for the precise reason that we may want to update the release notes.
