### ISSUE TITLE
Githubmessages in Freifunk slack

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#1522]
I liked the messages in the gluon channel in Freifunk slack. The channel seems to be silent since 26 july.

**Comment by rotanid** [comment]
aha! we saw some slack webhook in the github configuration but didn't knew what it does and who it set up, so we removed it.

**Comment by A-Kasper** [comment]
There is a gluon channel in Freifunk Slack. Every commit was posted there by a bot. As far as I know only the repository owner is able to setup this service. It would be nice if it could be re-enabled. I liked it.

**Comment by rotanid** [comment]
and what is "Freifunk Slack"?
Does the repository owner need do create/have an account there? if yes, it probably won't happen. if not, we'll discuss.

**Comment by A-Kasper** [comment]
It is the slack of the Freifunk Rheinland. It's open.
Somebody already setup this function. As you know there was the necessary api key in github configured. I'll have a look how to reenable the bot. I think the owner just needs to communicate or accept an api key.

**Comment by rotanid** [comment]
as far as i know no one in the current gluon team uses the slack of freifunk rheinland - therefore it wouldn't be a good idea to give someone else an API key for the Gluon github organization...

**Comment by NeoRaider** [comment]
I assume the integration is using a webhook. Readding a webhook for push notifications shouldn't be a problem.

**Comment by nomaster** [comment]
The integration works with a dedicated GitHub Slack app that needs access to this project. So this can only be done of an orga or project member.

Alternately, we can use some RSS app to subscribe to release events.

**Comment by mweinelt** [comment]
Does this kind of integration really need organization access? https://slack.github.com/

**Comment by nomaster** [comment]
The Slack app has been released in a totally new, incompatible version back in July. Since then, the old version that is currently in use on Freifunk Slack is dysfunctional.

I recommend removing the old access and reinstalling the Slack app with the following command (in the channel #gluon on Freifunk Slack):
```
/github subscribe freifunk-gluon/gluon
```

**Comment by mweinelt** [comment]
So nothing for us to do, correct? If so, I'd close the issue.

**Comment by mweinelt** [comment]
Closing for lack of feedback.
