### ISSUE TITLE
TP-LINK Archer C20 v4

### ISSUE THREAD

**Issue by J0WI** [freifunk-gluon/gluon#1531]
Supported since OpenWRT 18.06 (2.4 GHz only): https://openwrt.org/toh/tp-link/tp-link_archer_c20_v4
Specs: https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c20_ac750_v4

There is already a pending PR for v1: #1508

**Comment by rotanid** [comment]
" As of mid-2018, OpenWrt works on it with most features, except for the 5GHz radio. The open-source driver for wireless (MT76) is significantly unstable, causing disconnects and (infrequent) lock-ups. "
as there are other devices on the wishlist which don't have the 5 GHz limitation, we should focus on those i guess.
that doesn't mean that we wouldn't accept this device with a broken flag, if someone does the work and testing.

**Comment by mweinelt** [comment]
Missing sysupgrade is a dealbreaker for me.

**Comment by mweinelt** [comment]
>  As of mid-2018, OpenWrt works on it with most features, except for the 5GHz radio. The open-source driver for wireless (MT76) is significantly unstable, causing disconnects and (infrequent) lock-ups. 

https://openwrt.org/toh/tp-link/tp-link_archer_c20_v4

**Comment by adlerweb** [comment]
`As of mid-2020 OpenWrt works with most, if not all, features.`

**Comment by mweinelt** [comment]
Yes?

**Comment by gerhardt** [comment]
Yes, this would be actually great to have some other low cost routers working.
