### ISSUE TITLE
fastd vpn encryption/performance option missing in configmode

### ISSUE THREAD

**Issue by Grotax** [freifunk-gluon/gluon#1536]
Today I received the question why the option to configure the fastd encryption was missing form the web-interface.
To be sure I did a extra build without any extra packages.
Still the option is missing.
Maybe the site config is incorrect but I think it's fine.
![config-mode](https://user-images.githubusercontent.com/5429298/45966177-af7a7e00-c02a-11e8-8ad6-197ac4208841.png)

Site config: https://github.com/ffsh/site/blob/testing/site.conf
Images: https://firmware.grotax.de/testing/
Build with https://github.com/freifunk-gluon/gluon/commit/51b7928a55155dc2a462cef5d4c045a81d9c1e0c

**Comment by NeoRaider** [comment]
The page is provided by the "web-mesh-vpn-fastd" GLUON_FEATURES entry. It is not included by default, as many sites don't want to allow configuring the encryption.

**Comment by Grotax** [comment]
Thank you for the quick response :)
