### ISSUE TITLE
How to persist firewall rule for additional VXLAN interfaces?

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1542]
Before VXLAN people often used additional VLAN interfaces to separate meshes at offloader setups for example.

Starting with VXLAN two things changed:
1. The proto needed to be updated from `gluon_mesh` to `gluon_wired`
2. The new interface needed to be added to the network list in the `wired_mesh` firewall zone

After reloading network and firewall this works.

After an upgrade however all additional interfaces are flushed from the `wired_mesh` zone, blocking VXLAN traffic on the additional interfaces.

The overwrite afaict happens here: https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-core/luasrc/lib/gluon/upgrade/140-firewall-rules#L85

What's the proper way to resolve this? For now the only way to solve this seems to be to duplicate the `wired_mesh` firewall zone and its rules. Please note, that firewall zone names may only have up to 14 characters in length.

**Comment by NeoRaider** [comment]
As explained on IRC, at the moment the best option is to duplicate the `wired_mesh` zone and rule, giving it a new name like `wired_custom`. We will revisit this when we add official support for additional mesh interfaces (with proper configuration via the web interface).
