### ISSUE TITLE
Unable to use DNS if not connected to a mesh vpn

### ISSUE THREAD

**Issue by yanosz** [freifunk-gluon/gluon#1575]
Is: 

Upstream DNS-Servers are ignored (see: https://gluon.readthedocs.io/en/v2018.1.x/user/faq.html#dns-does-not-work-on-the-nodes), thus connectivity problems to vpn-servers (aka supernodes) cannot be analysed using ping vpn.server.name

Should:
When connectivity problems occur, ping vpn.server.name using wan's DNS should be possible.

**Comment by NeoRaider** [comment]
While this is working as designed, I agree that sometimes ping tests from the WAN port are desirable.

At the moment, the used DNS servers (as well as IPv6 route table - IPv4 is not properly separated yet) are chosen based on the user's GID. I guess we could provide a little exec wrapper doing a setgid to `gluon-mesh-vpn`.
