### ISSUE TITLE
Add support for Opportunistic Wireless Encryption (OWE)

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1586]
OWE secures connections to the client radio with opportunistic encryption for devices that support it and offers a transition mode (by providing two VAPs) so both devices that can and can't are able to make use of the WiFi.

**Comment by J0WI** [comment]
Is this branch stable enough for testing?

**Comment by mweinelt** [comment]
Not on devices with less than 8 MB of flash.

**Comment by mweinelt** [comment]
We haven't yet been able to properly configure the transition SSID and we're too busy to give this more thought in 2019, therefore pushing back to 2020.1.

**Comment by mweinelt** [comment]
Fixed in https://github.com/freifunk-gluon/gluon/pull/1945.
