### ISSUE TITLE
config-config-mode-geolocation-osm: i18n issue

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1611]
Something in the osm patchset is messing with i18n. The first sentence in the section is the literal string, then the translated string follows.

![i18n issue](https://i.imgur.com/tZ9lKpm.png)

Maybe here? https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-config-mode-geo-location/luasrc/lib/gluon/config-mode/wizard/0400-geo-location.lua#L21

**Comment by NeoRaider** [comment]
Hmm, the POT/PO files of gluon-config-mode-geo-location haven't been updated. I assume the issue will also occur without the OSM package.

**Comment by NeoRaider** [comment]
Ah, it was the other way around. The POT/PO files were changed, but it seems the corresponding text change in the Lua sources got lost in a rebase.
