### ISSUE TITLE
OSM map does not appear

### ISSUE THREAD

**Issue by RalfJung** [freifunk-gluon/gluon#1612]
I have enabled and configured the OSM module, and yet when I go to the node configuration page, no OSM map appears.

From my `site.mk`:
```
GLUON_FEATURES := \
	autoupdater \
	mesh-batman-adv-15 \
	mesh-vpn-tunneldigger \
	ebtables-filter-multicast \
	ebtables-filter-ra-dhcp \
	ebtables-source-filter \
	ebtables-limit-arp \
	radvd \
	radv-filterd \
	respondd \
	web-wizard \
	web-osm \
	web-advanced \
	web-private-wifi \
	status-page
```

From my `site.conf`:
```
  config_mode = {
    geo_location = {
      osm = {
        center = {
          lat = 49.3761,
          lon = 6.9468,
        },
        zoom = 10,
      },
    },
  },
```

Is there a screenshot somewhere of where and how the map should appear?  I looked next to the geocoordinate input fields as well as in the advanced settings.

**Comment by belzebub40k** [comment]
There was a typo in the release notes. The feature is called *config-mode-geo-location-osm* (package
*gluon-config-mode-geo-location-osm*) https://github.com/freifunk-gluon/gluon/commit/cdbd7b65df48586c77eefd03aba5971e4c7df673

**Comment by RalfJung** [comment]
Confirmed, that fixes the problem.
