### ISSUE TITLE
firewall should allow gluon-announced to work on br-wan

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#162]

**Comment by NeoRaider** [comment]
This should be okay as long as only link-local source addresses are allowed. Otherwise, this would allow similar amplification attacks as we had with DNS before.

**Comment by NeoRaider** [comment]
Ah, only allowing `ff02::2:1001` as the destination and no unicast address of the node would have the same effect of only allowing requests from peers on the same link.

**Comment by NeoRaider** [comment]
Done.
