### ISSUE TITLE
Private WLAN Issue

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#1635]
Today I used an 841nd. Freifunk worked fine, but private wlan didn't. It was a mobile connection so all i know is that there was no internetconnection available. after rebooting the 841nd the issue disappeared.

**Comment by mweinelt** [comment]
Without further information this doesn't seem actionable.

**Comment by rotanid** [comment]
sure but even then it doesn't help much if you don't specify which exact version/commit you are running and what your site.conf/site.mk looks like :)

**Comment by rotanid** [comment]
no further information provided, closing.
