### ISSUE TITLE
TL-WA7210N internal antenna does not work

### ISSUE THREAD

**Issue by RalfJung** [freifunk-gluon/gluon#1639]
The TL-WA7210N is marked as supported, but I got reports from a user saying that while the firmware boots, the device only uses the internal antenna -- there is an external antenna connector, but it does not work.  Moreover, when using OpenWRT on that device, the internal antenna also does not seem to work very well: it does not see any other WiFis.  I am still awaiting conformation from the user whether the internal antenna works properly with Gluon.

This is confirmed by reports on the internet, such as [this one](https://forum.openwrt.org/t/people-asked-about-tl-wa7210n-but-nobody-told-them-that-the-firmware-is-useless/8000/16) and [this](https://forum.archive.openwrt.org/viewtopic.php?id=46779).

**Comment by RalfJung** [comment]
Sorry I misunderstood the user -- turns out that *only* the external antenna was active, meaning the internal antenna was useless and the device cannot be used without connecting an external antenna.

**Comment by rotanid** [comment]
this is an upstream issue al you already found the reports about upstream OpenWrt issues. please continue to provide your debugging information upstream, maybe also open a bug at https://bugs.openwrt.org if there isn't any, yet.

The only thing we could do is to mark it as BROKEN - which would have other problems...

**Comment by txt-file** [comment]
@rotanid What's your problem with marking the TL-WA7210N as BROKEN?

**Comment by rotanid** [comment]
that people who are already using the device wont get updates anymore

**Comment by mweinelt** [comment]
The `ar71xx-tiny` target which this device belongs to has been deprecated and it is unlikely that tracking this bug downstream is helpful. I'm therefore going to close it.

Speak up if you disagree.
