### ISSUE TITLE
802.1x authentication for open infrastructure 802.11s networks

### ISSUE THREAD

**Issue by CodeFetch** [freifunk-gluon/gluon#1660]
Using SAE with a pre-shared key does allow encryption, but not authentication of nodes if the PSK is publicly known. 
For open infrastructure networks a possibility to ensure at least trust on first use would be to initiate a connection between nodes using a publicly known PSK the first time, then generate a random PSK using that secure session and save it to flash on the peering nodes. A custom RADIUS server would be needed for that.

**Comment by mweinelt** [comment]
What would happen if either side lost its state due to a reset?

**Comment by CodeFetch** [comment]
They need to handle out new credentials. Actually I don't even know whether it is implemented open-source, yet. The goal of having something like that is to implement a trust model. If they lose their credentials, they lose their accumulated trust.

**Comment by mweinelt** [comment]
How would you distinguish lost state versus an attack by someone malicious?

**Comment by CodeFetch** [comment]
Distinguishing between a lost state and an attack is easy as the ID of the node should not rely on a MAC address, but a randomly initiated value. You could also use public key crypto for that. Trust models are the hard problem. They are ongoing research e.g. by the military. There are many papers about that. Some propose using neural networks other simple evidence based rating algorithms. For ordinary commercial networks you either use a shared PSK (which is prone to physical hacking) or a centralized trust agent which is a single point of failure and needs to be reachable all the time. Without having authenticated mesh connections, we have no possibility to implement trust models at all. Trust on first use would be a first step.

**Comment by mweinelt** [comment]
Closing as stale and unlikely to be implemented.
