### ISSUE TITLE
x86 sysupgrade fails on virtual machines due to partition size

### ISSUE THREAD

**Issue by mmalte** [freifunk-gluon/gluon#1673]
The Partition size of the x86 targets was changed upstream in https://github.com/lede-project/source/commit/a1f83bad606411a561e8e60110c71232b1a28aa2

As a result an upgrade of virtual gluon systems (ESXi based in this case) fails with a kernel panic, since the disk space is not sufficient for the new layout.

![kernel-panic](https://user-images.githubusercontent.com/6890998/54448939-3e03c880-474d-11e9-8858-6ac709719469.png)

The Update was performed from gluon based on v2016.2.7 with https://github.com/ffac/site/tree/v2016.2.7-1-s  to v2018.2 with https://github.com/ffac/site/tree/v2018.2-1-b

**Comment by mweinelt** [comment]
This was documented in the release notes for Gluon v2017.1. Skipping releases without reading the release notes in between the releases is a bad idea.

> Another potential issue mostly affects virtual machines: Gluon 2017.1 images are bigger than 2016.2.x images on x86. If your virtual harddisk is based on a 2016.2.x image, it must be resized to 273MB or bigger before upgrading to Gluon 2017.1.

https://gluon.readthedocs.io/en/v2018.2.x/releases/v2017.1.html#general-changes

**Comment by mmalte** [comment]
Thank you.
