### ISSUE TITLE
Wiki: Tunneldigger needs different UCI command for bandwidth limit

### ISSUE THREAD

**Issue by RalfJung** [freifunk-gluon/gluon#1685]
The UCI docs at https://github.com/freifunk-gluon/gluon/wiki/Commandline-administration#limit-bandwidth-gluon-2016x need updating for https://github.com/freifunk-gluon/gluon/commit/d87c4b521b2e891155241c01b98a7ac90a8883b9.

Should I just add a note saying to do `uci set tunneldigger.mesh_vpn.limit_bw_down=5000` when using Tunneldigger?

**Comment by rotanid** [comment]
the wiki can be edited by anyone, so just do it :)
