### ISSUE TITLE
tunneldigger client update

### ISSUE THREAD

**Issue by RalfJung** [freifunk-gluon/gluon#1688]
https://github.com/wlanslovenija/tunneldigger/pull/88 hast just landed in tunneldigger upstream, fixing https://github.com/wlanslovenija/tunneldigger/issues/87. It would be great to also get this update in Gluon.

**Comment by bobcanthelpyou** [comment]
Does https://github.com/freifunk-gluon/packages/pull/214 fix that issue?

**Comment by RalfJung** [comment]
Well, that applies a local patch instead of updating upstream. I assume usually updating upstream is preferred?

**Comment by bobcanthelpyou** [comment]
You mean updating the `PKG_SOURCE_VERSION` (and maybe `PKG_SOURCE_DATE`) in the tunneldigger `Makefile`?
https://github.com/freifunk-gluon/packages/blob/master/net/tunneldigger/Makefile#L9

**Comment by RalfJung** [comment]
Yes.

**Comment by bobcanthelpyou** [comment]
Then maybe https://github.com/freifunk-gluon/packages/pull/215 will update the tunneldigger package.

**Comment by rotanid** [comment]
new PR is #216 but it still needs some love

**Comment by kaechele** [comment]
Can be closed as freifunk-gluon/packages#216 is merged and https://github.com/freifunk-gluon/gluon/commit/01fd25de429e3a92d93ab551520f0500210daa1d happened.
