### ISSUE TITLE
iperf3 not working

### ISSUE THREAD

**Issue by lrnzo** [freifunk-gluon/gluon#1705]
Hello there,

back in v2017.1.8 you could install iperrf3 and run it as a server in order to measusre e.g. the throughput within a mesh. Since at least v2018.1.2 this seems to be broken. By ```iperf3 -sd``` it says that it would listen on port 5201. But the mentioned port stays closed, as you can you see by ```nmap -6 -p 5201 <ipv6 of the node>```. On current openwrt (18.06.2) this is working, so i thought it might be a gluon issue.

so long

**Comment by mweinelt** [comment]
This is because our firewalling has become much stricter since v2017.1.8. The INPUT policy now defaults to reject, so you need to open up a port in the relevant zone inside `/etc/config/firewall` and restart the firewall.

Note: This is unlikely to persist across sysupgrades.
