### ISSUE TITLE
docs: gluon-respondd: do not join link-local multicast group on br-client 

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1715]
The change in https://github.com/freifunk-gluon/gluon/commit/59a44274cb00e88e3420b4c9c4303ca70f16b211 drops the link-local multicast group on br-client, which is used by mesh-wide respondd queriers.

A documentation update is required to make users reconfigure their queriers for the site-local group.

The last documentation bits were here:
https://github.com/freifunk-gluon/gluon/blame/master/docs/releases/v2017.1.rst#L193-L194

**Comment by 2tata** [comment]
solved by #1818 ?

**Comment by mweinelt** [comment]
Yep, thanks. Closed!
