### ISSUE TITLE
Display Wifi Channels on Status Page

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/gluon#1727]
When working in the field it is helpful if all channels in use by the device are displayed on the status page to ease build local meshes.

Using a map to extract the information may not always be possible depending on the uplink working at that time. Keeping the information de-centrally matches the goals of the project.

**Comment by rotanid** [comment]
do you agree, #644 is enough and this is a duplicate?

**Comment by Adorfer** [comment]
@rotanid it depends if all available respondd-data displayed on the status page. 
If this is not the case, then it has to be added to the statuspage after it's integrated in the respondd-info.

**Comment by rotanid** [comment]
ok, but then this issues is blocked by the other one nevertheless.

**Comment by CodeFetch** [comment]
@rotanid Can you add this in #1415 and close this issue?
BTW this is also a part that should be modularized. #1415 is blocked by #1158...

**Comment by rotanid** [comment]
thanks, done.
