### ISSUE TITLE
mit mesh-on-wan und mesh-on-lan, sollte auch mesh-on-wlan konfigurierbar sein

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/gluon#173]
In Bereichen mit vielen Clients macht es Sinn, mehrere Router per Kabel zu vermaschen und mesh-on-wlan abzuschalten, damit die Luft entlastet wird.
Es wäre toll, wenn das im expert mode - wie die beiden anderen features auch - konfigurierbar wäre.

**Comment by NeoRaider** [comment]
Done.
