### ISSUE TITLE
Load Balancing

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#174]
Wenn möglich wäre ein Load-Ballancing innerhalb des Mesh-Netzes cool.
Wenn man 2 Knoten hat und an einem 100 am anderen nur 2 Clients hängen sollte der mit den 100 Clients Daten die Verbindung für einige seiner Clients über den 2. Knoten abwickeln.
Ähnlich bei der Netzauslastung: Hat ein Knoten 1 MBit freigegeben und ein anderer 10 MBit, dann sollte nach möglichkeit die Verbindung genutzt werden die performanter ist. Ein Load-Ballancing in dieser Form wäre ein ziemlich großes Projekt, aber sichlicht ein sehr coole feature.

**Comment by genofire** [comment]
Richtiger Anlaufpunkt wäre hier: http://www.open-mesh.org/projects/batman-adv/issues
