### ISSUE TITLE
announce simple-tc per respondd

### ISSUE THREAD

**Issue by genofire** [freifunk-gluon/gluon#1769]
It is really to searching for speed issues which could not be find, because this values are set:
- limit_enabled
- limit_ingress
- limit_egress

could we announce them by respondd ?
(for debugging it is okay, that we have not this values yet on the status page, we know how to request this values manuelle)

**Comment by rotanid** [comment]
related: #644

**Comment by CodeFetch** [comment]
@Adorfer Can you add these to your feature request? Means one issue less...

**Comment by Adorfer** [comment]
> Can you add

Done. hopefully i did not miss an aspect

**Comment by rotanid** [comment]
closing in favor of #644
