### ISSUE TITLE
Alfred stürzt ab

### ISSUE THREAD

**Issue by 4ndr3** [freifunk-gluon/gluon#177]
Firmware: hamburg 0.5, Gluon v2014.3
alfred 2013.4.0
Gerät: TP-Link TL-WR842N/ND v1
Anbindung: WLAN mesh
Uptime (beim bemerken des Fehlers): 327h
dmesg & logread: nichts

**Comment by NeoRaider** [comment]
Ein Log von einem Alfred-Crash unter 2014.4 wäre cool, da unter Barrier Breaker die Kernel-Symbole zur Verfügung stehen.

Nach dem Log von 2014.3.1 würde ich vermuten, dass in alfred alles ok ist, und der Fehler in batman-adv liegt.

**Comment by 4ndr3** [comment]
Wir haben 2014.4 als Beta rausgegeben. Wie bekommt man ein Log von dem Crash? dmesg & logread zeigten in der Vergangenheit nichts.

**Comment by NeoRaider** [comment]
Ich vermute, es war Glück, dass ich da nen Log bekommen habe. Wahrscheinlich gibt es (mindestens) 2 verschiedene Fehler, die Alfred zum Absturz bringen können, und einer davon erzeugt in nen Log in `dmesg`.

**Comment by T-X** [comment]
> Alfred-Crash unter 2014.3.1: https://gist.github.com/NeoRaider/607d146fbe0c84fb6aa8

Für mich sieht dieser trace nach einem Crash im Kernel aus. Magst du erläutern,

**Comment by NeoRaider** [comment]
Closing; alfred crashes have become very rare. Also, alfred will be replaced by respondd/announced in Gluon 2015.2.

**Comment by ohrensessel** [comment]
I don't know if we really can say that they have become rare. alfred on our gateways crashes quite frequently, if it crashes on nodes we don't know if we cannot distinguish offline nodes. we simply do not know if a node was taken offline by purpose, crashed for some obscur reason, or is seen as offline because alfred crashed.

**Comment by 4ndr3** [comment]
Tritt wieder vermehrt auf Knoten mit 2015.1 auf.
