### ISSUE TITLE
Private WLAN should support WPA3

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1826]
OpenWrt 19.07 has support for WPA3 and we should upgrade `web-private-wifi` to configure the private wifi in WPA2/WPA3 mixed mode.

- Upside is more secure connections for devices that support it.
- Downside is that we would need to bundle a cryptographic library.
  - This can therefore only be made available to devices with `>=8MB` of flash.

**Comment by blocktrron** [comment]
Be my guest: https://github.com/blocktrron/gluon/tree/wip-wpa3

**Comment by skorpy2009** [comment]
>Downside is that we would need to bundle a cryptographic library.
>* This can therefore only be made available to devices with >=8MB of flash.

A solution to this could be to just drop those devices with not enough flash.

**Comment by rotanid** [comment]
> > Downside is that we would need to bundle a cryptographic library.
> > 
> > * This can therefore only be made available to devices with >=8MB of flash.
> 
> A solution to this could be to just drop those devices with not enough flash.

why? they are marked as deprecated and we can simply not add such features to them.
