### ISSUE TITLE
Ubiquiti UniFi AC LR missing fitting line in manifest in v2018.2.x and newer

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#1834]
Gluon v2018.2.x and newer on a Ubiquiti UniFi AC LR does not find a fitting line in autoupdater manifests.
It worked with Gluon v2018.1.x

Output-Information with Gluon v2018.1.x (LEDE 17.01.x)
```
# lua -e 'print(require("platform_info").get_image_name())'
ubiquiti-unifi-ac-lite
# cat /tmp/sysinfo/board_name
unifiac-lite
# cat /tmp/sysinfo/model
Ubiquiti UniFi-AC-LITE
```
Output-Information with Gluon v2018.2.x (OpenWrt 18.06.x)
```
# lua -e 'print(require("platform_info").get_image_name())'
ubiquiti-unifi-ac-lite-mesh
# cat /tmp/sysinfo/board_name
unifiac-lite
# cat /tmp/sysinfo/model
Ubiquiti UniFi-AC-LITE/MESH
```

ubnt_unifi_ac_board_detect() does not know the magic of the Ubiquiti UniFi AC LR, yet.

With help from @mweinelt i found out the magic is `e527` by calling:
`dd if=eeprom iflag=skip_bytes bs=2 skip=12 count=1 2> /dev/null | hexdump -v -e "1/1 \"%02x\""`

The PR #1332 and its merged commit 6d005b9803b394e09deb2063cae422c5054c04d8 is wrong.

A quickfix in Gluon would be to replace the erroneously added alias `ubiquiti-unifi-ac-lr` with the alias `ubiquiti-unifi-ac-lite-mesh`

Model detection should be contributed in upstream OpenWrt nevertheless.

**Comment by rotanid** [comment]
i fixed the device alias in master branch, cherry-picked this to v2019.1.x branch and backported the fix to the v2018.2.x branch.

**Comment by rotanid** [comment]
let's keep this issue open until upstream model detection is done

**Comment by mweinelt** [comment]
@rotanid Gluon master includes 8cf67728d3b41c47ee5e322bb8c2908696380f24 now, so we need another update to reenable autoupdates afaict.
