### ISSUE TITLE
how to normalize weight

### ISSUE THREAD

**Issue by 791136190** [freifunk-gluon/gluon#1835]
in gluon how to normalize weight.
calss xxx(gluon.HybridBlock):
    self.conv = nn.conv2d(...)
 def hybrid_forward(self, F, x):
     self.conv.weight.var = F.L2Normalization(self.conv.weight.var(), mode='instance')
like this, it can work? thk

**Comment by mweinelt** [comment]
Hey, I don't believe this is the repository you were looking for.

Closing.
