### ISSUE TITLE
add Support for TP-Link RE450v3

### ISSUE THREAD

**Issue by larsan** [freifunk-gluon/gluon#1839]
We (ffbs) recently got word that the image for the RE450 could not be flashed to a newly acquired RE450 and it turns out that a third hardware revision was released, While the current builds only support V1 and V2, the list of supported devices does not differentiate between them.

It is not supported by openwrt yet and except for a single [thread](https://forum.openwrt.org/t/add-support-for-tp-link-re450-v3/35042) not a lot of information could be found. 

We received the device yesterday and so far it looks like the hardware is identical to V2 (regarding SoC, RAM, Flash, WLAN, Switch). If we find the time we will look further into it.

**Comment by achterin** [comment]
> While the current builds only support V1 and V2, the list of supported devices does not differentiate between them.

it doesnt differentiate because this is not true. gluon supports v1, only openwrt supports both. in my opinion v2 will never get fully supported by gluon (only with broken flag like re355) as its only available with 64mb ram, which is not enough to run both radios stable.

**Comment by NeoRaider** [comment]
Docs fixed in ed2479bd40613010a44a519c357a785a1c46b792 and f44a6342b46e1a9afc2760627f3070fe3e30fc9f.

**Comment by blocktrron** [comment]
Closing this, as hardware support is not a Gluon issue. If somebody ported the device or it was added to upstream OpenWrt it can be added to Gluon.
