### ISSUE TITLE
WDR4300 stuck after reboot

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#185]
On BB releases the WDR4300 has issues rebooting. It gets stuck and needs manual power cycle to properly boot again. This happens when the reboot command is issued or after autoupdates.

**Comment by NeoRaider** [comment]
I've replaced the workaround patch with the real fix from the OpenWrt trunk.

The fix hasn't been tested a lot yet, so it would be great if some people could check if the reboot issue reappears with the Gluon master, or if it is still fixed. Note that you need to clean your kernel tree to get the new patch (`make target/linux/clean` or simply `make clean`).

**Comment by NeoRaider** [comment]
Closing, the upstream fix has been verified and backported to BB.
