### ISSUE TITLE
Node role list in site.conf not working/ignored

### ISSUE THREAD

**Issue by dr2okevin** [freifunk-gluon/gluon#1851]
### Bug report ###

**What is the problem?**
changing the node role via web interface in Gluon 2019.1 is not possible, because the drop down contains only the default value.

**What is the expected behaviour?**
I would expect a drop down that contains all roles defined in the site.conf roles -> list section

**Gluon Version:**
v2019.1 

**Site Configuration:**
freifunk-pinneberg/firmware/blob/3ec2a6e3880df7f39049e6ee789415bcd77b6296/site.conf#L167-L178

**Custom patches:**
none

**Comment by rubo77** [comment]
this must be fixed in 2019.1.x too

**Comment by mweinelt** [comment]
See 4942602f7deeeac5931a2e177d13c2f121119853.
