### ISSUE TITLE
ebtables: misses MLD Queries

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#191]
There seem to be two issues currently:

1) Gluon filters allow icmpv6, but only if icmpv6 is the first next-header in the IPv6 packet. With MLD queries, there's a hop-by-hop-option (type 0) first, so the query is not forwarded into the mesh for instance.

2) ebtables filtering in the OUTPUT chain seems broken: The following ebtables log-rule:

<pre><code>ebtables -I OUTPUT -p IPv6 -o eth1 --logical-out br0 --log --log-level 6 --log-ip6 --log-prefix="~EBT: " -j DROP</code></pre>

results in:

<pre><code>~EBT:  IN= OUT=eth1 MAC source = 02:04:64:a4:39:c2 MAC dest = 33:33:00:00:00:01 proto = 0x86dd IPv6 SRC=64a4:39c2:86dd:6000:0000:0020:0001:fe80 IPv6 DST=0000:0000:0000:0004:64ff:fea4:39c2:ff02, IPv6 priority=0x3, Next Header=2</code></pre>

This is not only a bug in OpenWRT but happens with a vanilla 3.17-rc4 Linux kernels in VMs with plain, virtual ethernet interfaces, too.

Because it happens for the OUTPUT chain only and is off by 14 bytes (= ethernet-header length), it seems like the bridge and ebtables kernel code might have some misunderstanding, maybe some wrongly set "skb_network_header()" in the handed over skb and the assumption by ebtables that skb_network_header() were set correctly by the caller.

Suggestions for gluon:
* Allow IPv6 with hop-by-hop option as next-header for INPUT and FORWARD
* Disable IGMP/MLD querier in the bridge code (so that the hop-by-hop option in the OUTPUT chain would not be of interest for us anymore)
* Enable snooping on bridges again
* Disable multicast-to-unicast feature (it's currently broken by design, see: https://lists.openwrt.org/pipermail/openwrt-devel/2014-September/027859.html)
* Maybe backport fixes mentioned here: https://lists.openwrt.org/pipermail/openwrt-devel/2014-September/027876.html - for instance they prevent broken multicast/ipv6 if some malformed queries appear on the link

**Comment by T-X** [comment]
The patch and two more fixes got picked up by OpenWRT barrier breaker:

https://dev.openwrt.org/changeset/44049

Once Barrier Breaker is updated in Gluon too this ticket can be closed. I'll make a new ticket for bridge-snooping and changes in Gluon needed for that.

**Comment by NeoRaider** [comment]
I've updated the OpenWrt base module.
