### ISSUE TITLE
Archer C25 v1 not broken anymore

### ISSUE THREAD

**Issue by edeso** [freifunk-gluon/gluon#1921]
testing with recent Gluon 2019.1.x and the device seems to work as expected including 5GHz. not meshing over 5GHz though, so maybe someone wants to test that.

**Comment by blocktrron** [comment]
Sadly, the situation is the same as for the Archer C60. See https://github.com/freifunk-gluon/gluon/pull/1904#issuecomment-570401915

**Comment by rotanid** [comment]
we also had cases where it did work great, but that depends very much on the surroundings where it is placed and the specific use case.
therefore, Gluon does not accept ath10k devices with only 64M of memory as non-broken.

**Comment by edeso** [comment]
sad indeed. thanks for the insight though!
