### ISSUE TITLE
Principle of generating firmware-images

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-gluon/gluon#1934]
Some time ago I inspected your build-framework (somehow inspired by https://github.com/freifunk-berlin/firmware/issues/696#issuecomment-502466912) and would like to get a comfirmation, that I got your build-process right.

1. building host-lua
2. using ```target_config.lua``` to create a openwrt/.config
2.1. this  sets the CONFIG_options as per ```targets/generic```
2.2. this sets all CONFIG_options as per ```config``` directive of ```targets/$arch```
2.3. this selects all packages defined by ```packages``` based on ```targets/generic``` and site-conf
2.4. adds the packages defined by ```device.packages``` of the TARGET-board
3. the packages are added directly to the board-specific packages in openwrt/.config
4. building the images with the OpenWrt toolchain
5. distribute these images

**Comment by NeoRaider** [comment]
This is roughly correct. There is one more step that happens between 3 and 4: after a `make defconfig` in OpenWrt `target_config_check.lua` verifies that all expected configuration options are actually enabled.

Package selections are a bit more complex; the whole current set of sources for the package list with their respective precedence can be found in #2007.
