### ISSUE TITLE
firewall: drops respondd requests from an extra_prefixes6

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#1959]
### Bug report

**What is the problem?**

Currently, the firewall only allows respondd requests from a link-local or prefix6 address as specified in the site.conf:

```
config rule 'mesh_respondd_ll'        
        option dest_port '1001'       
        option src 'mesh'             
        option name 'mesh_respondd_ll'
        option src_ip 'fe80::/64'     
        option target 'ACCEPT'        
        option proto 'udp'                    
                                              
config rule 'mesh_respondd_siteprefix'        
        option dest_port '1001'               
        option src 'mesh'                     
        option name 'mesh_respondd_siteprefix'
        option src_ip 'fdef:ffc0:3dd7::/64'
        option target 'ACCEPT'   
        option proto 'udp'
```

We have a hopglass server here which has an ULA in the prefix6 range (fdef:ffc0:3dd7::10) and a global IPv6 address in the extra_prefixes6 range (2001:67c:2d50::10). With the new site-scope multicast of ff05::2:1001 for respondd, the Linux kernel will need a routable source address and won't use a link-local source address anymore. So either the ULA or the global address mentioned before will be used. By default the Linux kernel will prefer the global address as it has a greater scope (2001:67c:2d50::10).

Unfortunately, "2001:67c:2d50::10 -> ff05::2:1001" will be filtered by the Gluon firewall though. So the hopglass-server will then get no responses.

**What is the expected behaviour?**

Gluon should allow respondd queries not only from the "prefix6" specified in the site.conf but also any prefix in the extra_prefixes6.

**Gluon Version:**
* Any version that allows the new, routeable multicast address ff05::2:1001, i.e. >= v2017.1. However using the routeable multicast address became mandatory with Gluon 2019.1, so these are affected in particular.

**

**Site Configuration:**

```
{
...

	prefix4 = '10.130.0.0/20',
	prefix6 = 'fdef:ffc0:3dd7::/64',
	extra_prefixes6 = { '2001:67c:2d50::/48' },
...
}
```

https://github.com/freifunk-luebeck/site-ffhl/blob/master/domains/default.conf

**Custom patches:**

none

**Workaround:**

On the hopglass-server add a multicast route to the "local" table with the desired "src":

```
$ ip -6 route add ff05::2:1001/128 dev $IFACE table local src fdeff
:ffc0:3dd7::10
```

This way the Linux kernel will be forced to use the ULA instead of the global one.

Ref.: https://github.com/hopglass/hopglass-server/issues/107

**Comment by mweinelt** [comment]
Can you please test https://github.com/freifunk-gluon/gluon/commit/19242248b8f70cb516a83b690d2bec94046d2565?

This should add the required firewall rules.
