### ISSUE TITLE
status-page: graph table is not responsive

### ISSUE THREAD

**Issue by tackin** [freifunk-gluon/gluon#1960]
Node is on gluon 2020.1.1
As shown in the picture, the headline to the graph is outside of the layout on my mobile device.
My guess, it is a minor formaterror in the status-page html.

![photo_2020-03-22_10-18-35](https://user-images.githubusercontent.com/15726279/77246405-2811c900-6c27-11ea-8eab-2848ba5ce34d.jpg)

[http://[2001:bf7:fc0f:2:b24e:26ff:fe6c:e166]/cgi-bin/status](http://[2001:bf7:fc0f:2:b24e:26ff:fe6c:e166]/cgi-bin/status)
upps! Github with url encode-error? .. :-)

**Comment by nalxnet** [comment]
The current data tables do not resize or restructure according to the responsive screen layout. The data tables need to react to such a small screen width. One approach could be to display each table row as it's own block/card, as with a such a small screen with there is barely enough space even for the table header.
