### ISSUE TITLE
Set 'option ifname' in /etc/config/wireless

### ISSUE THREAD

**Issue by thisco-de** [freifunk-gluon/gluon#197]
Setting the ifname statically for the wireless-interfaces of a node in the corresponding sections of /etc/config/wireless would not only help to make it easier to retrieve the actual assignment from the system, but will also avoid possible errors from gluon-components that rely on a fixed naming for the client- and the mesh-network. For instance, if one disables the mesh-network on a node, the dynamically generated interface-name "wlan0" will be assigned to the client-radio (which is "wlan0-1" in Barrier Breaker if both networks are enabled).

While it was possible in Attitude Adjustment to obtain the current assignment using "uci -P/var/state get wireless.<IFACE>.ifname"  even though the property was not set in the config file, it isn't anymore in Barrier Breaker (requires the ifname-option to be set explicitly now). There is however the possibility to obtain the assignment via "ubus call network.wireless status" in Barrier Breaker. Thus, having either statically defined names and/or common library-functions (shell, lua, etc.) in gluon, may help quite a lot and prevent possible errors.

**Comment by NeoRaider** [comment]
@tcatm: I'd like to either solve or reject this issue. I think for an administrator, having WLAN interfaces called something like `radio0-mesh` and `radio0-client` might be nice. What do you think?

**Comment by tcatm** [comment]
What about `mesh0` and `client0`? That's a lot easier for an admin to type on a high latency SSH session.

**Comment by NeoRaider** [comment]
That would be fine as well as long as all `wifi-device` sections in `/etc/config/wireless` are called radioX; if for some reason (like manual reconfiguration) a section with another name is encountered, the `ifname` option could just be kept unset. I'll add some code that sets the interface names like this.
