### ISSUE TITLE
uci set batman-adv.bat0.hop_penalty

### ISSUE THREAD

**Issue by 4ndr3** [freifunk-gluon/gluon#1985]
Bitte den Wert batman-adv.bat0.hop_penalty wieder zu uci hinzufuegen.

**Comment by NeoRaider** [comment]
Hmm, in the new UCI structure, we should put it somewhere in `/etc/config/gluon` (`/etc/config/batman-adv` does not exist anymore). I propose to use one of the following options:

- `gluon.mesh.hop_penalty`
- `gluon.mesh_batman_adv.hop_penalty`
- `gluon.mesh.batman_adv_hop_penalty`

**Comment by blocktrron** [comment]
@NeoRaider 

How about `gluon.batman_adv.hop_penalty`? Mesh seems redundant to me (at least in this context).

**Comment by mweinelt** [comment]
Duplicate of #1942.

**Comment by NeoRaider** [comment]
@blocktrron I think we should align the section names with package names, and the package is called gluon-mesh-batman-adv(-15).

**Comment by rotanid** [comment]
closing, as @mweinelt mentioned this is a duplicate if #1942 , please continue over there, thank you!
