### ISSUE TITLE
You are not reading the most recent version of this documentation.

### ISSUE THREAD

**Issue by rdiez** [freifunk-gluon/gluon#2035]
Clicking on this prominent link on the top-level  README.md file:

http://gluon.readthedocs.org/

opens the documentation as expected, but it shows the following warning:

You are not reading the most recent version of this documentation. v2020.1.2 is the latest version available.

Clicking on "v2020.1.2" switches to that version and makes the warning go away.

**Comment by blocktrron** [comment]
The default release was incorrectly set in readthedocs. I've fixed this.
