### ISSUE TITLE
Builds fail with iptables in GLUON_SITE_PACKAGES

### ISSUE THREAD

**Issue by belzebub40k** [freifunk-gluon/gluon#2046]
### Bug report

Since #2037 was merged I'm no longer able to build images with package `iptables`.

```
Configuration failed:
 * unable to enable package 'iptables'
```

Removing `iptables` from `GLUON_SITE_PACKAGES` works.

What is strange is that including `iwinfo` which is part of the same feed (_openwrt-19.07/package/network/utils_) works.

**What is the expected behaviour?**

Build images with package `iptables`.

**Gluon Version:**

latest master (v2020.1-190-g11a3b566)

**Site Configuration:**

https://github.com/freifunk-mwu/site-ffmwu

**Custom patches:**

None

**Comment by NeoRaider** [comment]
#2047 should fix this. Note that `iptables` is an OpenWrt core package that is included by default (which is what triggered this bug).

**Comment by belzebub40k** [comment]
I did a test build an it no longer fails.
