### ISSUE TITLE
factory support for TP-Link CPE210 3.20

### ISSUE THREAD

**Issue by adschm** [freifunk-gluon/gluon#2080]
I just pushed an update to the supported devices of the CPE210 v3 to OpenWrt master, as flashing via GUI was not possible on v3.20:

https://github.com/openwrt/openwrt/commit/4a2380a1e778a8f8e0bfb0a00f2996ed0aab58d8

This will be backported to 19.07 later this week, the backport is just a trivial cherry-pick.

Support had been requested in OpenWrt and Freifunk forums recently.

This issue is meant as a "notification" in case you want to implement this for Gluon beyond just doing a bump of the OpenWrt version at some point.

If you are not interested or will just take it with the next OpenWrt bump, just close this issue. I'm not using Gluon myself and will not pursue this any further.

**Comment by NeoRaider** [comment]
I think it makes sense to update our aliases accordingly.

Do I remember correctly that the CPE210/510 use the full revision number (including the 'v3.20') in `/tmp/sysinfo/model`?

**Comment by mweinelt** [comment]
They do.

```
root@64283-cccda-s:~# cat /tmp/sysinfo/model 
TP-Link CPE210 v1.0
```

**Comment by adschm** [comment]
Note that unless gluon changes /tmp/sysinfo/model locally, this will be gone with ath79, as there the DTS model will be taken.

**Comment by rotanid** [comment]
reopen as #2096 needs to be backported, i think @NeoRaider will take care of this

**Comment by rotanid** [comment]
backported via cherry-pick to v2020.1.x and v2020.2.x
