### ISSUE TITLE
after gluon-reconfigure ff-ip of node (via mesh-vpn, tunneldigger) not reachable

### ISSUE THREAD

**Issue by Adorfer** [freifunk-gluon/gluon#2083]
### scenario: 

- 2020.1.3-8-g3ef69c96+
- l2tp-tunndeldigger meshvpn
- public ipv6 and/or shell access to supernode

## to reproduce: 

- node in mesh-vpn mode, fully set up and operational. 
- node pingable from supernode via ipv6
- on cli enter "gluon-reconfigure"

## failure status: 

 - node not pingable from supernode via ipv6, no public (NOK) 
    - node pingable via batctl (OK)
    - ip access for clients (wifi-ap) works, even for new connected clients (OK)
    - ip addresses still on interfaces locally (OK)
    - ipv6 ping "via WAN" still working (OK)

## remedy:  (example)

- wan disconnect
- wait for l2tp-tunnel to collapase
- reconnect wan
- td goes through broker selection, comes online via supernode
- node becomes pingable again. 

## logs

https://paste.debian.net/1157466/

**Comment by NeoRaider** [comment]
This is expected, `gluon-reconfigure` will leave the node in an inconsistent state until services are restarted. It is recommended not to run it outside of config mode at all.
- In v2020.1.x and older, `gluon-reload` is severely broken, and a reboot *must* be done after `gluon-reconfigure`
- In v2020.2, a `gluon-reload` after `gluon-reconfigure` will restart all relevant services, but there is still a short time window where not all services are running with the same configuration (see also #2063)
- A real fix will be implemented with #2065, replacing `gluon-reconfigure` + reboot/`gluon-reload` with a way to do the reconfigure and reload in a single command that doesn't cause any inconsistent intermediate states
