### ISSUE TITLE
Ubiquiti NanoStation M2 should be in the tiny target

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#2117]
I think this (and some more) should be moved into the tiny target, since it has only 4 MB memory

**Comment by rotanid** [comment]
https://openwrt.org/toh/ubiquiti/nanostationm2
no, it has 8M

**Comment by blocktrron** [comment]
Even if, we are only referencing the target in which the device is upstream.

**Comment by rubo77** [comment]
But it has a big warning 

   DO NOT BUY DEVICES WITH 4MB FLASH / 32MB RAM

so the reason is, the only 32MB RAM

shouldn't we add those devices to the tiny target then as well? Or maybe create a new target for those with 32MB RAM?

**Comment by rotanid** [comment]
Gluon doesn't decide which device belongs to which target, as @blocktrron already wrote.

also, the warning meant always an AND not an OR

please raise the discussion at OpenWrt communication platforms if you want to change such things.

**Comment by SvenRoederer** [comment]
Recently I came up with this suggestion to the OpenWrt Devel List also: http://lists.openwrt.org/pipermail/openwrt-devel/2020-September/031422.html
