### ISSUE TITLE
Gluon v2020.1.x EOL Announcement

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#2138]
it's time to announce the end-of-life of the v2020.1.x branch.
per our Gluon Release life cycle, support ended in September:
 https://github.com/freifunk-gluon/gluon/wiki/Release-life-cycle

https://md.darmstadt.ccc.de/gluon-v2020.1.x-EOL

**Comment by NeoRaider** [comment]
Seems unnecessary to me. v2020.1.x is already past its EOL per https://github.com/freifunk-gluon/gluon/wiki/Release-life-cycle , and AFAIK there are no known regressions in v2020.2.x that could justify another v2020.1.x release.

**Comment by rotanid** [comment]
@NeoRaider so i updated the issue to what the majority of maintainers voted for on IRC.

**Comment by rotanid** [comment]
```
[ANNOUNCE] Gluon v2020.1.x End of life

The Gluon v2020.1.x branch has reached its end of life.
We have stopped maintaining it and will not create a release based on this branch anymore.

Updating to the v2020.2.x release series is the recommended course of action, which should be fairly easy. We are currently unaware of any regressions.

You can find documentation about the release life cycle of the Gluon branches on the GitHub Wiki:
https://github.com/freifunk-gluon/gluon/wiki/Release-life-cycle

```
