### ISSUE TITLE
unnecessary / old entries in "batctl tg" output 

### ISSUE THREAD

**Issue by Joachim-Wolff** [freifunk-gluon/gluon#216]
In the output of "batctl tg" I've seen many lines starting with the + sign. It looks they never time out. On my node with 15 day uptime I see over 250 of them, increasing, which is aprox 15% of all entrys. Also with 24h uptime I've seen over 50.

I've observed them after removing the Ethernet cable in a mesh-over-WAN setup, while the nodes see each other via WLAN too. Expect most of them occur after a router crash, like #109 

Currently running v2014.3-31-gc035ad0 / 0.6~exp20140809 but also see them on the current stable. They will be "announced" by both versions, too.

**Comment by NeoRaider** [comment]
We expect this to be fixed now.
