### ISSUE TITLE
question about gluon-core

### ISSUE THREAD

**Issue by dg0tm** [freifunk-gluon/gluon#2164]
Hi,

i wonder if 001-upgrade try to acces an non exist file. i think it could/should try to access /lib/gluon/gluon-version instant?

https://github.com/freifunk-gluon/gluon/blob/049625bb14c845c94ac88e9d022d8e0273344577/package/gluon-core/luasrc/lib/gluon/upgrade/001-upgrade#L7

because

https://github.com/freifunk-gluon/gluon/blob/049625bb14c845c94ac88e9d022d8e0273344577/package/gluon-core/luasrc/lib/gluon/upgrade/999-version#L10 

use it...

**Comment by blocktrron** [comment]
If I'm not mistaken, `/lib/gluon/version/core` was used ages ago to indicate the version prior upgrading (and is not used anymore).

`001-upgrade` therefore only sets the gluon_version non-nil, so initial steps are not executed again when upgrading. So the lack of `/lib/gluon/version/core` is perfectly fine.

**Comment by dg0tm** [comment]
Can you please rethink about it? Then without this file this script do nothing, because the first check is false and in these if clause mandatory. If the use case only set gluon_version non nil it could be also striped...

**Comment by dg0tm** [comment]
And if i fixed it, the following scripts change their behavior, because the initial check are now funktional...

e.g. 030-system

**Comment by blocktrron** [comment]
> Then without this file this script do nothing, because the first check is false and in these if clause mandatory.

This is expected, as "/lib/gluon/version/core" should only be available if you update from such an old gluon version. If you are not updating from such a version (which most likely won't work anymore anyway), this script is not necessary, as the prior Gluon version is already accessible using `gluon.sysconfig` and therefore the initial steps are skipped.

**Comment by dg0tm** [comment]
Okay, this script can be drop :)
Thank you for patience...
Am Montag, den 28.12.2020, 16:56 -0800 schrieb David Bauer:
