### ISSUE TITLE
Does Gluon need multiple routing tables?

### ISSUE THREAD

**Issue by CodeFetch** [freifunk-gluon/gluon#2181]
With working IPv6 source routing, a second IPv6 routing table might be unnecessary.

**Comment by NeoRaider** [comment]
The second routing table allows processes to use mesh or WAN as their default route depending on the packet mark. It is still necessary to get a different Source Address Selection for VPN etc.

**Comment by CodeFetch** [comment]
When explicitly specifying a source address for e.g. the VPN, it is unneeded I think, but I see the point...
