### ISSUE TITLE
Add TX power settings to expert mode (and maybe other WLAN-related settings)

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#219]

**Comment by CodeFetch** [comment]
I'd like to just edit the "Privates WLAN"-luci-package and rename it to "WLAN Einstellungen" or simply "WLAN". We should also add settings for region identification in beacons and distance. Is that okay?

**Comment by corny** [comment]
Sounds good to me.

**Comment by NeoRaider** [comment]
@CodeFetch, see also the comments in freifunk-gluon/packages#93

**Comment by CodeFetch** [comment]
Here's the pull request: https://github.com/freifunk-gluon/packages/pull/97
