### ISSUE TITLE
let "make all" call "make config" and "make update" automatically

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-gluon/gluon#2212]
Is there a specific reason why the make target "all" only depends on target "config"? Why not having "config" depending on "update"?
This way a simple "make all" call will be all that needs to be done for a correctly setup build.

**Comment by SvenRoederer** [comment]
For the Freifunk-Berlin firmware I can checkout, do my "site config", call make and take a coffee or so.

**Comment by blocktrron** [comment]
AFAIR the reason was that invoking `update` requires internet access while this is not necessarily the case when having cloned all modules and cached all downloads.

**Comment by SvenRoederer** [comment]
ok, seems a valid argument.

**Comment by NeoRaider** [comment]
`make update` doesn't require internet access when all referenced modules are up-to-date, but there lots of situations where an implicit `make update` is not desirable:
- `make update` takes some time, and it needs to be run only once and not for each target
- `make update` will revert modules to their original commits after manual checkouts, which is undesirable during development

**Comment by SvenRoederer** [comment]
But is this really working? I assume in most cases when the modules files changes the upstream repo has some changes to it's package version. This in turn will again trigger downloads at OpenWrt buildtime. So it might end up in a 50-50 chance that you don't need internet to build.
