### ISSUE TITLE
enable more secure SSH algorithms und ciphers for dropbear 

### ISSUE THREAD

**Issue by jbacksch** [freifunk-gluon/gluon#223]
Please enable more secure SSH algorithms und ciphers hmac-sha2-256 and hmac-sha2-512 for dropbear recommed by BetterCrypto p.19 <https://bettercrypto.org/static/applied-crypto-hardening.pdf>.

A patch is available for OpenWrt at <http://patchwork.openwrt.org/patch/6322/>.

**Comment by rotanid** [comment]
time has passed, but current gluon versions dropbear still doesn't support modern cryptography?
also, this doesn't affect only MAC, but also KeyExchange, curve25519 or sha256 aren't supported there, either...

**Comment by NeoRaider** [comment]
OpenWrt has enabled curve25519-sha256 by default since January, so I think we should backport that change now.

**Comment by NeoRaider** [comment]
curve25519-sha256 support is backported now.

**Comment by nomaster** [comment]
I have just tried to use my ssh-ed25519 key, but I was unable to log in. Is it supported?

**Comment by NeoRaider** [comment]
@nomaster: no, ed25519 is not supported at all by the current dropbear version 2016.74, I don't know if it is in development. Also, we use the default dropbear config from LEDE, which disables ECDSA using the NIST curves to save space.

curve25519-sha256 is supported as a key exchange method, but that's as far as ECC support goes at the moment.

**Comment by maurerle** [comment]
Dropbear supports ed25519 since 05.2020:
https://github.com/mkj/dropbear/pull/91

Release Notes:
https://github.com/mkj/dropbear/releases/tag/DROPBEAR_2020.79

OpenWRT Master (not released) is supporting it
https://github.com/openwrt/openwrt/blob/master/package/network/services/dropbear/Makefile

**Comment by mweinelt** [comment]
it is very unlikely that we will backport this. The OpenWrt team plans to do a new release soon and then we will benefit from those changes.
