### ISSUE TITLE
v2014.3.1 expert configuration error while activating mesh-on-WAN

### ISSUE THREAD

**Issue by Joachim-Wolff** [freifunk-gluon/gluon#224]
Got this error at initial configuration on v2014.3.1 after checking the box mesh-on-wan and save. 
But it works also...

https://gist.github.com/Joachim-Wolff/03e6b83e1a0ed82265ae

**Comment by NeoRaider** [comment]
We've released v2014.4, so let's close this v2014.3.1-specific issue.
