### ISSUE TITLE
Freifunk instable because Kabel Deutschland only serves ipv6 since two weeks

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#225]
If you use Kabel Deutschland and set a freifunk router to the Hitron Techn. router of Kabel Deutschland the internet access is **very unstable** since two weeks: sometimes webpages load fast as norrmal and sometimes the same pages get stuck loading. while on another computer in the same room at the same moment sometimes they load normal.

I called Kabel Deutschland and they said, since two weeks they changed something so they serve native Ipv6 to customers now. I told them to turn this switch off again at our account, to thin out the problem and noticed that now everything works smoothly again.

So it seems there is a big problem concerning Ipv6 and Kabel Deutschland with their new settings.

**Comment by fpletz** [comment]
Sounds like a MTU problem. What is the MTU for the fastd tunnels in your community?

**Comment by rubo77** [comment]
I already started a request ad KD, see: https://issues.freifunk.in-kiel.de/issues/25

**Comment by tcatm** [comment]
Gluon now has solid IPv6 support. If there are still problems, drop by on IRC or contact our mailinglist so we can sort out whether this is still a problem with Gluon.
