### ISSUE TITLE
Build for tl-wdr4900 fails

### ISSUE THREAD

**Issue by mmalte** [freifunk-gluon/gluon#228]
Building the ar71xx images works like a charm.

I've changed Makefile +23
GLUON_TARGET ?= mpc85xx-generic

Afterwards I got a lot of errors, even containing ar71xx:

make images V=s

make[1]: Entering directory /home/malte/freifunk/gluon/openwrt'
make -w -C /home/malte/freifunk/gluon/openwrt -f /home/malte/freifunk/gluon/Makefile GLUON_TOOLS=0 prepare-target
make[2]: Entering directory/home/malte/freifunk/gluon/openwrt'
mkdir -p /home/malte/freifunk/gluon/build/mpc85xx-generic/openwrt
for dir in build_dir dl staging_dir tmp; do \
mkdir -p /home/malte/freifunk/gluon/openwrt/$dir; \
done
for link in build_dir config Config.in dl include Makefile package rules.mk scripts staging_dir target tmp toolchain tools; do \
ln -sf /home/malte/freifunk/gluon/openwrt/$link /home/malte/freifunk/gluon/build/mpc85xx-generic/openwrt; \
done
make -w -C /home/malte/freifunk/gluon/openwrt -f /home/malte/freifunk/gluon/Makefile GLUON_TOOLS=0 feeds
make[3]: Entering directory /home/malte/freifunk/gluon/openwrt'
rm -rf /home/malte/freifunk/gluon/openwrt/package/feeds
mkdir /home/malte/freifunk/gluon/openwrt/package/feeds
[ ! -f /home/malte/freifunk/gluon/site/modules ] || . /home/malte/freifunk/gluon/site/modules && for feed in $GLUON_SITE_FEEDS; do ln -s ../../../packages/$feed /home/malte/freifunk/gluon/openwrt/package/feeds/$feed; done
. /home/malte/freifunk/gluon/modules && for feed in $GLUON_FEEDS; do ln -s ../../../packages/$feed /home/malte/freifunk/gluon/openwrt/package/feeds/$feed; done
make -w -C /home/malte/freifunk/gluon/openwrt -f /home/malte/freifunk/gluon/Makefile GLUON_TOOLS=0 prepare-tmpinfo
make[4]: Entering directory/home/malte/freifunk/gluon/openwrt'
mkdir -p tmp/info
export MAKEFLAGS= ;make V=ss -j1 -r -s -f include/scan.mk SCAN_TARGET="packageinfo" SCAN_DIR="package" SCAN_NAME="package" SCAN_DEPS="/home/malte/freifunk/gluon/openwrt/include/package*.mk /home/malte/freifunk/gluon/openwrt/overlay/*/*.mk" SCAN_EXTRA=""
export MAKEFLAGS= ;make V=ss -j1 -r -s -f include/scan.mk SCAN_TARGET="targetinfo" SCAN_DIR="target/linux" SCAN_NAME="target" SCAN_DEPS="profiles/*.mk /home/malte/freifunk/gluon/openwrt/include/kernel*.mk /home/malte/freifunk/gluon/openwrt/include/target.mk" SCAN_DEPTH=2 SCAN_EXTRA="" SCAN_MAKEOPTS="TARGET_BUILD=1"
for type in package target; do \
f=tmp/.${type}info; t=tmp/.config-${type}.in; \
[ "$t" -nt "$f" ] || ./scripts/metadata.pl ${type}_config "$f" > "$t" || { rm -f "$t"; echo "Failed to build $t"; false; break; }; \
done
./scripts/metadata.pl package_mk tmp/.packageinfo > tmp/.packagedeps || { rm -f tmp/.packagedeps; false; }
touch /home/malte/freifunk/gluon/openwrt/tmp/.build
make[4]: Leaving directory /home/malte/freifunk/gluon/openwrt'
make[3]: Leaving directory/home/malte/freifunk/gluon/openwrt'
make -w -C /home/malte/freifunk/gluon/openwrt -f /home/malte/freifunk/gluon/Makefile GLUON_TOOLS=0 gluon-tools
make[3]: Entering directory /home/malte/freifunk/gluon/openwrt'
make -w -C /home/malte/freifunk/gluon/openwrt -f /home/malte/freifunk/gluon/Makefile GLUON_TOOLS=0 tools/sed/install
make[4]: Entering directory/home/malte/freifunk/gluon/openwrt'
+ mkdir -p /home/malte/freifunk/gluon/openwrt/staging_dir/host
+ cd /home/malte/freifunk/gluon/openwrt/staging_dir/host
+ mkdir -p bin lib include stamp
mkdir -p /home/malte/freifunk/gluon/openwrt/build_dir/host/stamp /home/malte/freifunk/gluon/openwrt/staging_dir/host/include/sys
install -m0644 /home/malte/freifunk/gluon/openwrt/tools/include/*.h /home/malte/freifunk/gluon/openwrt/staging_dir/host/include/
install -m0644 /home/malte/freifunk/gluon/openwrt/tools/include/sys/*.h /home/malte/freifunk/gluon/openwrt/staging_dir/host/include/sys/
ln -sf lib /home/malte/freifunk/gluon/openwrt/staging_dir/host/lib64
touch /home/malte/freifunk/gluon/openwrt/staging_dir/host/.prepared
make[5]: Entering directory /home/malte/freifunk/gluon/openwrt/tools/sed'
. /home/malte/freifunk/gluon/openwrt/include/shell.sh; bzcat /home/malte/freifunk/gluon/openwrt/dl/sed-4.2.2.tar.bz2 | /home/malte/freifunk/gluon/build/ar71xx-generic/openwrt/staging_dir/host/bin/tar -C /home/malte/freifunk/gluon/openwrt/build_dir/host/sed-4.2.2/.. -xf -
bash: /home/malte/freifunk/gluon/build/ar71xx-generic/openwrt/staging_dir/host/bin/tar: No such file or directory
make[5]: *** [/home/malte/freifunk/gluon/openwrt/build_dir/host/sed-4.2.2/.prepared3ee93f2dfc5fa6933db0e8ab525eb189] Error 127
make[5]: Leaving directory/home/malte/freifunk/gluon/openwrt/tools/sed'
make[4]: *** [tools/sed/compile] Error 2
make[4]: Leaving directory /home/malte/freifunk/gluon/openwrt'
make[3]: *** [gluon-tools] Error 2
make[3]: Leaving directory/home/malte/freifunk/gluon/openwrt'
make[2]: *** [prepare-target] Error 2
make[2]: Leaving directory /home/malte/freifunk/gluon/openwrt'
make[1]: *** [/home/malte/freifunk/gluon/build/mpc85xx-generic/target-prepared] Error 2
make[1]: Leaving directory/home/malte/freifunk/gluon/openwrt'
make: *** [images] Fehler 2

**Comment by NeoRaider** [comment]
I've now found out what was triggering this issue. It is fixed in the git HEAD, but you must use a clean clone or at least delete `openwrt/tmp` for it to work.
