### ISSUE TITLE
optional backup uplink mode

### ISSUE THREAD

**Issue by JumpLink** [freifunk-gluon/gluon#230]
Gluon should have an optional backup uplink mode.
In this mode, the uplink would only be activated / used if no other node (which is meshing with our current note) has an activated uplink.
This would have the advantage that slow uplinks could only be used if no other (faster) uplink is in the near.

For example: I've two Internet connections, one over "Kabel Deutschland" with 100 Mbit/s and one over "T-Online" with 2Mbit/s. My Freifunk router's are using "Kabel Deutschland" for his uplink because it's much faster than "T-Online", but sometimes "Kabel Deutschland" has a fault and is not working anymore. In this situation it would be very useful, if my other Freifunk router (whose config is pre-configured for "T-Online") would activate his uplink as long as my Freifunk router (that is configured for "Kabel Deutschland") has no uplink.

I think this scenario is often, for example if your neighbor has an much slower connection as yours, normally your neighbor use the uplink of your faster uplink and his Freifunk router has an deactivated uplink, but what if the mash is interrupted? Then your neighbor would have no more uplink, with an backup uplink mode his Freifunk router could use his own uplink as long as the mash is interrupted.

I think this feature should not be so difficult to implement, in my imagination gluon would have a further checkbox in his config mode webinterface for this backup uplink mode, when this mode is activated, then a script runs every few minutes and test the own internet connection / uplink (In this case, it is not relevant from which node the uplink is), if no internet connection / uplink is found, the script activates the uplink in /etc/config/fastd. If the backup uplink is activated, the scripts checks the uplink status of his neighbor nodes, if one of the neighbors has an uplink (that comes not from his own), the script deactivates his own.

What necessary to clarify is, is how the node knows, that the uplink of the neighbor nodes are not comes from his own uplink. Could this information be stored in alfred?

I would also help to implement this feature, what do you think of my idea?

Cheers,
Pascal

**Comment by tcatm** [comment]
I think this is out of scope for Gluon. I'd suggest discussing such ideas with batman-adv developers directly.

**Comment by JumpLink** [comment]
Okay I've create an new [ticket for batman-adv](http://www.open-mesh.org/issues/205).
