### ISSUE TITLE
Node rebootet bei Broadcast-Ping

### ISSUE THREAD

**Issue by pberndro** [freifunk-gluon/gluon#231]
Wird in im Freifunk-Netz mit LanScan nach Geräten gesucht (Ipv4),
führt dies zu einem Absturz der Node mit Gluon 2014.3.1.

https://forum.freifunk-rheinland.net/t/node-rebootet-bei-broadcast-ping/729

**Comment by RubenKelevra** [comment]
Ansich sollte die ja nur überlaufen wenn genug gegenstellen im lokalen Netzwerk existieren, um das Limit zu überschreiten, sprich, ARP-Anfragen ins leere sollten ja nicht beantwortet und entsprechend nicht gespeichert werden.

Scans vom ganzen Netz sind grundsätzlich ein Problem, da sehr viel ARP-Broadcast erzeugt wird...

**Comment by RubenKelevra** [comment]
@simonszu kannst du mal versuchen, das Problem mit nmap nachzustellen, dann braucht man nicht dieses LanScan dafür, und kann vielleicht schaun ob es am ARP ansich oder am Port-Scan liegt.

**Comment by NeoRaider** [comment]
Has anyone tested this with a recent (CC-based) Gluon master?
