### ISSUE TITLE
netifd: mesh_lan (3240): Command failed: Permission denied

### ISSUE THREAD

**Issue by 2tata** [freifunk-gluon/gluon#2326]
### Bug report

**What is the problem?**

ringt after the update via autoupdater a message `"netifd: mesh_lan (3240): Command failed: Permission denied"` appears in logs. Not sure if its a real bug because the node works as expected, but still I found it noticable. I think this message is some where triggers by update script call.

device: Ubiquiti UniFi-AC-PRO, TP-Link TL-WR841N/ND v10

**Gluon Version:**
from gluon-v2020.2.3-4-g11861ed7 update to gluon-v2021.1.1-7-gb95cc175

**Site Configuration:**
https://git.ffnw.de/ffnw-firmware/siteconf/-/tree/202109

**Custom patches:**
https://git.ffnw.de/ffnw-firmware/siteconf/-/tree/202109/gluon_patches

**Comment by NeoRaider** [comment]
No reply from reporter, closing.
