### ISSUE TITLE
[gluon-v2021.1.1-6] respondd crash loop on devices with radios installed and all wifi disabled.

### ISSUE THREAD

**Issue by Adorfer** [freifunk-gluon/gluon#2327]
### Bug report

**What is the problem?**
gluon-respondd seems to crash on devices with radios installed, but all radios disabled, e.g. via uci settings

```
wireless.radio0.disabled='1'
wireless.radio1.disabled='1'
```

issue can be reliably reproduced

```
Sat Oct 16 21:46:19 2021 daemon.info procd: Instance gluon-respondd::instance1 s in a crash loop 6 crashes, 33 seconds since last crash

Sun Oct 17 13:06:47 2021 daemon.info procd: Instance gluon-respondd::instance1 s in a crash loop 6 crashes, 22 seconds since last crash

Sun Oct 17 14:03:19 2021 daemon.info procd: Instance gluon-respondd::instance1 s in a crash loop 9 crashes, 32 seconds since last crash
```

happens on different architectures (ath79, mt7621) 

even if manually restarted via "/etc/init.d/gluon-respondd start": terminates within seconds/minutes again

this occured on devices after migration from gluon 2020.2.x to gluon-v2021.1.1-6-g0625eb8c+
perhaps (speculative) linked to "no running hostapd process"

**What is the expected behaviour?**
respondd is constantly running and answering to hopglas requests

**Gluon Version:**
gluon-v2021.1.1-6-g0625eb8c+

**Site Configuration:**

site.conf/site.mk/modules: 
https://github.com/eulenfunk/firmware/tree/dd03276da8159f8cb8c88710ad8ac5dc860bb327/templates/13_dusfl

**Custom patches:**

respondd-patch "to listen to old hopglas-interfaces" still in place: 
https://github.com/eulenfunk/firmware/blob/dd03276da8159f8cb8c88710ad8ac5dc860bb327/patches/fix-respondd-rsk.patch

Images for test can be obtained from 
https://images.ffdus.de/stable/13_dusfl

(if this is a pure local issue due to extensive patching, hints appreciated how to debug locally)

**Comment by NeoRaider** [comment]
I can reproduce this issue with my own build of v2021.1.x, and it is definitely caused by the airtime module (when I delete it, the crashes stop). I'll look into this.
