### ISSUE TITLE
Add support for Nanostations Revision XW

### ISSUE THREAD

**Issue by powermik** [freifunk-gluon/gluon#236]
See http://wiki.openwrt.org/toh/ubiquiti/nanostationm5 for details

Nanostation M5 should be supported in openwrt 14.07 - for the loco version openwrt trunk is needed

**Comment by xfjx** [comment]
I just compiled the ubiquiti image for the loco XW and it works finde! Had to add one mirror to the download.pl for gmp-6.0.0a.
