### ISSUE TITLE
ramips-mt7621: migration of sysfs paths in /etc/config/wireless necessary

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#2391]
### Bug report

**What is the problem?**

On ramips targets (observed on D-Link DIR860L), the sysfs paths of the WLAN interfaces changed from OpenWrt 19.07 to 21.02:

Before:
```
pci0000:00/0000:00:00.0/0000:01:00.0
pci0000:00/0000:00:01.0/0000:02:00.0
```

After:
```
1e140000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0
1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0
```

`/etc/config/wireless` is currently not covered by #2372, so some config scripts fail after the upgrade.

Possible solutions:

- Regenerate `/etc/config/wireless` on reconfig
  - Requires to move more user intent to `/etc/config/gluon`
  - Might lead to unstable radio index assignments on some devices?
    - Regenerate only when the old config is obviously broken?
    - Ignore radio indices for intent configuration, instead use more generic "config for all 2.4GHz", "config for all 5GHz"?
- Target-specific migration script

**Comment by blocktrron** [comment]
Closed by #2560
