### ISSUE TITLE
Futro S400 kernel panic: invalid opcode

### ISSUE THREAD

**Issue by eliba** [freifunk-gluon/gluon#2397]
### Bug report

**What is the problem?**
A gluon boot does not complete on a Siemens Futro S400 with BIOS version `4.00.0P`.
When booting off the internal 8 GB CompactFlash card, the kernel stops booting at line
```
clocksource: Switched to clocksource tsc
```
When booting off a USB thumb drive (selected via Boot menu with `F12`) and additional kernel parameter `panic=0` (to stop gluon from instantly rebooting), this kernel panic happens:
```
traps: init[1] trap invalid opcode: ip:b7f39478 sp:bfbbd970 error: 0 in libc.so[b7f05000+4b000]
kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004
```

![IMG_20220218_132625](https://user-images.githubusercontent.com/12097093/154686269-87231c3d-ecad-4ae3-a66b-131c64dee3f0.jpg)

- What is not working as expected?
Initial booting after creating a bootable device
- What were you doing when you first noticed the problem?
System as described above. Using the "Generic x86 32-bit image from here: https://freifunk-firmware.de/images-release/stable/factory/gluon-ff3l-v2020.2.2%2B001-x86-generic.img.gz
- On which devices (vendor, model and revision) is it misbehaving?
Siemens Futro S400 Bios `rev. 4.00.0P`, AMD CPU with 1GHz, 1GB DDR-RAM with an additional add-on network card (2x RTL8110SB)
- Does the issue appear on multiple devices or targets?
Can't tell, since this is the only platform available to me at the moment. It does not make a difference whether the additional network card is plugged in or not.

**What is the expected behaviour?**
Gluon should boot successfully

**Gluon Version:**
[stable (v2020.2.2+001)](https://freifunk-firmware.de/images-release/stable/factory/gluon-ff3l-v2020.2.2%2B001-x86-generic.img.gz)

_Edit_:
Tried with current master and site config of FF3L ([from here](https://github.com/ff3l/site-ff3l)), resulting in this image name: `output/images/factory/gluon-ff3l-g65f5a3b0+sd462856~20220218-x86-generic.img.gz`, but still no luck:
```
traps: init[1] trap invalid opcode: ip:b7fc0d9c sp:bfc3dc80 error: 0 in libc.so[b7f8d000+4b000]
kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004
```
My wild guess is that maybe this CPU is not fully supported? Any help appreciated! :)

**Comment by NeoRaider** [comment]
The `x86-generic` image requires at least Pentium 4 or compatible. For the AMD NX the `x86-geode` image should be appropriate (and we also have an `x86-legacy` image for even less capable CPUs).

**Comment by eliba** [comment]
Thanks NeoRaider, I tried both image variants, and it seems to be an even less capable CPU. It works with the `x86-legacy` image, however only when booting off a USB thumb drive. When trying to boot off the CompactFlash card, it still hangs at the line:
```
clocksource: Switched to clocksource tsc
```
This is sufficent for now and I will continue to boot from USB, since the Futro offers it as a primary boot option.

Installing a Debian 11 onto the CompactFlash card works, so I suspect there's a driver missing in gluon.

**Comment by NeoRaider** [comment]
If you can find out which driver is missing (the Debian kernel log might contain a hint), I don't see an issue with including it in our x86 images by default.

**Comment by eliba** [comment]
This would be awesome!
I can't really tell the missing driver's name from the log alone, so here's the full `dmesg` output. The disk in question got recognized as `sda`. I also extracted `dmidecode` and `lspci` just in case, when I had Debian installed. Let me know if you need those as well.
[dmesg.txt](https://github.com/freifunk-gluon/gluon/files/8123268/dmesg.txt)

**Comment by NeoRaider** [comment]
The device uses the `pata_sis` driver. I've pushed a branch `hardware/pata_sis` based on the Gluon master that enables it. If you can't build an image yourself, I can also upload a test build.

**Comment by eliba** [comment]
I'll try next week and let you know immediately. Thank you already :)

**Comment by eliba** [comment]
Yessss it works perfectly!

**Comment by NeoRaider** [comment]
Thanks for testing. I've pushed the change to OpenWrt master and 21.02, so with the next module update the Gluon master will get it as well.
