### ISSUE TITLE
Possible enhancement: Implementation of CJDNS

### ISSUE THREAD

**Issue by pierrebeaucamp** [freifunk-gluon/gluon#240]
[CJDNS](https://github.com/cjdelisle/cjdns/) is a network protocol specifically designed for meshnets. It's used around the world in various meshnet communities (see [Hyperboria](http://hyperboria.net/), [Project Meshnet](http://projectmeshnet.org/) or the [Reddit Community](https://www.reddit.com/r/darknetplan/)). 

As Freifunk is a very well functioning and mature project, I understand that there is no need to look for an alternative to batman-adv. But the idea of a meshnet spreads globally and I think the various projects could benefit from each other by working together for the greater good. 

I just want to raise awareness of CJDNS, so the idea of a possible implementation (side-by-side with batman-adv or replacing batman-adv) could get around the freifunk and gluon communities.

Thank you.

**Comment by tcatm** [comment]
I'm closing this as it's unclear how this could proceed. If someone's interested to try it out using Gluon and documented his findings we might be able to judge whether it is worth implementing.
