### ISSUE TITLE
x86-64: Add target for UEFI boot compatible images

### ISSUE THREAD

**Issue by kpanic23** [freifunk-gluon/gluon#2403]
A lot of newer PCs don't have CSM any more and are unable to boot the regular x86 images.
Hence it would be great if the build scripts could create EFI-compatible images as well.

(see https://openwrt.org/docs/guide-developer/uefi-bootable-image)

**Comment by NeoRaider** [comment]
See #2404 - just switching to EFI-compatible images unconditionally seems preferable to teaching the autoupdater to distinguish the two image variants.
