### ISSUE TITLE
Add support for TP-Link TL-WR2543N/ND v1

### ISSUE THREAD

**Issue by kupschke** [freifunk-gluon/gluon#241]
It would be great if you can enable support for my TP-Link TL-WR2543ND:

http://wiki.openwrt.org/toh/tp-link/tl-wr2543nd

**Comment by NeoRaider** [comment]
I've added a profile for the TL-WR2543ND. It's untested so far, so Gluon must be compiled with BROKEN=1 to get it.

Regarding the WLAN, I've kept the OpenWrt default of always configuring it for the 2.4GHz band. Making the band configurable would be nice, but doesn't have high priority right now.

**Comment by kupschke** [comment]
I compiled Gluon and it is working for me.

Thank you :-)
