### ISSUE TITLE
Client-WLAN bei fehlendem mesh abschalten

### ISSUE THREAD

**Issue by 4ndr3** [freifunk-gluon/gluon#248]
Viele Knotenbetreiber_innen achten nicht auf den Zustand ihres Knotens, da sie ihn selbst nicht nutzen. Dies führt dazu, dass es viele Knoten gibt, die zwar laufen, aber nicht mit dem Netz per Funk oder VPN mesh Verbunden sind. Nichtsdestotrotz strahlen sie weiterhin das client-WLAN aus. Nutzer_innen versuchen sich dann erfolglos mit diesen Knoten zu verbinden -> Viel gehörtes Kommentar: "Freifunk, das funktioniert doch nicht".
Deshalb macht es Sinn das client-WLAN abzuschalten solange ein Knoten von Netz isoliert ist.

**Comment by FreifunkUFO** [comment]
zur Info: Freifunk Weimar macht das so hier: 
http://lists.berlin.freifunk.net/pipermail/berlin/2015-February/027084.html
bzw. https://github.com/bittorf/kalua/blob/master/openwrt-addons/etc/kalua/net#L1001

**Comment by elberfeld** [comment]
Grundsätzlich ist der Ansatz hier ein umbenanntes Client-WLAN zu erstellen gar nicht so unsinnig da man dann noch eine Möglichkeit hat auf den Knoten zuzugreifen auch wenn das Mesh gerade nicht funktioniert. 

Bei der Namennennung sollte aber auf jeden Fall darauf geachtet werden, dass der Name kein "Freifunk" enthält. 
Ein normaler Anwender wird sich auch zu einem Netzwerk "Freifunk-offline" verbinden und enttäuscht sein dass es nicht funktioniert. 
Ich würde hier eher "OFFLINE-Knotenname" vorschlagen.   

Noch konsequenter wäre hier bei Wegfall der Uplink oder Mesh Verbindungen den Freifunk Router als Client im Freifunk Netz zu aktivieren. 
Dann wäre auch ein Fallback für Änderungen die das Mesh zerstören vorhanden (z.B. Update der Batman Version).

**Comment by tcatm** [comment]
Due to the many unsolved problems associated with changing the ESSID we decided against any automated ESSID changes in Gluon.
