### ISSUE TITLE
TP-Link WDR4900 does not boot with OpenWrt 22.03

### ISSUE THREAD

**Issue by blocktrron** [freifunk-gluon/gluon#2491]
The TP-Link WDR4900 does not boot with a 22.03 based Gluon due to the the kernel exceeding the max bootable size.

@NeoRaider is working on a SPI loader to allow larger kernels to boot. This issue is for tracking said process after the merge of #2426

**Comment by rotanid** [comment]
here's neoraiders OpenWrt branch to test a fix:
https://git.openwrt.org/?p=openwrt/staging/neoraider.git;a=shortlog;h=refs/heads/mpc85xx-spi-loader

**Comment by rotanid** [comment]
@NeoRaider do you need help testing ?

**Comment by rotanid** [comment]
@NeoRaider ~180 devices (src: multi.meshviewer.org) would be happy to get to the next OpenWrt/Gluon release ;-)

**Comment by rotanid** [comment]
upstream issue for this problem:
https://github.com/openwrt/openwrt/issues/9027
@pmelange did test a 22.03.0-rebased version of the patches and reported it over there

**Comment by rotanid** [comment]
i'd like to reopen this until we have it in a stable branch

**Comment by AiyionPrime** [comment]
> i'd like to reopen this until we have it in a stable branch

I do not really mind, but does that imply we only close issues once/if they are backported?

**Comment by AiyionPrime** [comment]
> > > i'd like to reopen this until we have it in a stable branch
> > 
> > 
> > I do not really mind, but does that imply we only close issues once/if they are backported?
> 
> It's already backported in OpenWrt, just needs a bump + reenabling the device in Gluon.

That happened in #2675 earlier this afternoon.

I think I might need an introduction to what needs to become a backport, but that's for another time.

**Comment by pmelange** [comment]
5db6914f7cfddd1c3cb8a46017d4360e1ec26c5d is the upstream commit in 22.03.
2fa53c9214b7b93fd82ad1ff885145b9e1c1f71b is the upstream commit in master.

**Comment by rotanid** [comment]
> > i'd like to reopen this until we have it in a stable branch
> 
> I do not really mind, but does that imply we only close issues once/if they are backported?

if the issue also affects a supported stable branch, yes, i guess, as long as there was no decision to not backport.
