### ISSUE TITLE
Autoupdate Not working if branch is not in site

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#2519]
We accidentally offered a firmware in Freifunk Nord that had the Autoupdate branch defined to "2020.1.x" instead of "stable".

Since there's no firmware mirror defined for that, the au is not working.

It would have been helpful, if the au would fall back to stable if the branch is not defined

**Comment by rubo77** [comment]
To the user this problem is not visible in config Mode, since the select Box only shows "stable" because that is the first option.

There should be a warming there, that in uci there is set am invalid branch

**Comment by rubo77** [comment]
Will that commit also show a sensible display on misconfigured nodes in the admin panel?
E.g. show the configured branch somewhere instead of quietly just display the first entry in the selection?

**Comment by NeoRaider** [comment]
My PR will only prevent such a firmware from being built so far.

I don't think the UI needs a warning - instead we should make sure that node can't even get into the state where an invalid branch is set (unless someone manually edits the UCI config). One option would be to revert to the default branch on updates when an invalid branch is configured as an additional safeguard against misconfiguration, for the rare cases where
- the list of branches has actually changed or
- a firmware with broken default branch was manually updated.

**Comment by rubo77** [comment]
yes, that and the autoupdater should also check, if the configured branch is in the site.conf and if not, use the default branch to check for download.

ATM the autoupdater does not work at all if the branch is not in the list
