### ISSUE TITLE
Hängt nach firmware-Aktualisierung

### ISSUE THREAD

**Issue by 4ndr3** [freifunk-gluon/gluon#252]
Wir hatten einige Knoten die von pre-Gluon auf Gluon gingen, dass sie im safe mode hingen und durch firstboot zu reanimieren waren.
Jetzt, bei Hamburg 0.5 nach 0.5.2 (nur site.conf angepasst, Gluon v2014.3), hingen vereinzelt Knoten (4300, 841, 842), die sich einfach durch Trennen vom Strom, bzw. bei einem reboot im safe mode, reaktiviert werden konnten.
(Möglicher Weise verwandt mit https://github.com/freifunk-gluon/gluon/issues/185)

**Comment by tcatm** [comment]
Tritt das mit Gluon 2014.4 noch auf?

**Comment by NeoRaider** [comment]
Duplikat von #185.
