### ISSUE TITLE
Guide for fastd l2tp on gateways for v2022.1

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#2603]
There should be a note in the release notes on how to set up a reliable fastd l2tp setup.

What we are using is a bunch of shell scripts, that expect the bridge name to be passed as argv[1].

https://git.darmstadt.ccc.de/ffda/infra/salt/-/blob/master/fastd/files/fastd-default.conf.j2
https://git.darmstadt.ccc.de/ffda/infra/salt/-/tree/master/fastd/files/hooks

Unless anyone has anything else that works reliably I recommend we go with that.

**Comment by herbetom** [comment]
In my eyes one alternative could be systemd-networkd. Hoewer, i haven't tested the stability of such a setup with a large number of peers over a longer period of time.
And if there are minor issues fixing them within networkd wouldn't be easy. So scripts are probably for the better.

```ini
[Match]
Name=dom0-*

[Network]
Bridge=dom0-br
```
