### ISSUE TITLE
Missing kmod-ath10k on Netgear R7800

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#2619]
Problem introduced in https://github.com/freifunk-gluon/gluon/commit/15ef885836907b27b2c0481f7ea83d1dd504c5d5.

After install kmod-ath10k and modprobing `ath10k-core` and `ath10k-pci` the phys appear. Running `gluon-reconfigure` followed by a reboot of the device  makes it then work again normally.

**Comment by NeoRaider** [comment]
The image should contain `kmod-ath10k-ct`, not `kmod-ath10k`.

At least after `make GLUON_TARGET=ipq806x-generic config`, `openwrt/.config` contains `CONFIG_PACKAGE_kmod-ath10k-ct=y`. A full test build of *ipq806x-generic* is currently running on my machine.

**Comment by NeoRaider** [comment]
My build finished, and it contains `ath10k_core.ko` and `ath10k_pci.ko` from kmod-ath10k-ct.

@mweinelt Either you have a site-specific issue, or the device is not working correctly with the CT driver. Can you check which is the case?

**Comment by mweinelt** [comment]
The kmod is missing from our testing images since 2022-06-05. I'm not sure what causes it.

https://git.darmstadt.ccc.de/ffda/firmware/site
