### ISSUE TITLE
Add support for Ubiquiti's UniFi AP Outdoor+

### ISSUE THREAD

**Issue by thisco-de** [freifunk-gluon/gluon#272]
As the *UniFi AP Outdoor+* is the successor of of Ubiquiti's *UniFi AP Outdoor* (non-plus version) it becomes more and more important to support this device with gluon, as it is hard already to obtain the non-plus version from any reseller.

There exists a [patch](https://lists.openwrt.org/pipermail/openwrt-devel/2014-December/030281.html) by @NeoRaider based on [this patch](https://lists.openwrt.org/pipermail/openwrt-devel/2014-June/026087.html) (?) for the current OpenWRT development branch (*Chaos Calmer*) that has hardly been tested by now and is not yet integrated into Gluon.

**Comment by NeoRaider** [comment]
I'd like to get at least a little amount of feedback for the patch before integrating it into Gluon, especially because some people on openwrt-devel have seen WLAN issues.

**Comment by thisco-de** [comment]
I created an integration patch for Gluon today, but wasn't able to test it on an actual device, yet. Our community (Paderborn) will have two of these devices by next week, so feedback is on its way ...

**Comment by MPW1412** [comment]
Any updates on this?

**Comment by NeoRaider** [comment]
Sorry, no good news. I've added the Gluon support as BROKEN as the WLAN doesn't work correctly. The signal is strong, but there's extremly high packet loss. I'm not sure what needs to be done to fix this. It might be possible to analyze the stock firmware...

**Comment by MPW1412** [comment]
Thanks for the update. Can you do that? Do you need a testdevice? Or isn't that in your skill area?

**Comment by NeoRaider** [comment]
I have a test device here. I'll try to find out more about the issue when I have some spare time, but it may be beyond my abilities. I know a few things about the internals of ar71xx hardware, but WLAN hardware and drivers are very complex.

**Comment by oakey-dev** [comment]
Only so that it doesn't get forgotten.
I currently have to Bugs besides the WIFI Bugs from the openwrt-devel:
1. the MAC doesn't match the MAC from the Label
2. br-wan is bridged to the "secondary" Interface

**Comment by mmalte** [comment]
Is there an update on this device? I'll get some of these within the next few weeks.

**Comment by NeoRaider** [comment]
Unfortunately, the module to configure the HSR filter doesn't seem to work correctly, reception is still very bad.
