### ISSUE TITLE
cellular: authentication dropdown missing

### ISSUE THREAD

**Issue by AiyionPrime** [freifunk-gluon/gluon#2750]
> thxs 4 the nice work.
> for some provider, the auth feature is required to get a connection.
> could you be so kind and add an dropdown menu for the auth with:
> none, pap, chap or both
> txs!!!

_Originally posted by @heini66 in https://github.com/freifunk-gluon/gluon/issues/2631#issuecomment-1355086451_

**Comment by Djfe** [comment]
a setting for `roaming` might be useful as well

**Comment by T0biii** [comment]
> a setting for `roaming` might be useful as well

@Djfe should this be a separate issue? the #3307 only adds the auth dropdown

**Comment by Djfe** [comment]
I expected roaming to be a uci setting. It might be a setting on the sim card that needs to be executed with uqmi.
yes, a separate issue makes sense. but first I should test whether roaming currently works by default, if the sim was set to allow it. feel free to close this issue with your PR
