### ISSUE TITLE
What is the status of the XW images for ubiquiti loco and nano

### ISSUE THREAD

**Issue by xfjx** [freifunk-gluon/gluon#279]
Any news on the BROKEN status for the XW firmware version? I have a NanoStation Loco M5 and really looking forward to use it for a Freifunk node. Maybe I can help by sending the device to a developer or something?

Thanks in advance

**Comment by NeoRaider** [comment]
As I wrote in #236, it's marked BROKEN because it's untested. I expect it to work fine though, so please test it and give us feedback so we can remove the BROKEN flag.

**Comment by xfjx** [comment]
I just compiled the ubiquiti image for the loco XW and it works finde! Had to add one mirror to the download.pl for gmp-6.0.0a.
