### ISSUE TITLE
FritzBox 4020: randomly generated MAC on br-wan

### ISSUE THREAD

**Issue by grische** [freifunk-gluon/gluon#2808]
### Bug report

**What is the problem?**
As @tachtler discovered, the MAC address of `br-wan` is regenerate on every boot. This is following up from https://github.com/openwrt/openwrt/issues/11674.

With `fritz_tffs -i /dev/mtd5 -a | grep mac`:
```
maca=C8:0E:14:B5:BB:B7
macb=C8:0E:14:B5:BB:B8
macwlan=C8:0E:14:B5:BB:B9
macwlan2=C8:0E:14:B5:BB:BA
macdsl=C8:0E:14:B5:BB:B4
```

OpenWRT sets the macs correctly for at least `eth1` and `eth0.1`:
```
root@OpenWrt:~# uci show network | sort
network.@device[0].macaddr='C8:0E:14:B7:25:1F'
network.@device[0].name='eth1'
network.@device[0]=device
network.@device[1].name='br-lan'
network.@device[1].ports='eth0.1'
network.@device[1].type='bridge'
network.@device[1]=device
network.@device[2].macaddr='C8:0E:14:B7:25:1E'
network.@device[2].name='eth0.1'
network.@device[2]=device
...
```

while Gluon does set only the MAC for `br-client` to `macwlan`, but does not set `br-wan`:
```
root@ffmuc-c80e14b5bbb9:~# for device in /sys/class/net/*/address; do cat "$device" | tr -d $'\n' && echo "$device" | sed 's/.*\/\([^\/]*\)\/address/ \1/'; done
c8:0e:14:b5:bb:b9 bat0
c8:0e:14:b5:bb:b9 br-client
26:49:c5:3b:9a:e0 br-wan
4e:c6:35:db:24:28 client0
ce:e8:d9:2e:bb:69 dummy0
da:15:d1:9c:31:69 eth0.1
da:15:d1:9c:31:69 eth0
26:49:c5:3b:9a:e0 eth1
00:00:00:00:00:00 lo
...
```

and the respective bridge information:
```
root@ffmuc-c80e14b5bbb9:~# brctl show
bridge name     bridge id               STP enabled     interfaces
br-client               7fff.c80e14b5bbb9       no              bat0
                                                        client0
                                                        eth0.1
                                                        local-port
br-wan          7fff.2649c53b9ae0       no              eth1
```

**What is the expected behaviour?**
Having a stable MAC address for `br-wan`

**Gluon Version:**
2022.1.1 and 2022.1.2

**Custom patches:**
[patches](https://github.com/freifunkMUC/site-ffm/tree/stable/patches)

**Comment by Djfe** [comment]
About my comment on openwrt: I learned by now how OpenWRT and Gluon handle Mac addresses differently and that there are differences between the interfaces and how they are supplied with Mac addresses.
(I learned this with the Cudy X6 PR and via helpful conversations on IRC)
You were completely right, that my comment only applied for Gluon.
