### ISSUE TITLE
depdot.sh can't handle multiline DEPENDS entries

### ISSUE THREAD

**Issue by AiyionPrime** [freifunk-gluon/gluon#2814]
### Bug report

**What is the problem?**
./contrib/depbot.sh`

- How is it misbehaving?

currently it generates this on line 244:

```dot
__ [label="\", shape=box];
```

This escapes the second `"` and breaks the format afterwords.

**What is the expected behaviour?**

Escaping the second occurence of `$1` in `print_node()`:
https://github.com/freifunk-gluon/gluon/blob/fe79b504733c3497863529a24e4eba5d95264960/contrib/depdot.sh#L20

should to the trick.

```dot
__ [label="\\", shape=box];
```

**Gluon Version:**

v2023.1.3 as well as master are affected

**Site Configuration:**

no site necessary to reproduce

**Custom patches:**

none

**Comment by neocturne** [comment]
The issue is actually that depdot uses grep to parse Makefiles and thus can't handle multiline assignments at all. The `\` that appears in the output is the line continuation in the Makefile...
