### ISSUE TITLE
gluon-web-cellular: DNS servers added to wrong resolv.conf file

### ISSUE THREAD

**Issue by nrbffs** [freifunk-gluon/gluon#2849]
### Bug report

**What is the problem?**

DNS servers from the cellular interface are added to a wrong resolv.conf file, rendering DNS unusable until a connection to the mesh exists.

After booting the node and a VPN connection has been established, `/tmp/resolv.conf.d/resolv.conf.auto` looks like this
```
# cat /tmp/resolv.conf.d/resolv.conf.auto 
# Interface cellular_4
nameserver 139.7.30.125
nameserver 139.7.30.126
# Interface client
nameserver fd21:b4dc:4b08::a38:903
nameserver fd21:b4dc:4b08::a38:403
nameserver fd21:b4dc:4b08::a38:502
nameserver fd21:b4dc:4b08::a38:103
nameserver fd21:b4dc:4b08::a38:405
nameserver fd21:b4dc:4b08::a38:503
```
Where `fd21:b4dc...` are DNS servers from the mesh and `139.x` are DNS servers from my cellular provider.

**What is the expected behaviour?**

DNS servers from the cellular interface added to `/tmp/gluon/wan-dnsmasq/resolv.conf`. DNS servers from cellular should **not** be in `/tmp/resolv.conf.d/resolv.conf.auto`.

**Gluon Version:** 9a4395d048ccc3e911a99c243bf0bc87024e1aeb

**Site Configuration:** https://gitlab.freifunk-stuttgart.de/firmware/site-ffs/-/tree/6429e1491dde9a9482d0b067f4b1d2993beacfc4

**Custom patches:**

* https://gitlab.freifunk-stuttgart.de/firmware/gluon/-/commit/beab5a498fc230922290098264102acf6e19d9bf
* https://gitlab.freifunk-stuttgart.de/firmware/gluon/-/commit/b6da00d79dbf508e9b470124e735c71f35480104
* https://gitlab.freifunk-stuttgart.de/firmware/gluon/-/commit/d6cf79c6c5589529e1e289de709c14a2d5fcf99b
* https://gitlab.freifunk-stuttgart.de/firmware/gluon/-/commit/61695dc20d45e9f3bdf93fae4d90b2cb64390ef5

**Comment by Djfe** [comment]
I can confirm this:
```
uqmi -d /dev/cdc-wdm0 --get-current-settings
{
        "pdp-type": "ipv4-or-ipv6",
        "ip-family": "ipv4",
        "mtu": 1500,
        "ipv4": {
                "ip": "10.37.104.16",
                "dns1": "62.109.121.17",
                "dns2": "62.109.121.18",
                "gateway": "10.37.104.17",
                "subnet": "255.255.255.224"
        },
        "ipv6": {

        },
        "domain-names": {

        }
}
cat /tmp/gluon/wan-dnsmasq/resolv.conf
cat /tmp/resolv.conf.d/resolv.conf.auto
# Interface cellular_4
nameserver 62.109.121.17
nameserver 62.109.121.18
# Interface client
nameserver 2a03:2260:3006::53
search ffac
```
