### ISSUE TITLE
Tainted Kernel after "page allocation failure"

### ISSUE THREAD

**Issue by Joachim-Wolff** [freifunk-gluon/gluon#291]
I've observed a tainted kernel, first occured at 0.6~exp200141205, on my Nanostation Loco M2. Now again under 2014.4 , but don't look to affect the router funktional... Currently I only observerd it at NS Loco HW only, never (til now) at my other box with TP-Link TL-WR841N/ND v8 HW...

"[1080045.460000] CPU: 0 PID: 1036 Comm: alfred Tainted: G        W    3.10.49 #1"

**Comment by NeoRaider** [comment]
That's normal, as the page allocation failure happens in kernel space.

**Comment by NeoRaider** [comment]
Duplicate of #109
