### ISSUE TITLE
Bandwidth Downstream Limit (limit_ingress) not working properly

### ISSUE THREAD

**Issue by maurerle** [freifunk-gluon/gluon#3017]
### Bug report

This is generally known since a few month but noone created an issue yet.
When the issue was initially raised on IRC/matrix @neocturne said:
> Download limit has always been a bit wonky, as this is only enforced locally on the node by delaying or dropping packets that exceed the limit, so in theory the server can still send packets faster than should be possible (they just won't reach the client then if excess packets fill up the configured queue size). For protocols with some kind of congestion control (like TCP) this...

**What is the problem?**
Using:
```
uci set gluon.mesh_vpn.limit_egress=800    # upload 0.8 Mbit/s
uci set gluon.mesh_vpn.limit_ingress=5000  # download 5.0 Mbit/s
uci set gluon.mesh_vpn.limit_enabled=1
uci commit gluon
gluon-reconfigure
/etc/init.d/network restart
```

Limiting upload works as expected, but there is only small impact on download (30 instead of the full 40mbit/s).
Tested this with iperf3, librespeed, openspeedtest.
If I set limit_ingress to 500 - I still get 30mbit/s with iperf3 and 20mbit/s with openspeedtest.

**What is the expected behaviour?**

Download should be limited to 5MBit/s too

**Gluon Version:**

v2023.1.1 and master

**Site Configuration:**

https://github.com/ffac/site but also reported by ffmuc and eventually other communities

**Comment by neocturne** [comment]
Thanks, will be fixed by https://github.com/freifunk-gluon/packages/pull/267
