### ISSUE TITLE
readthedocs latest version information outdated

### ISSUE THREAD

**Issue by maurerle** [freifunk-gluon/gluon#3028]
### Bug report

**What is the problem?**

Readthedocs does not know what the latest release is..
It says 2022.1.4 would be the latest one, despite it already having newer releases available too.

**EDIT: the tags are not available, so this is the actual problem, that the pipeline did not run for the v2023.1 and v2023.1.1 tag?**

https://gluon.readthedocs.io/en/v2021.1.x/user/getting_started.html

![image](https://github.com/freifunk-gluon/gluon/assets/25026204/bb591e08-b569-47ba-8266-7b0531c0ae0c)

I don't know where this is set, but the versions also do not appear here at least:
https://readthedocs.org/projects/gluon/versions/

**What is the expected behaviour?**

**Gluon Version:**

**Site Configuration:**

**Custom patches:**

**Comment by blocktrron** [comment]
Versions have been enabled in rtd.
