### ISSUE TITLE
DWL-2100AP / DN-7018  REV A

### ISSUE THREAD

**Issue by MPW1412** [freifunk-gluon/gluon#308]
Hello,

at a dorm hier we found 13x DWL-2100AP / DN-7018 REV A1.31 routers. There seems to be OpenWRT-Support: http://wiki.openwrt.org/toh/d-link/dwl-2100ap

And they have an Atheros AR2112A Wifi chip.

Can we get support for gluon? 

Greetings
MPW

**Comment by tcatm** [comment]
Nope. 16 MB RAM is not sufficient for running recent versions of OpenWRT. They can't do 11n either.

**Comment by MPW1412** [comment]
A true, I thought 16 is the treshhold, but it's 32 actually.
