### ISSUE TITLE
bcm27xx: RaspberryPi libplatforminfo image name configuration broken

### ISSUE THREAD

**Issue by blocktrron** [freifunk-gluon/gluon#3099]
The workaround in libplatforminfo for RaspberryPi targets is currently broken due to changed target naming in OpenWrt.

It also lacks the new targets for RaspberryPi 3 and 4.

See https://github.com/freifunk-gluon/packages/tree/master/libs/libplatforminfo/src/targets

**Comment by neocturne** [comment]
PR is up in https://github.com/freifunk-gluon/packages/pull/270

I renamed the issue as I don't consider this a workaround.

**Comment by blocktrron** [comment]
Agreed, I was just typing this in a hurry after the meeting.
