### ISSUE TITLE
Floods of ARP replies for 0.0.0.0

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#311]
It looks like the ARP peaks in here (capture from Freifunk Hamburg):

http://metameute.de/~tux/Freifunk/ARP.kbits-1d-2015-03-15.png

are generated by some stupid devices issuing ARP requests for 0.0.0.0 about every five seconds. Even more stupid and many devices are actually responding that they'd have 0.0.0.0.

Suggestion: Add filters for ARP requests and replies for 0.0.0.0.

**Comment by NeoRaider** [comment]
Filtering the requests would be enough, wouldn't it?
