### ISSUE TITLE
ipq40xx: sysupgrade for Plasma Cloud PA2200 from v2023.1.x to master is rejected

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#3120]
When trying to sysupgrade a Plasma Cloud PA2200 node from the following Gluon version:

```
root@tux-pa2200-test:/tmp# cat /lib/gluon/gluon-version 
v2023.1.1-18-g701857e
```

To Gluon master

```
$ git describe
v2023.1-210-g3ab7149f472c
```

Then this fails with the following error message:

```
root@tux-pa2200-test:/tmp# sysupgrade ./gluon-ffhl-0.17.1\~exp20231222-plasma-cloud-pa2200-sysupgrade.bin 
Fri Dec 22 20:43:09 CET 2023 upgrade: The device is supported, but the config is incompatible to the new image (1.0->1.1). Please upgrade without keeping config (sysupgrade -n).
Fri Dec 22 20:43:09 CET 2023 upgrade: Config cannot be migrated from swconfig to DSA
Image check failed.
```

**Comment by blocktrron** [comment]
The autoupdater has this case covered:

https://github.com/freifunk-gluon/packages/commit/b80428166454d184f356e5a14a144911d9ee11aa

For calling `sysupgrade` on the CLI, you have to add this parameter manually. The upgrade view in setup mode should also work.
