### ISSUE TITLE
Support for TP-Link TL-WR741ND-V5

### ISSUE THREAD

**Issue by JoniArida** [freifunk-gluon/gluon#321]
Please Support the newest Generation of TP-Link WR741N/ND routers (V5) since TP-Link just produce the newest generation of this device.
Specification: http://wiki.openwrt.org/toh/tp-link/tl-wr741nd

**Comment by NeoRaider** [comment]
Unfortunately, there is no OpenWrt support for this device so far. We'd at least need a test device to implement support.

**Comment by JoniArida** [comment]
If you want I can sent you one. Just E-Mail me your address. (joni[dot]arida[@]posteo[dot]de)

**Comment by NeoRaider** [comment]
Support has been added, I'll mail back the test device next week :)
