### ISSUE TITLE
python3-distutils support ends that is a requirement for gluon Build (since Python 3.12)

### ISSUE THREAD

**Issue by ChristianMiddendorf** [freifunk-gluon/gluon#3266]
After a system update to Ubuntu 24.04LTS with Python 3.12, building Gluon no longer works because python3-distutils is no longer supported. 

Python refers to using setuptools in the future https://peps.python.org/pep-0632/ .

**Comment by 2tata** [comment]
it is `python3-distutils-extra`

**Comment by ChristianMiddendorf** [comment]
Thank you! 
…After installing python3-distutils-extra via apt install a make dirclean has to run and everything is fine :)
