### ISSUE TITLE
empty error message when choosing wrong hostname

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#333]
If I choose a hostname with special characters öäü in it and press the commit button, the page reloads and shows an empty error message (with just a list-dot and no text).

**Comment by NeoRaider** [comment]
Ah, I might have broken that when I cleaned up the templates for the i18n support. I'll look at it.

**Comment by rubo77** [comment]
![on-off-fehler](https://cloud.githubusercontent.com/assets/1591563/7078012/be886b22-df15-11e4-81a5-ec07fd82bae5.png)

**Comment by NeoRaider** [comment]
Ah, it's the other way around: It was broken before, I fixed it (unknowingly) when I added the i18n support. So this bug had already been fixed when you reported it.

Please always mention the Gluon version you are using in your bug reports.
