### ISSUE TITLE
neighbour log over time

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#334]
Especially for moving mobile nodes, but also for nodes with neighbours with differing connection strength, it would be of most interest to which nodes they connect over time.

My first solution idea:  
We would need a log of all neighbours seen over time, preferingy only local in RAM, that is sent through the mesh once the node has connection to a definable target address that will collect the connection information.

**Comment by ohrensessel** [comment]
mh you could log the information available in the nodes.json file generated by the ffmap-backend to see the mesh partners of a node over time.

**Comment by rubo77** [comment]
But this would be interesting on the status page of a node too, so a history of seen nodes would fit in there

**Comment by mweinelt** [comment]
Is what the current status page provides sufficient? 

Fwiw, I don't think it's feasible to keep any history on the router.

**Comment by rubo77** [comment]
the history should not be written on the router, but nodes that are there and gone again, should be visible until reboot. At the moment nodes are only visible for a certain time on the right (how long?)

**Comment by mweinelt** [comment]
In your opinion, where should this information be kept if not one the router?

**Comment by rubo77** [comment]
The history could be kept in a temporary file

**Comment by rubo77** [comment]
Sie, in memory, but that would be only a few bytes. And we don't want to cause write cycles

**Comment by mweinelt** [comment]
That would require a cronjob/daemon to collect the information regularly, and I'm telling you I don't like the sound of it, because I think the gain is very minimal.

**Comment by rotanid** [comment]
ack and therefore rejected
