### ISSUE TITLE
Ubiquity Rocket M

### ISSUE THREAD

**Issue by citronalco** [freifunk-gluon/gluon#341]
Bitte Ubiquity Rocket M in die Liste der unterstützten Geräte mit aufnehmen.
Läuft hervorragend mit dem Bullet M-Image.

Wie bei der Bullet M wird auch bei der Rocket der eingebaute Verstärker ignoriert, standardmäßig wird mit 20dbm+10dbm (Verstärker)=30dbm gesendet während iwinfo nur die 20dbm anzeigt. Also voll kompatibel zur Bullet M :)

**Comment by NeoRaider** [comment]
Done.
