### ISSUE TITLE
Add instant/temporary file sharing to status page

### ISSUE THREAD

**Issue by peki75** [freifunk-gluon/gluon#343]
Add file sharing capabilities directly to the status page of a Gluon node (this way personal file sharing works even for nodes isolated from the mesh).

Newer HTML5 features (not supported by all browsers yet) should allow these browser to browser file sharing functions, e.g WebRTC's RTCDataChannel API: http://www.html5rocks.com/en/tutorials/webrtc/datachannels/

Another example is noatta.ch which stores the file, creates a shortcut and the receiver is able to download the file from that custom URL before it gets deleted. But this is only working with special routers like 1043v2 which allows to add USB storage as devices are fairly limited.

noattach: https://github.com/astro/noattach

**Comment by tcatm** [comment]
While this sounds usefil it is out of scope for Gluon.
