### ISSUE TITLE
Add license information/README to output build directories

### ISSUE THREAD

**Issue by tyll** [freifunk-gluon/gluon#357]
It would be nice if the gluon build scripts also create a license file/readme about where to get the source next to the built firmware files, for example
http://images.freifunk-aachen.de/stable/factory/
does not contain any of these files. From my understanding of the GPL and the license of OpenWRT which is used by Gluon, this might even be a requirement.

**Comment by NeoRaider** [comment]
The person who provides the downloads must handle this herself, for example by adding a note to the community download page. This is handled like that on the official OpenWrt download servers.
