### ISSUE TITLE
Sysupgrade will fail at WDR4900

### ISSUE THREAD

**Issue by christian1980nrw** [freifunk-gluon/gluon#359]
sysupgrade gluon-moehne-0.6.2-stable20150430-t
-link-tl-wdr4900-v1-sysupgrade.bin
Invalid image type.
Image check 'platform_check_image' failed.

Its only possible with command -F (force).

**Comment by NeoRaider** [comment]
Looks like a typo in the image name. A bit confusing, but `sysupgrade` will give you the same "Invalid image type" error message when the image file doesn't exist...

**Comment by christian1980nrw** [comment]
it was my mistake... found the prob. closed.
