### ISSUE TITLE
documentation for option mesh on lan and mesh on wan

### ISSUE THREAD

**Issue by eriu** [freifunk-gluon/gluon#376]
mit gluon 2015.1 kann man u.A. einzeln mesh on lan oder mesh on lan aktivieren. Leider ist das weder im Luci Interface noch in der Gluon-Readme ausreichend dokumentiert was welche Option bewirkt.

**Comment by MichaelSasser** [comment]
Hmm... ich gehe mal davon aus, dass du Mesh-on-Lan, Mesh-on-Wan und Mesh-on-VPN (Mesh VPN) meinst.

Mesh-on-Lan wurde [hier](http://gluon.readthedocs.org/en/v2015.1.1/releases/v2015.1.html?highlight=lan#mesh-on-lan) dokumentiert mit allen Infos darüber, Mesh-on-Wan ist [hier](http://gluon.readthedocs.org/en/v2015.1.1/features/mesh-on-wan.html?highlight=mesh%20wan#mesh-on-wan) etwas dürftig dokumentiert und Mesh VPN [hier](http://gluon.readthedocs.org/en/v2015.1.1/dev/wan.html?highlight=vpn#wan-support) mit wenig Infos, ist jedoch hervorragend config-mode beschrieben.
