### ISSUE TITLE
Request: Default installation of siproxd to fix sip over mesh

### ISSUE THREAD

**Issue by christian1980nrw** [freifunk-gluon/gluon#382]
I was not able to receive incoming voip calls (Client is an older IPv4 Fritz Box) over the mesh network until i installed siproxd on my gluon router. Siproxd is working transparent.

For example the wdr4900 needs this package:
https://downloads.openwrt.org/barrier_breaker/14.07/mpc85xx/generic/packages/telephony/siproxd_0.8.1-4_mpc85xx.ipk

I am still testing, but i think incoming calls are working now with this config:
/etc/config/siproxd

config siproxd general
	option if_inbound		br-client
	option if_outbound		bat0

Could siproxd be integrated into gluon by default?

**Comment by tcatm** [comment]
Gluon comes with no pakages integrated by default. It's all up to the community's site.mk where packages can be selected.

Can you explain what your setup does and how it fixes the problem? What is the problem? In most Gluon networks it should just work and I've been using SIP successfully over the mesh a few times.

**Comment by christian1980nrw** [comment]
I think it is a similar problem like this:
http://www.sipgateblog.de/sipgate-am-ipv6-kabelanschluss/
For example sipgate recommends to use tcp keepalives (last block of the text).
And Siproxd is uing keepalives (20 secs) by default. My old Fritz Box cannot do this.

**Comment by tcatm** [comment]
That's not the only possible solution. If your Fritz Box can't do that, you should update it's firmware. siproxd may also be deployed at your community's internet gateway.

**Comment by christian1980nrw** [comment]
I still think it has to be integrated to fix it. There is no disadvantage.
Mobile sip user dont like to set up keepalives for freifunk to stay reachable, especially if they dont know that there is a problem.

**Comment by tcatm** [comment]
Please evaluate whether this can be solved by installing siproxd on the gateways instead.
