### ISSUE TITLE
accept only valid RFC 1123 hostname

### ISSUE THREAD

**Issue by davidak** [freifunk-gluon/gluon#389]
i set a hostname with underscores `_` in gluon, but netmon says:

```
Der Hostname ist ungültig. Erlaubt sind Hostnames nach RFC 1123.
```
so i had to change it again, what can be avoided.

**Comment by NeoRaider** [comment]
Yes, the hostname check in the config mode has some major flaws...

Our plan for the next Gluon release is changing the field to a "pretty hostname" and allowing any unicode string there. The "real" hostname would be derived from the pretty hostname in a way similar to what many desktop OSs do; the real hostname would follow RFC1123 then, of course.

**Comment by NeoRaider** [comment]
This is now tracked in #414.
