### ISSUE TITLE
using gluon and gluon-packages in openwrt buildroot

### ISSUE THREAD

**Issue by imp1sh** [freifunk-gluon/gluon#395]
Hi,

I've been trying to integrate gluon and gluon-packages in openwrt buildroot (trunk).
There are a couple of errors that hold me back from being successful.

This is what I added to feeds.conf:
src-git gluon https://github.com/freifunk-gluon/gluon.git
src-git gluonpackages https://github.com/freifunk-gluon/packages.git

When I run ./scripts/feeds update -a there are some errors which always lead into the same direction:
ERROR: please fix feeds/gluon/package/gluon-authorized-keys/Makefile - see logs/feeds/gluon/package/gluon-authorized-keys/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-autoupdater/Makefile - see logs/feeds/gluon/package/gluon-autoupdater/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-config-mode-autoupdater/Makefile - see logs/feeds/gluon/package/gluon-config-mode-autoupdater/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-config-mode-contact-info/Makefile - see logs/feeds/gluon/package/gluon-config-mode-contact-info/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-config-mode-core/Makefile - see logs/feeds/gluon/package/gluon-config-mode-core/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-config-mode-geo-location/Makefile - see logs/feeds/gluon/package/gluon-config-mode-geo-location/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-config-mode-hostname/Makefile - see logs/feeds/gluon/package/gluon-config-mode-hostname/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-config-mode-mesh-vpn/Makefile - see logs/feeds/gluon/package/gluon-config-mode-mesh-vpn/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-core/Makefile - see logs/feeds/gluon/package/gluon-core/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-legacy/Makefile - see logs/feeds/gluon/package/gluon-legacy/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-admin/Makefile - see logs/feeds/gluon/package/gluon-luci-admin/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-autoupdater/Makefile - see logs/feeds/gluon/package/gluon-luci-autoupdater/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-mesh-vpn-fastd/Makefile - see logs/feeds/gluon/package/gluon-luci-mesh-vpn-fastd/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-node-role/Makefile - see logs/feeds/gluon/package/gluon-luci-node-role/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-portconfig/Makefile - see logs/feeds/gluon/package/gluon-luci-portconfig/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-private-wifi/Makefile - see logs/feeds/gluon/package/gluon-luci-private-wifi/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-luci-wifi-config/Makefile - see logs/feeds/gluon/package/gluon-luci-wifi-config/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-mesh-batman-adv-14/Makefile - see logs/feeds/gluon/package/gluon-mesh-batman-adv-14/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-mesh-batman-adv-15/Makefile - see logs/feeds/gluon/package/gluon-mesh-batman-adv-15/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-mesh-batman-adv-core/Makefile - see logs/feeds/gluon/package/gluon-mesh-batman-adv-core/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-mesh-vpn-fastd/Makefile - see logs/feeds/gluon/package/gluon-mesh-vpn-fastd/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-next-node/Makefile - see logs/feeds/gluon/package/gluon-next-node/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-node-info/Makefile - see logs/feeds/gluon/package/gluon-node-info/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-setup-mode/Makefile - see logs/feeds/gluon/package/gluon-setup-mode/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-simple-tc/Makefile - see logs/feeds/gluon/package/gluon-simple-tc/dump.txt for details
ERROR: please fix feeds/gluon/package/gluon-site/Makefile - see logs/feeds/gluon/package/gluon-site/dump.txt for details

All of them are saying this:
Makefile:8: /include/package.mk: No such file or directory
make[1]: *** No rule to make target '/include/package.mk'.  Stop.

Somehow this seams to be the line causing this error within the Makefile:
include $(GLUONDIR)/include/package.mk

Packages usint $(INCLUDEDIR) instead of $(GLUONDIR) don't throw this errors.
Obviously $(GLUONDIR) doesn't seem to be known.

Can this be fixed easily? I'm lacking a bit of understanding how this works in gluon and why it doesn't in buildroot.

**Comment by tcatm** [comment]
While [gluon/packages](1) is supposed to work with vanilla OpenWrt all packages in gluon itself require the Gluon build framework.

Discussion about this is better suited for the mailinglist. This isn't really an issue with Gluon.

[1]: https://github.com/freifunk-gluon/packages
