### ISSUE TITLE
openwrt factory 710

### ISSUE THREAD

**Issue by AiyionPrime** [freifunk-gluon/gluon#399]
heyho,
building gluon from master returns excellent results for wr841n, but bricks the wr710n v2 (EU)

here's the bootlog - http://pastebin.com/fkcWDTt1
maybe it helps.

Aiyion

**Comment by NeoRaider** [comment]
What Gluon tree are you using? Our upstream Gluon has only support for the WR710N v1.

**Comment by NeoRaider** [comment]
It seems like the wrong `board` command line was fixed in OpenWrt r45756 on May 26th. Just update your Gluon tree to get that fix.

**Comment by AiyionPrime** [comment]
Thank you very much.
