### ISSUE TITLE
Improvement: add my patch which fixes u32int overflow

### ISSUE THREAD

**Issue by RubenKelevra** [freifunk-gluon/gluon#400]
Gateway-Selection Class 1 is broken in Batman-adv, here's the patch:

https://lists.open-mesh.org/pipermail/b.a.t.m.a.n/2015-May/013125.html

**Comment by NeoRaider** [comment]
Does this also affect the old batman-adv-legacy version?

openwrt-routing has been updated to the latest master, which contains the patch for batman-adv 2015.0.

**Comment by NeoRaider** [comment]
The fix has now been applied to batman-adv-legacy as well. When the updated batman-adv-legacy has been tested a bit more (there have been other changes besides this one), I'll also update it in v2015.1.x.
