### ISSUE TITLE
Gateway-Selection behavoir

### ISSUE THREAD

**Issue by RubenKelevra** [freifunk-gluon/gluon#401]
Currently, we're using Gateway Selection Class 20, which does nothing than selecting the gateway with the highes TQ each time the selected gateway drops to delta -20 of the highes TQ of gateway-list.

I wrote a patch to change the Gateway Selection Class xx behavior, which change the algorthm to selecting the gateway with the highest bandwidth of the Gateway-List, but with a limit of delta -20 of the highes TQ in List, each time the selected gateway is dropping to delta -20 of the highes TQ.

Currently testing my patch... so I doesn't link it though.

Else the Gateway Selection Class 1 behavior is now fixed by me, there was a integer overflow issue. So when we use a fixed release we also might change to Gateway Selection Class 1, which implements a mixed calculation of TQ and Bandwidth.

**Comment by NeoRaider** [comment]
I think making the gw selection class configurable in `site.conf` would make sense. I'll add such an option.
