### ISSUE TITLE
Feature Request: Add config mode option to put LAN ports to br-wan instead of br-client

### ISSUE THREAD

**Issue by Kunsi** [freifunk-gluon/gluon#405]
Config mode should have an option to bridge WAN and LAN ports on Routers, so it could be used as ethernet switch (Have a "private LAN" like there's already "private WLAN")

Currently this is only possible to do using ssh access, and will likely break on update.

See also Issue #284 here and pull request freifunk-gluon/packages#71

**Comment by NeoRaider** [comment]
As you mentioned, this will be provided by #284. Closing as duplicate.
