### ISSUE TITLE
sysupgrade, update from "opkg_repo"

### ISSUE THREAD

**Issue by aeickho** [freifunk-gluon/gluon#418]
on a sysupgrade opkg_repo will not be updated.
  barrier_breaker -> chaos_calmer

https://dev.openwrt.org/ticket/20079#ticket

**Comment by NeoRaider** [comment]
I don't think this is a problem. opkg.conf should not be touched (there are other options besides the repository path), and a user who is able to install packages can also adjust the path herself.

**Comment by tcatm** [comment]
If this is a problem at all it must be dealt with in OpenWrt first. Gluon does not rely on opkg repositories so this is not a problem for us.
