### ISSUE TITLE
openssl is updated to 1.0.2d

### ISSUE THREAD

**Issue by ES110178** [freifunk-gluon/gluon#420]
Hi there,
make downloads the old openssl 1.0.2c and gets 404 error, because the new version is 1.0.2d
i mean the /gluon/openwrt/package/libs/openssl

**Comment by NeoRaider** [comment]
This has been fixed both in the Gluon master and the v2015.1.x branch more than one week ago. Please don't report bugs that are already fixed.

We'll release v2015.1.2 soon, you can just use v2015.1.x in the mean time.

We are aware that it is unfortunate that the build of our release tags breaks like this, but we can't really change that the OpenSSL maintainers fail to provide stable download links... We're currently planning to provide a mirror of all dependencies of Gluon, which will avoid such issues in the future.
