### ISSUE TITLE
autoupdates on nodes with uplink later

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#426]
If all nodes that have an uplink would wait some time longer than nodes without, this would enhance the chance for nodes without uplink to update first to a new milestone for example with a channel change.

**Comment by MichaelSasser** [comment]
I've seen a script from any community in the forum doing exact this. It would be cool, to bundle that idea with your other idea in #427, that should also fix that problem, even if a node is currently down.

**Comment by NeoRaider** [comment]
#427 will make this redundant, and we'd like to avoid implementing topology-dependent behaviour for the autoupdater if we can...
