### ISSUE TITLE
Build a management interface for nodes

### ISSUE THREAD

**Issue by enko** [freifunk-gluon/gluon#433]
I propose of building a management interface for nodes. This includes the following tasks:

* Auto-Update
* Configuration
* Reboot

## Management interface

The job of the management interface is to provide a service for the community. It is optional and everyone who wants to setup his own instance can do it. The audience of this tool are community admins who are maintaining community nodes and individuals which are running more than one node.

### Daemon

The management interface consists of two components. One part is a daemon which does the actual heavy lifting:

* Retrieving information from nodes (responsed/ssh) and put it into a database.
* Setting configuration on the nodes
* Deploy updates

### Webinterface

It is a simple CRUD for the database. You can edit these objects:

* ssh private key
* node
** mac address
** assign a ssh key
* my user
** change your password

## Task: Auto-Update

At the moment the autoupdater is dumb and will result in a broken network under some conditions. If you change network parameters (for example WIFI channel or batman version), nodes will loose connectivity to neighbouring nodes and in result can't connect to the update server.

To improve this situation the daemon will calculate an update priority for every node based on number of uplinks. The update priority controls the order of the deployment. So nodes with less uplinks will be updated first and those with with more later. You can still deploy updates without compatibility over a given time frame.

## Task: Configuration

You can set various configurations of the node, for example contact, geolocation etc.

## Task: Reboot

You can reboot the node for whatever reason.

**Comment by adlerweb** [comment]
Hmm... Centralized decision are always a good source for failures and/or possible security nightmares. However here my bits:
* Downloading the update beforehand will consume a lot of memory - not sure if it is a good idea to keep it there for longer periods of time.
* I would prefer staying away from ffmap-backend and alfred since they aren't exactly reliable

**Comment by enko** [comment]
At Thu, 06 Aug 2015 00:33:57 -0700,
Florian Knodt wrote:
> Hmm... Centralized decision are always a good source for failures
> and/or possible security nightmares.

Of course, but a decentralized approach would require much more effort
and thinking. As for security: As I understand it, the updates are
already signed, so only updates with a correct signature will be accepted?

> * Downloading the update beforehand will consume a lot of memory - not
>   sure if it is a good idea to keep it there for longer periods of
>   time.

> * I would prefer staying away from ffmap-backend and alfred since they
>   aren't exactly reliable 

Thats good to know, since I'm relativly new to the hole gluon
stack. Knowing this, I think I would create a daemon which scans the
node for its version, saves the result to a database (what kind of
database is up to discussion, I preffer flatfiles for the moment,
since the volume of data is manageable) and also pushes
the update to the node via ssh.

I think since it might not be a good idea to save the update for a
longer time on the node, it might be good to calculate a update
priority score for all the nodes. For example: Nodes with only a batman link
get a high score, if the uptime isnt so stellar of the only batman
node, the score rises again. If the node has a wan interface, the
score will ne relativly low, since it does not depend on the batman
link.

**Comment by enko** [comment]
I have updated the ticket to reflect the latest discussion on IRC and this Ticket.

**Comment by NeoRaider** [comment]
Most Gluon-based network already have too much centralized infrastructure. We'd like to avoid by all means to add even more centralized control over the nodes... Giving one (or multiple) central server SSH access to nodes, even with the consent of the node owner, is not acceptable.

There are some ideas for decentralized management facilities though (see http://www.nilsschneider.net/2015/08/14/ff-online-config.html ).

Synchronizing firmware updates is a completely different issue, and there are some approaches to make it unnecessary (see #427 ).
