### ISSUE TITLE
batman-adv-v15: double fragmentation issue (formerly: mow/mol issue)

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#435]
batman-adv v15 does not correctly handle fragmentated packets when forwarding them through links requiring even more fragmentation, i.e. a 1500 byte packet is fragmented to fit within an MTU of 1400 and forwarded over a link with an MTU of 1300. In this case batman-adv v15 does not fragment the already fragmented packets to match the lower MTU but instead tries to send a too large packet through link causing that packet to be dropped.

Script for reproducing this problem: https://gist.github.com/tcatm/1832c8e4fb6198f0adb3
Relevant documentation: http://www.open-mesh.org/projects/batman-adv/wiki/Fragmentation-technical#Limitations

**Comment by viisauksena** [comment]
i did not get this completly : for to clarify ...
did this happens with v14 also?
so i do decrease mtu of mesh-vpn to 1280 , or something?

**Comment by jplitza** [comment]
No, this did not happen with v14.
Yes, 1280 is a common choice by many communities for the mesh-vpn. The rationale probably goes something like "It has to be fragmented anyway, so use something that will surely not cause any problems."
