### ISSUE TITLE
wireless config: set channel, htmode and regdom outside gluon-mesh-batman-adv-core

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#437]
Channel, htmode and regdom settings are useful for other routing protocols. I'd like to introduce a package "gluon-wireless-base" that will take care of setting these options so they can be used both by batman-adv and babeld (which I'm currently integrating into Gluon). Does this make sense?

**Comment by NeoRaider** [comment]
I guess that makes sense.

Alternatively, this could be moved to gluon-core. We could make all of this configuration optional, so building the firmware without wifi24/wifi5 sections will just result in a wired-only mesh firmware.
