### ISSUE TITLE
Check Site

### ISSUE THREAD

**Issue by stebifan** [freifunk-gluon/gluon#439]
Is it possible to implement a make check in gluon?

It would be nice to have the option to check the site.conf for syntax error

**Comment by NeoRaider** [comment]
This is already done (it was broken in the Gluon master some time ago, but it has been fixed two weeks ago).

**Comment by NeoRaider** [comment]
Ah, you probably meant a site check independent of the "normal" make target. That is not really possible because of the way the site checks are realized.

**Comment by rubo77** [comment]
Maybe someone could write an external (online) sire checker
