### ISSUE TITLE
trim hostname in lucy input field

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#444]
When entering a hostname starting or ending with a space, you get an error message, that there are invalid characters, but it is not really visible.

same with the coordinate fields.

It would be handy if all field entries would automatically be trimmed on save so you only get an error message if you do something really wrong.

**Comment by tcatm** [comment]
Could you contact upstream (OpenWrt) to check whether it can be fixed there?

**Comment by rubo77** [comment]
I thought this would be something the lua scripts would have to manage? Who is creating the error message that there are false characters in the hostname?

**Comment by tcatm** [comment]
Verification is handled by luci in this file https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/cbi/datatypes.lua

**Comment by rubo77** [comment]
https://github.com/openwrt/luci/issues/458

**Comment by rubo77** [comment]
This could also be handled according to this package: https://github.com/ffgtso/ffgt_packages-v2015.2/blob/master/gluon-config-mode-hostname-ffgt/files/lib/gluon/config-mode/wizard/0100-hostname.lua

**Comment by NeoRaider** [comment]
Obsoleted by pretty-hostname support.
