### ISSUE TITLE
status-page & wifi-iface mesh_radio0 disable

### ISSUE THREAD

**Issue by Joachim-Wolff** [freifunk-gluon/gluon#451]
If wifi-iface mesh_radio0 is disabled in /etc/config/wireless, the status-page show the usage of "iw dev"

Putting a # in the system call helps as dirty workaround, /lib/gluon/status-page/www/cgi-bin/status line 79... 

At least v2015.1 + v2015.1.2 are affected.

**Comment by tcatm** [comment]
Thanks for pointing this out. The "old" statuspage was never meant to be perfect. It's just a few hardcoded commands that would output useful information in most cases and it will be replaced with the a new status page soon.

**Comment by kb-light** [comment]
Should already be solved in the current Master since 753c1f9, since iw dev <dev> link is not used anymore in the "old" statuspage.

**Comment by NeoRaider** [comment]
As @kb-light pointed out, this has been solved already.
