### ISSUE TITLE
Get rid of rpcd?

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#452]
Before making a Chaos-Calmer-based release we should look into getting rid of rpcd, which is a completely unneeded dependency of LuCI (it is used for authentication only in LuCI 1, but Gluon doesn't use authentication in LuCI). While rpcd is very small, having an unused daemon runing all the time doesn't seem like a good idea.

**Comment by FreifunkUFO** [comment]
rpcd is needed for any ajax/javascript based webservice, for luci2 (a very small webservice) and also for getting statusinformation/ setting configuration via http.. it connects via ubus.
(f.i. alfred values can be read via rpcd: https://github.com/freifunk-leipzig/solarfestival-packages/blob/master/rpcd-mod-alfred/rpcd/usr/libexec/rpcd/alfred )

it seems that gluon-firmware has done that some months ago via an extra new service called "gluon-announced". Now that could be migrated to rpcd now.

**Comment by tcatm** [comment]
Both rpcd and gluon-announce serve different purposes. rpcd can not be used in place of announced (and announced can not replace rpcd).
