### ISSUE TITLE
Use luci-lib-jsonc instead of luci-lib-json

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#455]
https://github.com/openwrt/luci/tree/master/libs/luci-lib-jsonc

- [ ] ensure it offers equal functionality (i.e. https://github.com/openwrt/luci/commit/304eec2ebaf983fd067e5ae719f8ec023aad8b30)
- [ ] replace luci.json with luci.jsonc in all scripts
- [ ] ensure luci.json is not installed as a dependency

**Comment by jplitza** [comment]
openwrt/luci#457 is on the way to offer the same functionality regarding empty lists and objects.
