### ISSUE TITLE
wr941ND v6 Kernel Panic

### ISSUE THREAD

**Issue by strontium38** [freifunk-gluon/gluon#471]
With version 7f5c3e433bf01e7fd1ec5adfc3e1f740841ab945  there is a kernel pannic directly after boot.

The output on the serial console:
https://gist.github.com/strontium38/bb161d4ae7f4271a2766

**Comment by NeoRaider** [comment]
Yes, this is known, the 941v6 support was broken. This has been fixed just 30 minutes ago (a `make clean` is necessary after the update).
