### ISSUE TITLE
Change bandwith limit between timeframe

### ISSUE THREAD

**Issue by ReVoLt112** [freifunk-gluon/gluon#483]
In order to optimize the bandwith management, it would be great if the bandwith can be regulated by time. For example a Shop has a DSL 16.000 connection but need at least 10Mbit/s for buisness. After 18:00 o'clock, when the shop is closed, the bandwith could be used by 100% for Freifunk.

**Comment by jplitza** [comment]
Just like for #477, this can already be done using a cronjob file in `/lib/gluon/cron/` containing something like this:
```
0 18 * * * /usr/sbin/gluon-simple-tc mesh-vpn - -
0  6 * * * /usr/sbin/gluon-simple-tc mesh-vpn 6000 100
```
As this is a very specific setup that not nearly everybody wants to have, it makes no sense implementing a UI for that in the setup wizard. Thus, closing.
