### ISSUE TITLE
xen_domu target does not build an image

### ISSUE THREAD

**Issue by benchlor** [freifunk-gluon/gluon#485]
After creating targets/x86-xen_domu/profiles.mk as an empty file and targets/x86-xen_domu/config:

CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_xen_domu=y

make GLUON_TARGET="x86-xen_domu" runs without critical errors, but no image is build. I'd like to have an ext4-image, just like the x86-generic build, but I can't figure out how...

**Comment by NeoRaider** [comment]
1. Please don't open tickets for features not yet upstream, discuss such things in IRC or on the mailing list.
2. `profiles.mk` defines which images are built.
