### ISSUE TITLE
VMware x86-generic/x86-64 - IPv6 does not work

### ISSUE THREAD

**Issue by Datafreak** [freifunk-gluon/gluon#502]
Hi,

I hope someone can help me. I build the x86 Images from git master but the IPv6 does not work.
It looks like that the kernel modul can not be loaded. I use VMware vSphere Hypervisor 6 with a USB network card (asix-ax88179). I build this packages for it: kmod-libphy kmod-mii kmod-usb-net kmod-usb-net-asix-ax88179 kmod-usb-core kmod-usb3 libusb-1.0 zlib usbutils

In the configuration mode everything look ok. But after I have configured the node and rebooted I have no IPv6:
![01_logread](https://cloud.githubusercontent.com/assets/2600684/10057295/daf60ef6-623f-11e5-9180-8b17c9273a73.jpg)
![02_modprobe](https://cloud.githubusercontent.com/assets/2600684/10057296/daf7fd60-623f-11e5-91af-8d6ecd5a3643.jpg)
![03_modules](https://cloud.githubusercontent.com/assets/2600684/10057627/8d0238b2-6241-11e5-9e00-e2613f010042.jpg)
![04_kmodloader](https://cloud.githubusercontent.com/assets/2600684/10057298/dafd346a-623f-11e5-9fda-47d807800231.jpg)

Here the x86-64 image: https://www.dropbox.com/s/izu88dplkrsjs4f/gluon-ffka-master-x86-64-vmware.vmdk?dl=0

Can someone look on this issue?

Thanks,
Datafreak

**Comment by NeoRaider** [comment]
The image you provided works for me in VMware Workstation.

**Comment by Datafreak** [comment]
Hi Matthias,

thank you for you feedback. I have now deleted my VMware vSphere Hypervisor 6 and installed VMware vSphere Hypervisor 5.5. And there it works. So it looks like, the Image is somehow incompatible to the newest version of vSphere.

So I think we can close this issue here.

Best Regards,
Datafreak
