### ISSUE TITLE
gluon-announced: some responses are compressed, some not 

### ISSUE THREAD

**Issue by dereulenspiegel** [freifunk-gluon/gluon#505]
Hi,

I am currently playing with announced/respondd and noticed that the lua script called by respondd sometimes compresses answers with deflate and sometimes not. I think this is incostistent behavior and makes implementing a server collecting these information a bit harder. It would be nice if all responses are either compressed by the same algorithm or not compressed at all. Since deflate compression/decompression doesn't eat that much resources, but saves a bit bandwidth I would vote for compressing all responses with deflate.
If no one else is already working on this, I would like to create a PR for this, but I would like to have some consensus on this before. Thanks :)

**Comment by tcatm** [comment]
Uncompressed responses are used by the status page (that is, even older versions before compression was introduced). Newer software should always use `GET $thing`.
