### ISSUE TITLE
Problems with generated JSON of announce

### ISSUE THREAD

**Issue by datenhahn** [freifunk-gluon/gluon#514]
Json output contains "function: 0x ..." or "table: 0x...:" entries. The problem is in `/usr/lib/lua/gluon/announce.lua`

```lua
 function collect_dir(dir)
-	local ret = { [json.null] = true }
+	local ret = { [{}] = true }
```

Please see this ticket for more details.

https://github.com/freifunkMUC/ffmap-backend/issues/7

**Comment by tcatm** [comment]
Could you be a little bit more specific?

**Comment by datenhahn** [comment]
ah sorry, is probably fixed by usage of jsonc
