### ISSUE TITLE
"Foreign" ARP table entries

### ISSUE THREAD

**Issue by Tobi042** [freifunk-gluon/gluon#541]
We observe, that there is an extreme number of ARP requests flooding our network from many sources. These are either by foreign networks or for foreign networks and by "foreign" I mean non-Freifunk networks, mostly private IP ranges such as the ones found in many home networks. 

I suggest creating an ebtables filter package that prevents such ARP packets (src IP does not match prefix4 from site.conf OR dst IP does not match site.conf) from being forwarded via batman. It might be useful to have them forwarded to other local devices, so the rule should probably not be applied at br-client level, but rather really at bat-device level.

**Comment by tcatm** [comment]
It's valid usecase to use other IP Ranges (statically configured) within a layer 2 mesh network. I guess if such a feature is really desired the GCP might be a good place to implement it.

**Comment by NeoRaider** [comment]
I think such a package would be pretty trivial, I don't really see an issue with make it an official package.

I think we can in fact block ARP/ND for foreign IP space without breaking anything useful. When other ranges are routed over the mesh network, the local nexthops should still always have "correct" addresses.

**Comment by Tobi042** [comment]
I concede that it might be a valid use case, but I believe that most communities would profit from the reduced "management" traffic that such a package would ensue. As mentioned in my email on the mailing list, at times, Batman's distributed ARP table in our community is filled with 70% foreign IP addresses, with a non-negligible number of unresolvable ARP packets flooding every client regularly.
I could imagine an additional site.conf section that would define exceptions for such a rule. Also, normal clients would never see such out-of-range static IP addresses, because they would be L3-routed as the normal network subnet masks distributed by DHCP server do not allow for such traffic to be L2-delivered.

**Comment by mweinelt** [comment]
Das scheint dieses Paket von Paderborn zu erledigen:
https://git.c3pb.de/freifunk-pb/ffho-packages/tree/master/ffho/ffho-ebtables-net-rules
