### ISSUE TITLE
TL-WR941v6 - LAN-Port

### ISSUE THREAD

**Issue by hauetaler** [freifunk-gluon/gluon#550]
On TP-Link TL-WR941v6, Switch Port 1 doesn't work with the latest v6-patches. All the other ports seem to be ok. The router detects the plugged in cable, the corresponding LED lights, but that's all. No transfer is possible.

**Comment by NeoRaider** [comment]
Have you tested on multiple devices? This might be a hardware defect.

**Comment by hauetaler** [comment]
It's not a hardware defect. Switch port works fine on tp-link firmware.

**Comment by NeoRaider** [comment]
Okay, thanks for the report, I'll look into it.
