### ISSUE TITLE
ath10k candela-firmware does not load

### ISSUE THREAD

**Issue by RubenKelevra** [freifunk-gluon/gluon#563]
Currently the candela firmware does not load at boot, so the 5 GHz module of the Archer C7 is unavailable. 

Some weeks ago, the C7 was booting like this:
http://pastebin.com/iQpbQUQe

The latest master boots like this:
http://pastebin.com/x01Be4DE

**Comment by NeoRaider** [comment]
Should be fixed by 8ef02f33e9361556ed9c79ce47aad04608c52dec

**Comment by RubenKelevra** [comment]
Confirm the fix. Thank you!
