### ISSUE TITLE
Better documentation of disabled status handling for ibss/mesh config

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#574]

**Comment by MPW1412** [comment]
Is there any info or commit related to this? Documentation shouldn't be to hard to finish, so that v2015.2 will be ready soon.

Can you post the commit hash to the feature, which shell be documentated here? I'd like to look into it, but have no clue where to start.

**Comment by NeoRaider** [comment]
@MPW1412, the current behaviour has been implemented in 0335ce10e2fe2ba40ac9a3f76236cbf83befd462, #573 also has some information.
