### ISSUE TITLE
can't build gluon on Fedora 23 + opensuse 13.2 - openwrt paket (node-v0.12.7)

### ISSUE THREAD

**Issue by aeickho** [freifunk-gluon/gluon#589]
87dd5bb3bbe26e60e90c84560f0bb7a207f93e7b

import bz2 in tools/js2c.py 
ImportError: no module named bz2 

log:
https://gist.github.com/aeickho/e6faba1c6b130936d314

**Comment by NeoRaider** [comment]
If you are affected by this bug, you need to run `make dirclean` in your build tree or make a fresh git clone for the fix to have an effect.

**Comment by aeickho** [comment]
tnx, patch is fine
