### ISSUE TITLE
Problem in gluon-neighbour-info?

### ISSUE THREAD

**Issue by AKA-47** [freifunk-gluon/gluon#591]
Seems there is a problem in gluon-neighbour-info:

New statuspage shows

Mesh-VPN
    true
Automatische Updates
    false
Branch
    stable

but

uci show | grep vpn

simple-tc.mesh_vpn.enabled='0'
simple-tc.mesh_vpn.ifname='mesh-vpn'

vs

gluon-neighbour-info -d ::1 -p 1001 -t 1 -c 1 -r nodeinfo

fastd":{"enabled":true,"version":"v17"},
"autoupdater":{"enabled":false,"branch":"stable"}

but 

uci show

autoupdater.settings=autoupdater
autoupdater.settings.version_file='/lib/gluon/release'
autoupdater.settings.enabled='0'
autoupdater.settings.branch='experimental'
autoupdater.experimental=branch

**Comment by NeoRaider** [comment]
I've found the issue in the fastd announce script, but I can't find anything wrong with the autoupdater one.

**Comment by NeoRaider** [comment]
The fastd issue has been fixed by 5ecb8a73668d030561dda8cf22143bedb27b05da.

Did you by any change change the autoupdater branch via SSH? At the moment, UCI configs aren't reloaded by gluon-announced, so a reboot is necessary to see the changed values.

**Comment by AKA-47** [comment]
Found the problem with autoupdater .. Reboot did it finally :D
