### ISSUE TITLE
old Statuspage

### ISSUE THREAD

**Issue by fragstone** [freifunk-gluon/gluon#594]
Hi,

ok the new Statuspage has some good features and is a eyecatcher but is it possible to make a gluon package availabe with the old statuspage?
It will be nice when people are able to choice the right package for yourself?

regards
Thomas

**Comment by pinguinpfleger** [comment]
Why do you want to go back to the old status page?

**Comment by fragstone** [comment]
sorry pinguinpfleger :-)

but that is not the question. 
it are plus points for the new one and plus points for the old one.
so i think over the next month users will use the new one. 

but actual i think users shout be able th choise it.

**Comment by mmalte** [comment]
Some possible issues:

The load rises significantly when someone is viewing the the status page for some minutes.  
Only one (or a few) user at a time is able to use the status page. 
The contact information is displayed.

**Comment by pinguinpfleger** [comment]
I just wanted to here your intention why you seem to prefer the old one, no big deal.

**Comment by fragstone** [comment]
one big thing for me is that i can check the status page by linky (lynx) [text console browser]

**Comment by pinguinpfleger** [comment]
mmalte: if that's true the new status page is a serious vulnerability for DOS attacks :(
maybe we could improve the status page by splitting it up in specific sub status pages and not generate all status data at once.

**Comment by mmalte** [comment]
In a huge Mesh with 960 online nodes I saw a 841v10 reboot when I visit the status page. 

Had no time to reproduce the issue.

**Comment by tcatm** [comment]
@fragstone Sure, it may still be possible to use the old status page and there could even be a package if someone volunteers to maintain it.

**Comment by fragstone** [comment]
Hi Tcatm,

stupid question :D who i can found the old code to see if i can maintenance it.

**Comment by jplitza** [comment]
@fragstone [This](https://github.com/freifunk-gluon/gluon/tree/431ac81407919f9e2a88ea1328cafaf3cdf30f2e/package/gluon-status-page) probably is the best starting point.

**Comment by NeoRaider** [comment]
The old status page is still included in the gluon-status-page package ( https://github.com/freifunk-gluon/gluon/tree/master/package/gluon-status-page/files/lib/gluon/status-page/www ), just use http://[address]/cgi-bin/status to reach it.
