### ISSUE TITLE
config mode has to forbid "." in hostname

### ISSUE THREAD

**Issue by mokkin** [freifunk-gluon/gluon#596]
![bildschirmfoto_2015-12-10_23-04-15](https://cloud.githubusercontent.com/assets/2938748/11730046/ea5d4fc2-9f92-11e5-9a2b-c641689b335b.png)
![bildschirmfoto-markus vzl-laptop0](https://cloud.githubusercontent.com/assets/2938748/11730255/22f73266-9f94-11e5-85ec-836f8e508253.png)

**Comment by NeoRaider** [comment]
This will be fixed by #414, thus closing as duplicate.
