### ISSUE TITLE
Change Chatroom or help to enter

### ISSUE THREAD

**Issue by A-Kasper** [freifunk-gluon/gluon#601]
You can't enter the gluon chat without registration. The Registration mail never found its way to my gmx. Account. I would like you to think about changing the chat location to another one which is easier to use. Otherwhise I would suggest to add a step by step guide to the documentation.

**Comment by NeoRaider** [comment]
Hackint does not send a registration mail. As mentioned in https://hackint.org/faq , the supplied mail address doesn't even need to be valid to complete registration.

I've removed the +r mode for the channel, it was mainly a temporary measure against spam.
