### ISSUE TITLE
Android Browser and the new status page

### ISSUE THREAD

**Issue by JamesT42** [freifunk-gluon/gluon#606]
Hi!
I'm testing the current master on an offloader and when viewing the page with the 2 Android devices I own, i don't see all information.
However, the page works finde on the same device with Opera. So I do not think it is an ipv6 connection issue.
View on PC: https://www.dropbox.com/s/tx6d9yrehek8oj5/PC-Ok.jpg?dl=0
View on Smartphone with Android 4.4.4: https://www.dropbox.com/s/a8m2twmtvmjfpup/Phone-Android-4.4.4.jpg?dl=0 Missing some mesh infos
View on Tablet with Android 4.4.2: https://www.dropbox.com/s/a0u46gsqg3fgaci/Tablet-Android-4.4.2.png?dl=0 Missing all mesh infos
(It is an offloader, so the lack of signal strength for the mesh devices is due to mesh over lan)
Cheers,
JT

**Comment by tcatm** [comment]
Currently only (recent versions of) Firefox and Chrome are supported. Other browser might experience issues. In most cases it doesn't work due to these not supporting a feature called "Server-sent events".

**Comment by Byggvir** [comment]
Currently my Firefox on Android doesn't show Systemlast, RAM, NVRAM and Traffic. Chrome shows these value and they are updated. But Firefox is instable and unusable at the moment. I would not bother with Firefox at the moment.

**Comment by JamesT42** [comment]
I have not seen any issues with Firefox.

**Comment by jplitza** [comment]
I can confirm @Byggvir's report. My Firefox for Android doesn't show these values either. I does show the graphs and everything else, though.

@JamesT42 You did see that this is about Firefox on *Android*, right?

**Comment by JamesT42** [comment]
@jplitza Yeah sorry, didnt read the Android part. In Firefox Android I can confirm the problem.

**Comment by tcatm** [comment]
Firefox for Android is missing [Internalization API](http://caniuse.com/#feat=internationalization).
