### ISSUE TITLE
Make gluon status page more robust

### ISSUE THREAD

**Issue by mmalte** [freifunk-gluon/gluon#618]
This is how the next node functionality is intercepting requests designated for the gluon status page:

https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-next-node/files/lib/gluon/ebtables/250-next-node

Would be great to go a little bit deeper and use:

ebtables -t nat -A PREROUTING --logical-in br-client --ip-dst next_node.ip4 -p ipv4 -j dnat --to-destination next_node.mac

This way the next node even works if my client is in the wrong subnet, for example because we are using different parts of our IP space in different segments of our network.

**Comment by NeoRaider** [comment]
I don't think intercepting requests is something a node should do; nobody else has commented on this proposal, so I'm closing it.
