### ISSUE TITLE
gluon-neighbour-info can't query neighbours over Mesh-on-WAN

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#619]
Maybe a firewall issue. Reported on IRC.

**Comment by NeoRaider** [comment]
The issue is that the requests are multicast, not unicast, and thus the replies don't match the RELATED firewall rules.

A quick workaround would be to generally accept UDP packets from port 1001 to high ports (1024+) on the WAN port from fe80::/64.

**Comment by jplitza** [comment]
Why, again, are me more paranoid on the WAN interface (default: reject) than on the Freifunk interface (default: accept)? Not only does the latter mostly have an unfiltered, public IPv6 address in most Freifunk communities nowadays, but also is the WAN interface oftentimes behind a NAT router without a public address and thus better protected.

**Comment by NeoRaider** [comment]
@jplitza, some communities had issues with DNS amplification attacks abusing nodes which had global addresses (e.g. directly connected to a cable modem), after which we installed the restrictive WAN policy...

I'll see if I can find time to write a patch for this bug tonight.

**Comment by jplitza** [comment]
Wouldn't blocking port 53 be sufficient to prevent DNS amplification attacks? That's what we do on the Freifunk interface as well, which – as I said – has a public address, too.

But don't get me wrong, I'm not advocating to loosen the policy on the WAN interface, I'm suggesting to tighten the policy on the Freifunk interface.

And if the firewall rule you mentioned above (allow 1001→ephemeral port) is the intended solution, I can put that together too.

**Comment by NeoRaider** [comment]
Yes, that's the solution I indented to implement.
