### ISSUE TITLE
UniFI AP Outdoor+

### ISSUE THREAD

**Issue by Mathiasb007** [freifunk-gluon/gluon#627]
Irgenwie bleibt der AP bei 54Mbits und wechselt trotz Maximaler Signalstärke nicht den Modus. An was könnte das liegen ?

**Comment by corny** [comment]
Weiß jemand genaueres?

**Comment by NeoRaider** [comment]
Sollte mit 0e85726a0a9bf4fd2b7faa08f5d86eac03283071 gefixt sein.
