### ISSUE TITLE
Support for Mediatek/Ralink WLAN

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#648]
Ralink WLAN hardware does support VIFs, but
* no VIFs with IBSS (but AP + 11s works)
* only with sequential MAC addresses (the MAC addresses of all VIFs may only differ in the last 3 bits -> 8 VIFs are supported)

The MAC address scheme deployed by Gluon doesn't not generate sequential MAC addresses (the address of a single radio are counted in byte 2, different radios in byte 3). This was done to avoid address collisions (we have to deal with devices with only a single assigned MAC address, so devices bought together often have very similar MAC addresses).

We plan to fix this by generating a new base MAC address by applying a hash function to the real primary address, and derive the VIF addresses from this base address.

**Update:**

* The effective length of such a MAC prefix is 43bits, as the last 3 bits are variable, and 2 bits are fixed (unicast / locally administered). This yields a collision probablity of 1.4e-08 for 1000 prefixes and 1.4e-06 for 10000 prefixes.
* Using a single prefix for all interfaces of a node would work, as 8 addresses are enough even for nodes with two radios.
  * 8 addresses would suffice for 4 radios for AP+11s, and 2 radios for AP+IBSS+11s (which is not recommended anyways). No device we support has more than 2 radios, and using additional radios doesn't work without manual config (so requiring manual config of the MAC addresses wouldn't be a problem)
  * Non-wireless interfaces (mesh VPN, mesh-on-WAN/LAN) need addresses as well. Conveniently, it is possible to reuse AP VIFs' addresses for these interfaces, as APs don't participate in meshing directly, so their MAC addresses aren't visible to batman-adv.
  * Example configuration for the worst case:
    * 0: client0; mesh-vpn
    * 1: mesh0
    * 2: ibss0
    * 3: client1; mesh-on-wan
    * 4: mesh1
    * 5: ibss1
    * 6: mesh-on-lan
    * 7: unused

**Comment by FreifunkUFO** [comment]
your expectations are wrong: at least some mediatek/ralink hardware support ad-hoc + vAP mode.

p.s. for the hardware which doesnt support that: gluon already has queckboxes for disabling mesh or vAP on the device!?

**Comment by NeoRaider** [comment]
I've updated the issue description with a more detailed plan.

@FreifunkUFO: That's good to know, but doesn't really change a lot. The missing IBSS support in some models is reason enough to switch to 11s as soon as possible, so we plan to generally phase out IBSS support in Gluon as soon as we have a migration plan.

**Comment by FreifunkUFO** [comment]
so here a small ticket to support at least devices, wo can "ad-hoc + vAP":
https://github.com/freifunk-gluon/gluon/issues/650

**Comment by waschmi** [comment]
Archer C50 (mediatek mt7620a and mt7612e)
For Gluon I had to make MAC entries manualy. IBSS works but not IBSS+AP. 11s I didn't test, yet. 
[openwrt-archer-c50.TXT](https://github.com/freifunk-gluon/gluon/files/129237/openwrt-archer-c50.TXT)
(reset button doesn't work. firmware update over config-mode page works ok.)

**Comment by jotzt** [comment]
D-Link DIR-860L (`ramips-mt7621`) is sucessfully running with L2TP/802.11s under Gluon v2016.1.2. 
 - target was added according to the Gluon documentation
 - 11s is stable but slow, only MCS0 (6.5 Mbit/s) at 2.4G and 5G so far
 - client connection is barely stable
 - correct primary MAC-address can be set similar to TL-WDR3600 `/sys/class/ieee80211/phy1/macaddress` 

Anything I could test on that DIR-860L in order to support the development?

Status: http://karte.freifunk-muensterland.org/map07/#!v:m;n:e46f132ebcac
