### ISSUE TITLE
Activation of mesh_no_rebroadcast for Mesh-on-WAN/LAN

### ISSUE THREAD

**Issue by FFS-Roland** [freifunk-gluon/gluon#652]
Currently **option mesh_no_rebroadcast '1'** is only set on interface 'mesh_vpn' per default, but will also reduce load on the other cable based meshing variants. All ARP and most ICMPv6 on Freifunk Client Network is forewarded as broadcasts on mesh-level ethernet, where especially IPv6 Router Advertisements are consuming a lot of ressources on Nodes.

The comment of Linus Lüssing, who implemeted this option in batman-adv on September 2013:
_With this option set incoming multicast payload frames on `<iface>` are not being rebroadcasted on `<iface>` again. This option should be set on links which are known to be transitive and symmetric only, for instance point-to-point wifi longshots or wired links._

Therefore at Freifunk Stuttgart we began to set this option manually on installations using Mesh-on-LAN and/or Mesh-on-WAN since September 2015 using SSH:

`uci set network.mesh_wan.mesh_no_rebroadcast='1'`
`uci set network.mesh_lan.mesh_no_rebroadcast='1'`
`uci commit`
`reboot`

In times of very high broadcast and multicast traffic this prevented nodes from beeing overloaded, in particular TP-Link WR841N/ND.

Our proposal is to activate this option by default on mesh_wan and mesh_lan. This can be done e.g. with modification of two files:

\package\gluon-mesh-batman-adv-core\files\lib\gluon\upgrade\330-gluon-mesh-batman-adv-core-mesh-on-wan

`if not c:get('network', 'mesh_wan') then`
&emsp;`c:section('network', 'interface', 'mesh_wan',`
&emsp;&emsp;`{ ifname = 'br-wan'`
&emsp;&emsp;`, proto  = 'batadv'`
&emsp;&emsp;`, mesh   = 'bat0'`
`+++         , mesh_no_rebroadcast = '1'`
&emsp;&emsp;`, auto   = site.mesh_on_wan and 1 or 0`
&emsp;&emsp;`})`
`end`

\package\gluon-mesh-batman-adv-core\files\lib\gluon\upgrade\340-gluon-mesh-batman-adv-core-mesh-on-lan

`uci:section('network', 'interface', 'mesh_lan',`
&emsp;`{ ifname  = sysconfig.lan_ifname`
&emsp;&emsp;`, proto  = 'batadv'`
&emsp;&emsp;`, mesh   = 'bat0'`
&emsp;&emsp;`, macaddr = util.generate_mac(1, 1)`
`+++         , mesh_no_rebroadcast = '1'`
&emsp;&emsp;`, auto   = enable and 1 or 0`
&emsp;&emsp;`})`

With best regards from Stuttgart,
Roland.

**Comment by T-X** [comment]
There is just one scenario that I could think of where things would break: A WDS wifi bridge solution with STA isolation enabled. And a mesh-on-wan/lan router connected to one of this bridge-STAs via cable. But I've never heard of anyone enabling STA isolation there.

So looks good to me.
