### ISSUE TITLE
Translation support for community name

### ISSUE THREAD

**Issue by FreifunkUFO** [freifunk-gluon/gluon#654]
please change the type of editing the community name inside the wizard.
at the moment all translation files has to be changed from "entenhausen" to local city name.. thats not nice!

also the email adresses should be configured in a different way, not within translation module

**Comment by NeoRaider** [comment]
I agree that our use of the translation module for the config mode texts is a bit abusive, but I don't see any reason to change it. The idea of the site repo is to be replaced by community-specific data, and using the i18n functions allow communities to do exactly that: adjusting the texts displayed by the config mode to local needs.

Please also note that Gluon is not only used for Freifunk anymore, so it is important that it's simple to completely remove any mention of "Freifunk" from the config mode. Another common change is not to display the key and a mail address at all for networks where no key registration is necessary.

Before we had i18n, these texts were configurable in site.conf; basically, we have moved the texts out of there to allow per-language configuration. Having two separate places to adjust the city name/mail address and the rest of the texts seems unnecessarily complicated to me.
