### ISSUE TITLE
batman-adv - interface MTU size warnings in dmesg

### ISSUE THREAD

**Issue by wararjey** [freifunk-gluon/gluon#660]
With the latest gluon-v2016.1-1-g44bdf37 I'm seeing several MTU size warnings in dmesg on my TP-Link TL-WDR3600 v1. See snippets of the kernel log in this report: 

[   44.060000] batman_adv: bat0: Adding interface: eth0.1
[   44.070000] batman_adv: bat0: The MTU of interface eth0.1 is too small (1500) to handle the transport of batman-adv packets. Packets going over this interface will be fragmented on layer2 which could impact the performance. Setting the MTU to 1532 would solve the problem.
[   44.090000] batman_adv: bat0: Interface activated: eth0.1

[   46.170000] br-client: port 1(bat0) entered forwarding state
[   46.450000] batman_adv: bat0: Adding interface: mesh-vpn
[   46.450000] batman_adv: bat0: The MTU of interface mesh-vpn is too small (1320) to handle the transport of batman-adv packets. Packets going over this interface will be fragmented on layer2 which could impact the performance. Setting the MTU to 1532 would solve the problem.
[   46.480000] batman_adv: bat0: Interface activated: mesh-vpn
[   46.490000] batman_adv: bat0: no_rebroadcast: Changing from: disabled to: enabled
[   46.520000] batman_adv: bat0: Changing gw mode from: off to: client
[   46.560000] batman_adv: bat0: hop_penalty: Changing from: 30 to: 15
[   46.560000] batman_adv: bat0: multicast_mode: Changing from: enabled to: disabled
[   46.610000] batman_adv: bat0: orig_interval: Changing from: 1000 to: 5000

Upstream Internet connection on this node is a VDSL link, so a MTU of 1500 is likely to large.

Regards

**Comment by NeoRaider** [comment]
This is expected. If you don't see this message, something is wrong.
