### ISSUE TITLE
Check if coordinate are valid

### ISSUE THREAD

**Issue by mmalte** [freifunk-gluon/gluon#664]
Would be nice to check if the geo ID is valid:

![geo-koordinaten](https://cloud.githubusercontent.com/assets/6890998/13300371/0aa60cd6-db40-11e5-8516-c18cfcd16434.png)

**Comment by viisauksena** [comment]
but this should be better checked by the meshviewer .. something like, if distance >=25 km ignore

**Comment by jplitza** [comment]
@viisauksena Distance of what? Why can't you have a community with a diameter greater 25km?
@mmalte Can you give what coordinates were actually specified for those two nodes?

**Comment by viisauksena** [comment]
@jplitza i mean a single link between 2 nodes, could not imagine how you get 25km + with actual HW we use ..

**Comment by tcatm** [comment]
We can't prevent nodes from announcing bogus information so this can not be fixed in Gluon. However, an improved coordinate input box could prevent mistakes.

Is that something you'd like to work on?

**Comment by rotanid** [comment]
feel free to open a pull request if you want to do what @tcatm suggested.

**Comment by viisauksena** [comment]
this question was for @mmalte .. right

**Comment by rotanid** [comment]
for everyone.
