### ISSUE TITLE
Picostation startet immer wieder mit leeren Einstellungen

### ISSUE THREAD

**Issue by FabianCernota** [freifunk-gluon/gluon#687]
Hallo zusammen,
ich habe auf eine Picostation Gluon v2016.1.2 geflasht. Wenn ich jetzt im Configmode bin und Einstellungen setze sind diese nach einem Neustart wieder weg und ich lande im Configmode.

Muss ich noch irgendetwas machen?

Gruß
Fabian

**Comment by NeoRaider** [comment]
Dein Gluon-Image ist kaputt; es wurde beim Update von v2016.1 auf v2016.1.2 entweder `make update` oder `make clean` (oder beides) vergessen.

In diesem Zustand ist der Flash nicht beschreibbar, also auch kein normales Sysupgrade möglich. Du musst nach Erzeugen eines korrekten Images dieses per TFTP flashen.

**Comment by FabianCernota** [comment]
Auch mit einem frischen Gluon kann ich es noch auf 2 verschiedenen Picostations nachstellen. 

Im Forum gibts es noch jemand der auch Probleme mit der Picostation hat:
https://forum.freifunk.net/t/ubiquiti-picostation-m2-startet-nur-in-den-gluon-configmode/11361

**Comment by NeoRaider** [comment]
@FabianCernota, wie hast du das frische Gluon aufgespielt? Wenn schon einmal ein kaputtes Gluon drauf war, muss über TFTP geflasht werden.

**Comment by FabianCernota** [comment]
@NeoRaider  Eine per TFTP und eine von der Stockfirmware heraus.

**Comment by NeoRaider** [comment]
@FabianCernota Logs?

**Comment by FabianCernota** [comment]
@NeoRaider Welche genau? An die Gluon Logs komme ich ja nicht.

**Comment by NeoRaider** [comment]
@FabianCernota, warum nicht? Einfach per Telnet drauf und `dmesg` bzw. `logread` eingeben.

**Comment by FabianCernota** [comment]
http://pastebin.com/ZUrFTJ5v

**Comment by NeoRaider** [comment]
Okay, die Picostation benutzt einen Flash-Chip von einem anderen Hersteller als Macronix... ich bau nachher nen Patch.

**Comment by MPW1412** [comment]
Wir haben das hier auch mehrfach schon gesehen jetzt, falls du noch Logs brauchst. Wir freuen uns auf den Patch :).

**Comment by NeoRaider** [comment]
Im master sollte 1ccd24df770f24d5660885d264b3a2af51bf6d1e das Problem beheben. Bitte einmal testen, wenn der Patch funktioniert, landet er auch in v2016.1.x.

**Comment by NeoRaider** [comment]
Ich habe gerade einen anderen Patch und zugehörige Diskussionen gefunden, daher vermute ich, dass mein Patch mehr Probleme auslöst als er behebt.

Siehe:
http://patchwork.ozlabs.org/patch/549173/
http://patchwork.ozlabs.org/patch/553683/

**Comment by NeoRaider** [comment]
Könnte mir jemand leihweise eine entsprechende PicoStation zukommen lassen? Adresse gibt's per Mail oder IRC.

**Comment by NeoRaider** [comment]
Hmm, CPE210 und WDR4300 benutzen denselben Flash-Chip. Ich probier erstmal, das Problem mit den Geräten zu reproduzieren.

**Comment by NeoRaider** [comment]
Bitte doch einfach mal mit dem Patch testen (also nicht den neuesten Stand des Master, in dem ich den Patch reverted habe, sondern den davor).

**Comment by NeoRaider** [comment]
Und könnte mal jemand eine PicoStation aufschrauben und nachschauen, was auf dem Flash-Chip steht? Laut Kernel-Log ist das ein Spansion s25fl064k, aber möglicherweise ist der Log flasch und es ist eigentlich ein Winbond w25q64.

**Comment by justelex** [comment]
Hi,
ich habe die eben mal aufgeschraubt, 
es ist ein Winbond 25Q64FVIG
Danke für deine Mühe

**Comment by NeoRaider** [comment]
Neuer Patch: d9ca449ed0109651d748b22e6a6421867b1e9ae9 Bitte testen!

**Comment by FabianCernota** [comment]
@NeoRaider Funktioniert leider noch nicht:

`[    0.000000] Linux version 3.18.27 (cernota@arch-fabian) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r47335) ) #1 Tue Mar 29 22:46:54 CEST 2016
[    0.000000] MyLoader: sysp=cc33cc33, boardp=33cc33cc, parts=cc33cc73
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
[    0.000000] SoC: Atheros AR7241 rev 1
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 02000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x01ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x01ffffff]
[    0.000000] Initmem setup node 0 [mem 0x00000000-0x01ffffff]
[    0.000000] On node 0 totalpages: 8192
[    0.000000] free_area_init_node: node 0, pgdat 803742b0, node_mem_map 81000000
[    0.000000]   Normal zone: 64 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 8192 pages, LIFO batch:0
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8128
[    0.000000] Kernel command line:  board=UBNT-BM console=ttyS0,115200 mtdparts=spi0.0:256k(u-boot)ro,64k(u-boot-env)ro,7552k(firmware),256k(cfg)ro,64k(EEPROM)ro rootfstype=squashfs,jffs2 noinitrd
[    0.000000] PID hash table entries: 128 (order: -3, 512 bytes)
[    0.000000] Dentry cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Inode-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 28324K/32768K available (2573K kernel code, 133K rwdata, 540K rodata, 264K init, 193K bss, 4444K reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:51
[    0.000000] Clocks: CPU:390.000MHz, DDR:390.000MHz, AHB:195.000MHz, Ref:5.000MHz
[    0.000000] Calibrating delay loop... 259.27 BogoMIPS (lpj=1296384)
[    0.070000] pid_max: default: 32768 minimum: 301
[    0.070000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.080000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.090000] NET: Registered protocol family 16
[    0.090000] MIPS: machine is Ubiquiti Bullet M
[    0.100000] registering PCI controller with io_map_base unset
[    0.320000] PCI host bridge to bus 0000:00
[    0.330000] pci_bus 0000:00: root bus resource [mem 0x10000000-0x13ffffff]
[    0.330000] pci_bus 0000:00: root bus resource [io  0x0000]
[    0.340000] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.340000] pci 0000:00:00.0: [168c:002a] type 00 class 0x028000
[    0.340000] pci 0000:00:00.0: fixup device configuration
[    0.350000] pci 0000:00:00.0: reg 0x10: [mem 0x10000000-0x1000ffff 64bit]
[    0.350000] pci 0000:00:00.0: supports D1
[    0.350000] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    0.350000] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    0.350000] pci 0000:00:00.0: BAR 0: assigned [mem 0x10000000-0x1000ffff 64bit]
[    0.350000] pci 0000:00:00.0: using irq 40 for pin 1
[    0.360000] Switched to clocksource MIPS
[    0.360000] NET: Registered protocol family 2
[    0.370000] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.370000] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.380000] TCP: Hash tables configured (established 1024 bind 1024)
[    0.390000] TCP: reno registered
[    0.390000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.400000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.400000] NET: Registered protocol family 1
[    0.410000] PCI: CLS 0 bytes, default 32
[    0.410000] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.440000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.450000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.460000] msgmni has been set to 55
[    0.460000] io scheduler noop registered
[    0.470000] io scheduler deadline registered (default)
[    0.470000] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.480000] console [ttyS0] disabled
[    0.510000] serial8250.0: ttyS0 at MMIO 0x18020000 (irq = 11, base_baud = 12187500) is a 16550A
[    0.510000] console [ttyS0] enabled
[    0.520000] bootconsole [early0] disabled
[    0.530000] m25p80 spi0.0: found s25fl064k, expected m25p80
[    0.540000] m25p80 spi0.0: s25fl064k (8192 Kbytes)
[    0.540000] 5 cmdlinepart partitions found on MTD device spi0.0
[    0.550000] Creating 5 MTD partitions on "spi0.0":
[    0.550000] 0x000000000000-0x000000040000 : "u-boot"
[    0.560000] 0x000000040000-0x000000050000 : "u-boot-env"
[    0.570000] 0x000000050000-0x0000007b0000 : "firmware"
[    0.590000] 2 uimage-fw partitions found on MTD device firmware
[    0.590000] 0x000000050000-0x00000016ea0a : "kernel"
[    0.600000] 0x00000016ea0a-0x0000007b0000 : "rootfs"
[    0.600000] mtd: device 4 (rootfs) set to be root filesystem
[    0.610000] 1 squashfs-split partitions found on MTD device rootfs
[    0.620000] 0x0000003b0000-0x0000007b0000 : "rootfs_data"
[    0.620000] 0x0000007b0000-0x0000007f0000 : "cfg"
[    0.630000] 0x0000007f0000-0x000000800000 : "EEPROM"
[    0.650000] libphy: ag71xx_mdio: probed
[    1.250000] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.1:04 [uid=004dd041, driver=Generic PHY]
[    1.260000] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
[    1.260000] TCP: cubic registered
[    1.270000] NET: Registered protocol family 17
[    1.270000] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
[    1.290000] Bridge firewalling registered
[    1.290000] 8021q: 802.1Q VLAN Support v1.8
[    1.300000] VFS: Mounted root (squashfs filesystem) readonly on device 31:4.
[    1.310000] Freeing unused kernel memory: 264K (8038e000 - 803d0000)
[    2.780000] init: Console is alive
[    2.790000] init: - watchdog -
[    4.890000] init: - preinit -
[    5.640000] random: procd urandom read with 8 bits of entropy available
[    8.470000] eth0: link up (100Mbps/Full duplex)
[    9.040000] mount_root: jffs2 not ready yet, using temporary tmpfs overlay
[    9.430000] eth0: link down
[    9.440000] procd: - early -
[    9.440000] procd: - watchdog -
[   10.160000] procd: - ubus -
[   11.170000] procd: - init -
[   12.530000] NET: Registered protocol family 10
[   12.540000] tun: Universal TUN/TAP device driver, 1.6
[   12.550000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[   12.560000] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   12.590000] batman_adv: B.A.T.M.A.N. advanced 2016.0 (compatibility version 15) loaded
[   12.610000] u32 classifier
[   12.610000]     input device check on
[   12.620000]     Actions configured
[   12.620000] Mirror/redirect action on
[   12.670000] Loading modules backported from Linux version v4.4-rc5-1913-gc8fdf68
[   12.680000] Backport generated by backports.git backports-20151218-0-g2f58d9d
[   12.730000] Ebtables v2.0 registered
[   12.760000] ip_tables: (C) 2000-2006 Netfilter Core Team
[   12.790000] nf_conntrack version 0.5.0 (446 buckets, 1784 max)
[   12.880000] xt_time: kernel timezone is -0000
[   13.110000] PCI: Enabling device 0000:00:00.0 (0000 -> 0002)
[   13.130000] ath: phy0: Ignoring endianness difference in EEPROM magic bytes.
[   13.130000] ath: EEPROM regdomain: 0x0
[   13.130000] ath: EEPROM indicates default country code should be used
[   13.130000] ath: doing EEPROM country->regdmn map search
[   13.130000] ath: country maps to regdmn code: 0x3a
[   13.130000] ath: Country alpha2 being used: US
[   13.130000] ath: Regpair used: 0x3a
[   13.150000] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   13.150000] ieee80211 phy0: Atheros AR9280 Rev:2 mem=0xb0000000, irq=40
[   27.870000] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   27.880000] jffs2_build_filesystem(): unlocking the mtd device... done.
[   27.880000] jffs2_build_filesystem(): erasing all blocks after the end marker... 
[   28.260000] jffs2: Newly-erased block contained word 0x0 at offset 0x00390000
[   28.270000] jffs2: Newly-erased block contained word 0xdeadc0de at offset 0x00380000
[   28.280000] jffs2: Newly-erased block contained word 0xdeadc0de at offset 0x00370000
[   28.290000] jffs2: Newly-erased block contained word 0x314d043e at offset 0x00360000
[   28.320000] jffs2: Newly-erased block contained word 0x1a4bf99a at offset 0x00350000
[   28.330000] jffs2: Newly-erased block contained word 0x8a98408d at offset 0x00340000
[   28.340000] jffs2: Newly-erased block contained word 0x80f2db9f at offset 0x00330000
[   28.350000] jffs2: Newly-erased block contained word 0x111f9ee6 at offset 0x00320000
[   28.380000] jffs2: Newly-erased block contained word 0xe4a493be at offset 0x00310000
[   28.390000] jffs2: Newly-erased block contained word 0x9405c066 at offset 0x00300000
[   28.400000] jffs2: Newly-erased block contained word 0xe643892d at offset 0x002f0000
[   28.410000] jffs2: Newly-erased block contained word 0xb07d440d at offset 0x002e0000
[   28.440000] jffs2: Newly-erased block contained word 0x40cfe119 at offset 0x002d0000
[   28.450000] jffs2: Newly-erased block contained word 0x1a4f2dfc at offset 0x002c0000
[   28.460000] jffs2: Newly-erased block contained word 0x923eced at offset 0x002b0000
[   28.470000] jffs2: Newly-erased block contained word 0x27e934f3 at offset 0x002a0000
[   28.500000] jffs2: Newly-erased block contained word 0xec0dfbe9 at offset 0x00290000
[   28.510000] jffs2: Newly-erased block contained word 0xc2fd48d6 at offset 0x00280000
[   28.520000] jffs2: Newly-erased block contained word 0xae40bf1d at offset 0x00270000
[   28.530000] jffs2: Newly-erased block contained word 0x1a6303c8 at offset 0x00260000
[   28.560000] jffs2: Newly-erased block contained word 0x88889fa8 at offset 0x00250000
[   28.570000] jffs2: Newly-erased block contained word 0x1ff26692 at offset 0x00240000
[   28.580000] jffs2: Newly-erased block contained word 0x345f4653 at offset 0x00230000
[   28.590000] jffs2: Newly-erased block contained word 0x3ef0ecfa at offset 0x00220000
[   28.620000] jffs2: Newly-erased block contained word 0x63e74dd9 at offset 0x00210000
[   28.630000] jffs2: Newly-erased block contained word 0xcd9d75fd at offset 0x00200000
[   28.640000] jffs2: Newly-erased block contained word 0x9945872c at offset 0x001f0000
[   28.650000] jffs2: Newly-erased block contained word 0x19362795 at offset 0x001e0000
[   28.680000] jffs2: Newly-erased block contained word 0xe10d502a at offset 0x001d0000
[   28.690000] jffs2: Newly-erased block contained word 0x4504e62c at offset 0x001c0000
[   28.700000] jffs2: Newly-erased block contained word 0xd92abfed at offset 0x001b0000
[   28.710000] jffs2: Newly-erased block contained word 0x60c5250 at offset 0x001a0000
[   28.750000] jffs2: Newly-erased block contained word 0x5fb85ee8 at offset 0x00190000
[   28.760000] jffs2: Newly-erased block contained word 0x5d5958db at offset 0x00180000
[   28.770000] jffs2: Newly-erased block contained word 0x5ab6eb47 at offset 0x00170000
[   28.780000] jffs2: Newly-erased block contained word 0xdb9ea56e at offset 0x00160000
[   28.790000] jffs2: Newly-erased block contained word 0xbb513a13 at offset 0x00150000
[   28.820000] jffs2: Newly-erased block contained word 0x2e405c72 at offset 0x00140000
[   28.830000] jffs2: Newly-erased block contained word 0x4d03fc3c at offset 0x00130000
[   28.840000] jffs2: Newly-erased block contained word 0x7cc888ac at offset 0x00120000
[   28.850000] jffs2: Newly-erased block contained word 0xd1c3953c at offset 0x00110000
[   28.860000] jffs2: Newly-erased block contained word 0x1f1f7751 at offset 0x00100000
[   28.890000] jffs2: Newly-erased block contained word 0x56f9b7dd at offset 0x000f0000
[   28.900000] jffs2: Newly-erased block contained word 0x8f39521d at offset 0x000e0000
[   28.910000] jffs2: Newly-erased block contained word 0x1ad33f51 at offset 0x000d0000
[   28.920000] jffs2: Newly-erased block contained word 0x2fe9519e at offset 0x000c0000
[   28.930000] jffs2: Newly-erased block contained word 0x88142a65 at offset 0x000b0000
[   28.960000] jffs2: Newly-erased block contained word 0xccbe88ad at offset 0x000a0000
[   28.970000] jffs2: Newly-erased block contained word 0x59b24a94 at offset 0x00090000
[   28.980000] jffs2: Newly-erased block contained word 0x5ceff193 at offset 0x00080000
[   28.990000] jffs2: Newly-erased block contained word 0x47222d48 at offset 0x00070000
[   29.000000] jffs2: Newly-erased block contained word 0xdeb83c1d at offset 0x00060000
[   29.030000] jffs2: Newly-erased block contained word 0x23020c34 at offset 0x00050000
[   29.040000] jffs2: Newly-erased block contained word 0x2023d8fa at offset 0x00040000
[   29.050000] jffs2: Newly-erased block contained word 0x9ca5caaa at offset 0x00030000
[   29.060000] jffs2: Newly-erased block contained word 0xff8e3867 at offset 0x00020000
[   29.070000] jffs2: Newly-erased block contained word 0xd7315ec6 at offset 0x00010000
[   29.100000] jffs2: Newly-erased block contained word 0xdeadc0de at offset 0x00000000
[   29.100000] done.
[   29.110000] jffs2: notice: (1072) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[   33.030000] device eth0 entered promiscuous mode
[   33.030000] IPv6: ADDRCONF(NETDEV_UP): br-setup: link is not ready
[   34.130000] eth0: link up (100Mbps/Full duplex)
[   34.130000] br-setup: port 1(eth0) entered forwarding state
[   34.140000] br-setup: port 1(eth0) entered forwarding state
[   34.160000] IPv6: ADDRCONF(NETDEV_CHANGE): br-setup: link becomes ready
[   36.140000] br-setup: port 1(eth0) entered forwarding state
[   68.290000] random: nonblocking pool is initialized
`

**Comment by NeoRaider** [comment]
@FabianCernota, den Kernel-Tree hast du aber gecleaned nach dem git-pull/make-update, oder?

**Comment by FabianCernota** [comment]
Jap git pull , make clean, make update

**Comment by NeoRaider** [comment]
Hmm, seltsam. Dann komme ich ohne Testgerät nicht weiter.

**Comment by FabianCernota** [comment]
Ich lass dir eine zukommen alles weitere per Mail dann :)

**Comment by MPW1412** [comment]
Scheinbar kann man das Problem umgehen, wenn man erst AirOS auf eine alte Version verringert. 

Querverlinkung: https://forum.freifunk-muensterland.de/t/picostationm2-v2016-1-1-0-0/884/8?u=mpw

**Comment by NeoRaider** [comment]
@MPW1412, ja, das ist allgemein bekannt. Es geht in diesem Report darum, diesen Workaround in Zukunft vermeiden zu können.

**Comment by MPW1412** [comment]
Also ist das primäre Problem gar nicht der neue Flash-Chip, sondern irgendwas im Bootloader, was den Flash nicht korrekt entsperrt.

**Comment by NeoRaider** [comment]
Es ist eigentlich nicht die Aufgabe des Bootloaders... der Kernel sollte das schon selbst können.

**Comment by SilversurferCH** [comment]
Wenn du noch beim Testen Hilfe brauchst, hab hier auch noch eine betroffen Pico liegen.

**Comment by LeSpocky** [comment]
Bestätige Winbond 25Q64FVIG auf PicoStation M2 XM.

**Comment by A-Kasper** [comment]
Passiert der Fehler auch wenn ihr vorher nen downgrade gemacht habt?
Ich hatte das auch erst. Habe dann per tftp zurück auf stock und von da
auf 5.5 und dann auf gluon. dann ging es.

**Comment by NeoRaider** [comment]
@A-Kasper, nein, der alte Bootloader entsperrt den Flash. Das Problem tritt nur mit dem neuen auf.

**Comment by txt-file** [comment]
Am 11. April kam eine neue Version von 5.6.x raus. Das Changelog klingt so, als wäre dort dieser Bug behoben.
Hat jemand Zeit und Gerät um das einmal zu testen?

https://www.ubnt.com/downloads/firmwares/XN-fw/v5.6.4/changelog.txt

**Comment by NeoRaider** [comment]
@txt-file, das wäre wieder nur ein Workaround, der echte Fix muss im Kernel passieren. @FabianCernota, wie sieht's mit dem Testgerät aus?

**Comment by SilversurferCH** [comment]
Ich habe gerade mal mit der 5.6.4 getestet. Leider gleiches Ergebnis. Gluon war 2016.1.3.

**Comment by LeSpocky** [comment]
Erfolgreich getestet mit gluon v2016.1.5: https://map.md.freifunk.net/#!v:m;n:68725142b11b :beers:

**Comment by viisauksena** [comment]
ich habe mit unserem letzten update alle betroffenen cpe210 v1 und v1.1 abgeschossen .. symptom : Geräte tot, leuchtet nur noch power - meist nur config mode
der upgrade passierte von 
v2016.1.5.u / gluon-v2016.1-183-gfb8c7a8
auf
v2016.1.6 / gluon-v2016.1-295-gc673356
mit den 841 egal welcher art gibt es keine Probleme mit der FW ... ich wüsst nicht wie ich da noch mehr Info liefern könnt.. ich Versuch nochmal ganz neue FW zu bauen und die zu flashen

**Comment by NeoRaider** [comment]
@viisauksena 

1. Was hat das mit diesem Ticket zu tun??? #796 war das einzige CPE-spezifische Ticket in letzter Zeit... und wenn du dir unsicher bist, mach lieber ein neues Ticket auf.
2. Was sind das für Versionsnummern? v2016.1.6 kommt aus dem Stable-Branch, v2016.1-295 muss ein Master-Commit sein (im Stable-Branch gab es seit v2016.1 nur 83 Commits, keine 295)
3. Möglicherweise kein `make clean` nach dem `make update` ausgeführt? Das würde das Problem in diesem Fall erklären.

**Comment by viisauksena** [comment]
das sind die bezeichnungen aus dem meshviewer, der erste Teil ist selbstgewählt und der letzte kommt aus dem Masterbranch , korreckt - da die beiden Plattformen ähnlich (so dachte ich - und das oben auch erwähnt wird)  sind hab ich das mal so aufgemacht. 
ich dachte ich probier noch ein paar Dinge bevor ich Alarm schlage

**Comment by PolynomialDivision** [comment]
Habt ihr zufällig ähnliche Probleme mit nem 5.4 Kernel auf AR9342? Man findet diesen issue über: https://dev.archive.openwrt.org/ticket/20982
