### ISSUE TITLE
sort gateways alphabetically

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#698]
The order of gateways in a community in the status page is not sorted:

![](http://i.stack.imgur.com/35tST.png)

It would be nice to have them sorted alphabetically ;)

**Comment by NeoRaider** [comment]
Indeed, this should be fixed.

**Comment by poldy79** [comment]
2016-03-26 0:10 GMT+01:00 Matthias Schiffer <notifications@github.com>:

> Indeed, this should be fixed.
>

+1

In our site.conf, the GWs are sorted. They are not sorted in
/etc/config/fastd any more- perhaps that is the source of not beeing sorted.

Regards
Leonard

**Comment by NeoRaider** [comment]
No, the ordering must be done in the frontend, JSON objects have undefined ordering.
