### ISSUE TITLE
Updating node location during normal operation

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#71]
Yesterday, I've been talking with other freifunkers about Gluon's new features. I've concluded, that not being able to update a nodes' location remotely is  a huge problem. This is mainly due to the actual workflow of setting up nodes being different from what we anticipated.
# Workflow mismatch

Our anticipated workflow looks something like this:
1. User wants to setup a new node,
2. thinks exactly about where to put it and retrieves WGS84 coordinates for that location,
3. installs firmware,
4. visits configmode,
5. sets location,
6. places at said location,
7. submits public key to community.

However, the more common workflow seems to be:
1. Users wants to setup a new node,
2. installs firmware,
3. visits configmode,
4. submits public key,
5. thinks about where to put it,
6. places node at desired location.

Essentially, the user does not know where the node will be located when entering configmode and forcing her to retrieve it at that point is a burden. This is also a problem when moving a node to a new location.
# Proposed solution

We'll add a simple codeword[1] the use can set in configmode. This codeword will allow changing a nodes location on the statuspage. It won't be the root password nor will it allow logging in. It's just a shared secret to authenticate changing longitude and latitude of the node.

**It will not allow changing whether the location is shared or not.** This will prevent attackers from making a hidden node visible. Should a user desire to change the visibility of her node she must go through configmode again.

**It will not allow changing the hostname.** I consider changing a nodes hostname potentially harmful if done by an attacker. Again, configmode is required.

**It will not allow changing the codeword itself.** Thus, an attacker won't be able to lock a node to a location after gaining knowledge of the codeword. Again, configmode enforced.

**If no codeword is set, changing the location will not be possible at all.** In this case the user will have to visit configmode again in order to update the location. Just as it is now. We should encourage this for "important" nodes.

In my opinion, these three properties will prevent attackers from harming a node badly and thus enabling us to encourage re-use of the codeword for all nodes of a user. An attacker sniffing traffic in the mesh could get much more valuable information than the codeword and, should he desire to mess with the map, inject or manipulate alfred packages directly. Effectively, the codeword-approach will be (maybe just little) more secure than our current wiki approach (which anyone can edit). Still, I do not like sending the codeword in plaintext over the mesh but neither would I want to restrict it to the next-node address (some nodes on roofs might not be reachable through next-node or there may be too many nodes close together so the user can not select the desired node) and I think we should work on solving this issue in later Gluon releases.

Thanks for reading, and thanks to Linus and everyone else I've talked to regarding this issue for their input! Please let me know what you think about this in the comments.

(Did I mention the statuspage would be able to show a map so the user can place her node without knowing about WGS84?)

[1]: like a password but without any security requirements. I'd consider "foo" reasonable.

**Comment by rubo77** [comment]
Any solutions by now? Did someone implement something like this locally already?

**Comment by tcatm** [comment]
hexa came up with the idea of using a time-based OTP (i.e. RFC 6238) for authentication. I kind of like that approach. For this to work the user would be shown a QR code (+string) for setting up the OTP "Client" (i.e. a smartphone). The user must be able to reset the token (or disable the feature completely).

**Comment by viisauksena** [comment]
this is far from the convinient idea of easy setting geo with status page (with whatsoever auth mode) .. but if you have ssh connection and you are not frightend by terminals - here are some helpfull minisripts like **lat lon alt location geoguess** https://github.com/viisauksena/gluon-banner/tree/master/files/usr/bin/ you could add by default to your nodes or your firmware

**Comment by rubo77** [comment]
What about a big hint

**Be sure you wrote down the geo coordinates before you continue**

that will be shown only once at the first call of the config mode after a fresh install?

**Comment by CodeFetch** [comment]
@blocktrron @mweinelt @rotanid Can we close this?

NeoRaider said
> And I don't see a problem with users going having to go back to the config mode once when they install a node somewhere.

I think this is true... Going back to config mode is feasible. No overly complicated solution is needed here and this was not implemented in 5 years. So this possibly won't ever be finished...
