### ISSUE TITLE
Reduce count of flash writes during upgrade

### ISSUE THREAD

**Issue by kpanic23** [freifunk-gluon/gluon#714]
If my understanding of the autoupdate process is correct, on the reboot after an update, all the update scripts in /lib/gluon/upgrade are executed. It seems to me, that in most of them at least one "uci commit" is done. Would'nt it be possible to reduce the amount of flash writes dramatically by committing only once , like, in a last file like /lib/gluon/upgrade/zzz-commit?
I guess this could increase the flash-chip's lifetime. We already had some nodes with worn-out flash...

**Comment by NeoRaider** [comment]
I think this makes sense, I'll try this change out.
