### ISSUE TITLE
Add support for TL-WR841N(D) Revision 11

### ISSUE THREAD

**Issue by dkessel** [freifunk-gluon/gluon#721]
Retailers are starting to sell revision 11(.1)  of the TL-WR841N(D).

It would be good to have support for this in gluon. I found this at openwrt - DD trunk seems to have support for it:
https://wiki.openwrt.org/toh/start?dataflt%5BModel*~%5D=TL-WR841N%28D%29

**Comment by NeoRaider** [comment]
OpenWrt currently supports the US version of the v11 only (TP-Link started separating firmwares between US and EU because of the new regulations). I'll get an EU test device soon, so we can add support.

**Comment by belzebub40k** [comment]
Looks like all changes TP-Link made where implemented in the firmware and no significant changes where made in OpenWrt to add the support. Hopefully this is the same for the EU version.

http://git.openwrt.org/?p=openwrt.git;a=commitdiff;h=d71d620ac7d5a496bc7be16f9f1046d9c6133d14

**Comment by Ranlvor** [comment]
I did an untested backport of the v11-Changes. https://github.com/Ranlvor/gluon/tree/wr841n-v11

Will pull-request as soon as I got feedback of an owner of a v11.

**Comment by mmalte** [comment]
@neoraider we've got the first report of an 804v11 device today. 

Did you receive yours or should we ask for the device for testing purposes?

**Comment by NeoRaider** [comment]
I don't have a 841 v11, but as there's already OpenWrt support, I'll just backport it. As I've found out, the 841 v11 does not yet have region-specific versions yet.

**Comment by NeoRaider** [comment]
Added as BROKEN, please test.

**Comment by mmalte** [comment]
I've got reports that even the 841v10 firmware is working on a 841v11

**Comment by NeoRaider** [comment]
@mmalte, well, the firmwares are exactly identical, with one exception: the firmware header contains a different hardware ID, so the 841v10 firmware can't be flashed on a 841v11. Of course, first flashing OpenWrt and then flashing a "wrong" Gluon image with -F is possible and will work (but will show the device as v10).

**Comment by SilversurferCH** [comment]
Hi just tested Düsseldorf firmware (http://images.ffdus.de/brokenl2tp/factory/gluon-ffdus-2016042602-exp-tp-link-tl-wr841n-nd-v11.bin). Upgrading the firmware went well. Even Configuring is working. One thing i noticed: The Power-LED is no more glowing. Actually compiling for Münster so we can test mesh.

**Comment by mmalte** [comment]
I've cherry picked #8f6cc2d on top of v2016.1.4 works perfectly.

**Comment by Adorfer** [comment]
I can confirm
https://karte.ffdus.de/#!v:m;n:a42bb0a9ee88 seems to work fine. 
https://map.eulenfunk.de/stats/dashboard/db/node-byid?var-nodeid=a42bb0a9ee88

**Comment by mraerino** [comment]
TL-WR841N v11-EU seems not to work with gluon 2016.2.2
> Error code: 18005
> Upgrade unsuccessfully because the version of the upgraded file was incorrect. Please check the file name.

Is there something happening for this?

OpenWRT seems to somehow have support for this: https://forum.openwrt.org/viewtopic.php?pid=338779#p338779
Seems like there is only some new signature added: https://forum.openwrt.org/viewtopic.php?pid=338630#p338630

**Comment by NeoRaider** [comment]
@mraerino You need to set the correct GLUON_REGION (`GLUON_REGION := eu` in *site.mk*) when building the images.
