### ISSUE TITLE
Preparing Gluon for Babel

### ISSUE THREAD

**Issue by tcatm** [freifunk-gluon/gluon#724]
Basically, fix all implicit deps on batman-adv in various packages:
- [x] `gluon-radvd` refers to `bat0` here https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-radvd/files/lib/gluon/ebtables/300-radv-input-output
- [x] `gluon-radvd` must run on `local-node` instead of `br-client` (for the next-node-mac to become the gateway)
- [x] `uradvd` `--default-lifetime` setzen (z.B. auf 900)

the following packages also do contain references to "bat"
- [x] gluon-mesh-vpn-fastd (refactoring necessary, split into vpn-part, batman-part, babel-part)
- [ ] gluon-respondd (allow respondd to realize that interfaces changed like uradvd, remove hotplug script)
- [x] gluon-status-page
- [x] gluon-status-page-api
- [x] gluon-mesh-vpn should add the mesh-vpn interface to /lib/gluon/core/mesh_interfaces, one interface per line.

**Comment by christf** [comment]
the following packages also do contain references to "bat"

gluon-mesh-vpn-fastd
gluon-respondd (hotplug-script)
gluon-status-page
gluon-status-page-api

**Comment by christf** [comment]
gluon-mesh-vpn should add the mesh-vpn interface to /lib/gluon/core/dynamic/mesh_interfaces, one interface per line.

**Comment by tcatm** [comment]
- [ ] network.local_node_route6 must be removed

**Comment by christf** [comment]
most of this is done in #934 
the following is still open
- statuspage / statuspage-api
- gluon-respondd

**Comment by christf** [comment]
gluon- respondd is mesh-protocol agnostic with #946

**Comment by christf** [comment]
I do not think we need  respondd to notice if interfaces change for a new mesh protocol. Sure, it should be done but is not necessary for babel.

**Comment by christf** [comment]
the babel-speciic parts have been implemented. Creating a new issue for respondd
