### ISSUE TITLE
Multithreadded compiling fails at high probability

### ISSUE THREAD

**Issue by MPW1412** [freifunk-gluon/gluon#733]
Hello,

I know, that many failures of compiling gluon are due to failed downloads. But I think that there are race conditions, too. As of my observations, the compiling process fails much more often, the more cores are used.

So I started collecting intel on this issue and I'm uploading two log files here now. I used my build script and enabled debugging, which is basically the "set -x" command in bash: https://github.com/FreiFunkMuenster/tools/blob/b66d89013feb6aff49b6c1ad51d440b2c1eadf3b/build_all.sh (Linked to fixed commit as work is in progress.)

Both tries failed because of uncompleted downloads.

[buildlogs.zip](https://github.com/freifunk-gluon/gluon/files/233182/buildlogs.zip)

Regards,
Matthias

**Comment by christf** [comment]
we did discuss on irc to:
- [ ] cache downloads
- [ ] use more quotes
- [ ] get rid of some pipes
- [ ] order of builds (build all site.confs for one target first, then change target)

likely using a downlaod-cache will resolve your issues.

**Comment by NeoRaider** [comment]
I think this is actually a race condition, caused by an incomplete backport. I'll fix this.

**Comment by MPW1412** [comment]
Thanks for the quick fix. I'll do a dirclean and try to build master later.

**Comment by MPW1412** [comment]
Works like a charm, just compiled in a brand new build environment with eight cores and it just worked.
