### ISSUE TITLE
reconsider PR768 after switch to LEDE

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/gluon#769]
https://github.com/freifunk-gluon/gluon/pull/768

using PROVIDES in packages is the right choice but the build breaks using openwrt. 
After the dependency handling is fixed, this pr should be reconsidered.
also gluon-mesh-babel should provide gluon-mesh-provider

**Comment by rotanid** [comment]
the switch to LEDE happened, is this still a thing? if not, please close the issue yourself.

**Comment by NeoRaider** [comment]
PROVIDES still doesn't work well enough in LEDE 17.01. I don't think it makes sense to keep this ticket open any longer...
