### ISSUE TITLE
support for TP-Link TL-WA801NDv3

### ISSUE THREAD

**Issue by rotanid** [freifunk-gluon/gluon#800]
might be good to have support for the TP-Link TL-WA801NDv3
it's cheaper (and easier) than buying a 841 and doing PoE separately, if i'm not mistaken

**Comment by rotanid** [comment]
upstream support was introduced in february:
https://dev.openwrt.org/changeset/48705

**Comment by NeoRaider** [comment]
The ethernet port configuration is a bit broken on the TL-WA801ND v3 (dead eth0, single port as eth1). I'd like to fix this first (together with the DIR-505, which has the same issue) before adding this device.
