### ISSUE TITLE
cat /proc/cpuinfo shows wr841n v10 as v9

### ISSUE THREAD

**Issue by MPW1412** [freifunk-gluon/gluon#805]
Hello,

I just noticed, that 

`cat /proc/cpuinfo`

shows a wr841n v10 as v9:

![bildschirmfoto vom 2016-06-22 12 04 47](https://cloud.githubusercontent.com/assets/1448950/16262857/c28eee42-3871-11e6-8709-9b0f90268689.png)

The MeshViewer shows the correct version.

Regards,
Matthias

**Comment by NeoRaider** [comment]
Completely normal. cpuinfo shows the board name, and v9 and v10 use the same board design.
