### ISSUE TITLE
Disable CONFIG_KERNEL_KALLSYMS?

### ISSUE THREAD

**Issue by T-X** [freifunk-gluon/gluon#807]
Since we are a little short on RAM for 32MB devices, I was wondering whether we should remove the kernel symbol table from the images by unsetting CONFIG_KERNEL_KALLSYMS. Not 100% sure, but I think this had actually been the default in OpenWRT some time ago.

At least for the uncompressed vmlinux for the ar71xx-generic target I'm getting a size reduction from 3836356 bytes down to 3606900. For kernel modules there should be a similar reduction in size.

The downside of all this are less comfortable call traces, of course.

**Comment by NeoRaider** [comment]
I think proper backtraces are too valuable to disable the kernel symbols.

In any case, the uncompressed numbers aren't of much value, do you have numbers for LZMA-compressed kernels?

**Comment by NeoRaider** [comment]
As written before, I don't think this is a good place to shave off some bytes.
