### ISSUE TITLE
841N v11 PowerLED not working

### ISSUE THREAD

**Issue by RubenKelevra** [freifunk-gluon/gluon#812]
We use a forked version of your 2016.1.x branch on the state of four weeks ago. I've currently testing the 841N v11 support and just learned that the PowerLED seems to be not working at all. While powering on, like all LEDs are lit up, the PowerLED does this as well, but thereafter the PowerLED is off.

**Comment by NeoRaider** [comment]
I've backported the patch for LED support to the Gluon master, but I don't have a device to test it. If you can check that this is working correctly, I'll also port it to v2016.1.x.

**Comment by RubenKelevra** [comment]
Thanks, gonna check this in the next days for you. :)
