### ISSUE TITLE
Disable fastd whenever mesh on wan gets enabled

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#818]
I see no scenario where fastd should stay enabled

**Comment by jplitza** [comment]
Why wouldn't you have a small subnet where multiple nodes mesh via cable and simultaneously a router offers one of the nodes internet access?

**Comment by NeoRaider** [comment]
The normal usecase is having multiple nodes with mesh-on-WAN in a home network, and having one of them use the mesh VPN.

**Comment by rubo77** [comment]
I thought of automatically disabling the fastd-option if it is enabled, because what I just had was this problem:

my wr4900 was connected to the interne with fastd enabled and Mash-on-LAN

my 1043 had Mesh-on-WAN enabled and was connected via kable to the 4900.

Since the 1043 had also fastd enabled it created another fastd tunnel through the 4900 - a tunnel inside the tunnel.

I see no useful usecase where this should be possible?

**Comment by jplitza** [comment]
Yes, VPN tunnels should never be established through Freifunk. But a more appropriate countermeasure would be to block forwarding of VPN traffic on the nodes or on the servers.

**Comment by rubo77** [comment]
that would be a new issue? "block forwarding of VPN traffic on the nodes"

**Comment by NeoRaider** [comment]
Doing this on the VPN servers is much more appropriate (and simpler).

Also, mesh-on-lan and mesh-on-wan are expert mode features. Users are expected to know what they are doing when using these features; "magically" changing other, mostly unrelated settings is not acceptable for the expert mode.
