### ISSUE TITLE
Autoupdater connects to IPv4 mirror

### ISSUE THREAD

**Issue by p-vitt** [freifunk-gluon/gluon#822]
The documentation says:

> All configured mirrors must be reachable from the nodes via IPv6.

I have a node with an experimental 2016.1.5 that connects to an IPv4 address to request the manifest. Is this a bug in software or documentation?

**Comment by NeoRaider** [comment]
The documentation is a bit unclear here (and Gluon's separation of mesh and uplink network imperfect). At the moment, we highly recommend to use a liteteral IPv6 address or a hostname without A record (only AAAA) as the mirror address in the site.conf.

We'll improve the separation in a future Gluon version, so processes running in mesh context can't access don't try using the uplink connection.
