### ISSUE TITLE
Order of firmware mirrors

### ISSUE THREAD

**Issue by p-vitt** [freifunk-gluon/gluon#823]
If there are more than one firmware mirrors configured, the order of requesting new software is, at least to me, counter intuitive, as the last mirror is asked first. I think, this should be mentioned somewhere in the documentation, as long as it is reliable (what I don't know and, thus, didn't just open a pull request). 
Therefore the question is: is this request order reliable?

**Comment by NeoRaider** [comment]
The mirrors are queried in random order.
