### ISSUE TITLE
Probleme beim Bauen von Unify AP AC Pro Images

### ISSUE THREAD

**Issue by RubenKelevra** [freifunk-gluon/gluon#830]
Ich wollte gern aus dem Master Images für die Unify AP AC Pros bauen, leider wird nur ein Image für "Sysupgrade" generiert. Im Ordner Factory liegen keine Images für diesen Typ Hardware.

Ich hab via TFTP probiert auf einen das Sysupgrade-Image zu spielen, leider frisst er diese nicht.

Ist das ein noch ein bekanntes Kompabilitätsproblem oder liegt hier noch ein Fehler im Buildscript vor? :)

**Comment by NeoRaider** [comment]
Die Unifi AP AC Pro haben im "regulären" Updater eine Signaturprüfung, daher können wir keine sinnvollen Factory-Images erzeugen.

Die Stock-Firmware enthält allerdings auch das Tool mtd, mit diesem kann das sysupgrade-Image direkt in den Flash geschrieben werden (siehe https://wiki.openwrt.org/toh/ubiquiti/unifiac ).

**Comment by RubenKelevra** [comment]
Bei den bisherigen Unifys konnte man die mit dem erzeugten Image via TFTP flashen, prüft TFTP diese Signatur auch? Oder reicht da vielleicht doch ein Magic-Byte? :)

**Comment by NeoRaider** [comment]
Wenn ich mich richtig erinnere, habe ich auch im Dump vom Uboot Strings gefunden, die auf eine RSA-Signaturprüfung hindeuten. Ist allerdings eine Weile her, dass ich mir das angeschaut habe, ich könnte mich irren.

Das neue Factory-Format ist etwas anders als das alte (darüber hinaus, dass es jetzt eine Signatur am Ende gibt), und da die Sysupgrade-Images benutzbar sind, werde ich keine Zeit in die Analyse des neuen Formats stecken.

**Comment by RubenKelevra** [comment]
Ich seh grade, das OpenWRT-Wiki gibt eine Anleitung für TFTP, können wir nicht einfach das OpenWRT-Layout benutzen, was offenbar ja funktioniert? :) 

Oder übersehe ich etwas?

![img_8319](https://cloud.githubusercontent.com/assets/614929/17246709/18369b68-558e-11e6-9234-9e347cefa1a4.PNG)

**Comment by NeoRaider** [comment]
@RubenKelevra, die Anleitung ist für die UAP Pro, nicht den UAP AC Pro.

**Comment by RubenKelevra** [comment]
Sorry. Mehr Kaffee. ;)

**Comment by RubenKelevra** [comment]
Denke das Problem ist gelöst, zwei Geräte laufen super stabil bei uns mit der 2016.1.x mit backportiertem Patch :)

Bei Interesse:

https://github.com/VfN-NRW/gluon-firmware-builder/blob/master/gluon08-repo-patches/device-support/0001-add-support-for-unifi-ac-pro-lite.patch

Danke & Gruß

Ruben
