### ISSUE TITLE
D-Link DIR 860L: Enabling private wifi breaks 5Ghz wifi

### ISSUE THREAD

**Issue by codedust** [freifunk-gluon/gluon#831]
When enabling the private wifi option, the 5Ghz channels are not shown any more in `iwinfo` and are in fact down. All 2 Ghz channels (including the private wifi) are working as expected.

When disabling the private wifi option, both 5 Ghz and 2 Ghz channels are up.

**Comment by NeoRaider** [comment]
Thanks for the report, I'll fix this.

**Comment by NeoRaider** [comment]
Please check if this is fixed with b241373640e570302dc13c18194479ea88fa8d89.

**Comment by mweinelt** [comment]
@codedust try 0.9.0-20160728 (will be built tonight) or later.

**Comment by codedust** [comment]
Thank you very much! This resolved the issue!
