### ISSUE TITLE
MAC address assignment incompatible with Bridge Loop Avoidance

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#834]
Causes

    br-client: received packet on bat0 with own address as source address

as BLA uses packets with batman-adv's primary address as source.

**Comment by RubenKelevra** [comment]
In case you got a look or no loop on the network?

**Comment by NeoRaider** [comment]
@RubenKelevra, already occurs with a single isolated node.

**Comment by Byggvir** [comment]
This kern.warn is only on our nodes generated after 22nd Jul. The 15th April image is running fine. It also occurs on single nodes without neighbors.

**Comment by stweil** [comment]
I see `br-client: received packet on bat0 with own address as source address` on different router hardware with recent firmware. Is that a critical error? Should it be reported in a new issue?
