### ISSUE TITLE
restart von fastd wirft einen Fehler

### ISSUE THREAD

**Issue by RubenKelevra** [freifunk-gluon/gluon#846]
Hallo zusammen,

beim Aufruf von `/etc/init.d/fastd restart` wirft mein Node folgenden Logeintrag:

`daemon.notice netifd: mesh_vpn (5992): ./batadv.sh: eval: line 1: can't create /sys/class/net/mesh-vpn/batman_adv/mesh_iface: nonexistent directory
`

Da läuft 2016.1.x drauf.

Kann das einen Fehlerfall verursachen oder ist der Logeintrag zu ignorieren?

**Comment by jplitza** [comment]
Kann ignoriert werden. Siehe #820.
