### ISSUE TITLE
autoupdater fails to compare versions correctly

### ISSUE THREAD

**Issue by neocturne** [freifunk-gluon/gluon#87]
The autoupdater is using `sort -n` to compare version strings, but `-n` works for the first number of a string only, so the updater things that `0.3.99` is newer than `0.3.101`.

Proposed solution: use `opkg compare-versions` instead, as it was used for a similar usecase in `gluon-core` (removed in  freifunk-gluon/packages@13f99f1d8c8aa55061deaa0ac34cee0b92cb550f).

**Comment by rubo77** [comment]
Is this still fixed? We plan to update from `0.7.1` to `0.16.1` to include the gluon versioning but still stay on `0.x`

So would this work?

**Comment by A-Kasper** [comment]
Am 14.02.2016 um 10:24 schrieb Ruben Barkow:
> Is this still fixed? We plan to update from |0.7.1| to |0.16.1| to
> include the gluon versioning but still stay on |0.x|
> 
> So would this work?

No. The string is compared bytewise. 7 is bigger than 1. You would have
to make the string "higher".

As workaround you may add a V or something V0.16.1

**Comment by NeoRaider** [comment]
@rubo77, don't comment on old issues. This is fixed and does work fine. 16 is greater than 7.
