### ISSUE TITLE
Add support for D-Link DIR615 Rev. D1

### ISSUE THREAD

**Issue by ghost** [freifunk-gluon/gluon#891]
OpenWRT supports the D1 version, would it be possible to add support for it in Gluon too?
Support has been added in Chaos Calmer 15.05.1.

https://wiki.openwrt.org/toh/hwdata/d-link/d-link_dir-615_d1

**Comment by NeoRaider** [comment]
The DIR-615 D1 is based on the Ralink RT305x SoC. It is not properly supported at the moment (the target is marked as BROKEN), but will hopefully get proper support in the future. In any case, it won't support AP+IBSS operation, so meshing will only work over 11s.

**Comment by TheTaques** [comment]
Ahh OK, thanks for looking into it.

**Comment by ambassador86** [comment]
Hello @NeoRaider, this issue can be closed. The support has been added in #1274.

**Comment by rotanid** [comment]
@ambassador86 thanks for the heads-up. closing.
