### ISSUE TITLE
branch for 2016.2

### ISSUE THREAD

**Issue by fragstone** [freifunk-gluon/gluon#892]
Hello,

its actual not a branch choisable for 2016.2 can you create them?

**Comment by rotanid** [comment]
as soon as we need a branch, we'll create one.
at the moment, master-branch is sufficient, as it doesn't contain anything else besides 2016.2

**Comment by rubo77** [comment]
And there is the tag: https://github.com/freifunk-gluon/gluon/releases/tag/v2016.2
