### ISSUE TITLE
Add support for TP-Link  TL-WA7210N

### ISSUE THREAD

**Issue by J0WI** [freifunk-gluon/gluon#894]
Support for the 5GHz model TP-Link TL-WA7510N has already been added in #681, but the 2.4 GHz model is not yet officially supported.
Support to OpenWRT has been added here: https://dev.openwrt.org/changeset/44526

**Comment by NeoRaider** [comment]
I will add a profile for this device after the conversion from OpenWrt CC to LEDE is finished.
