### ISSUE TITLE
cpe210v1 rssi leds using 12%cpu

### ISSUE THREAD

**Issue by viisauksena** [freifunk-gluon/gluon#897]
(rssileds is the feature which show rx level of ibss0 meshing network on the small leds on the side of cpe210  -  as far as i know)  

i suggest to let rssi leds only run for the first 15 minutes, or some other reasonable time ... so the 12% cpu and 2% Memory is free and available for fastd or other things 

```
Mem: 28276K used, 32520K free, 252K shrd, 2216K buff, 7316K cached
CPU:  20% usr  26% sys   0% nic  16% idle   0% io   0% irq  36% sirq
Load average: 1.86 1.97 1.90 1/51 9861
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 1644     1 root     R     3408   6%  49% /usr/bin/fastd --config - --daemon --
 1751     1 root     R     1216   2%  12% /usr/sbin/rssileds ibss0 40000 1 tp-l
 1606     1 root     R     1532   3%   5% /usr/sbin/hostapd -P /var/run/wifi-ph
```

**Comment by mweinelt** [comment]
Or maybe just let the program update only in intervals, instead of hammering them so much that they flicker.

**Comment by TobleMiner** [comment]
Agreed. But this should be fixed in [openwrt itself](https://github.com/openwrt/openwrt/blob/cabb0c506526fe468e4aa985086e50c440192122/target/linux/ar71xx/base-files/etc/board.d/01_leds#L134) The default value is 40ms (25 refreshes per second) which is really fast. I think that 250 ms (4 refreshes per second) would be much more reasonable. I would suggest reopening this issue on the openwrt repo.

**Comment by viisauksena** [comment]
but this is also installed by default in gluon for cpe210 at least - so limiting rssileds in gluon in whatever-way  also sounds reasonable

**Comment by TobleMiner** [comment]
Sure, gluon should fix this. But it is also "broken" in openwrt. Thus it should be fixed there, too.

**Comment by mweinelt** [comment]
So can someone confirm 250ms to be a good value?

**Comment by viisauksena** [comment]
so we wait until PR in openwrt is acknowledged and than build it in gluon (and whats than with upcoming LEDE) or we need own patch?

**Comment by NeoRaider** [comment]
We'll need a patch in Gluon as well.

@mweinelt, I think it would make sense to change the interval for all devices at once, not just for the CPE210/510.

**Comment by mweinelt** [comment]
So set 200ms for every device that has less than 200ms?

**Comment by NeoRaider** [comment]
Yes. A quick grep shows that all devices use the same interval of 40ms at the moment.

**Comment by viisauksena** [comment]
is there a  place where i can change it once , or do i have to change all the profiles with a patch?
