### ISSUE TITLE
Show Router version and installed gluon version on login

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#901]
At the moment there is only shown the standard OpenWRT Login on the console.

It would be really helpful if the Model verstion and Gluon version would be shown there as well:

    lua -e 'print(require("platform_info").get_board_name())'
    lua -e 'print(require("platform_info").get_model())'
    cat /lib/gluon/gluon-version /lib/gluon/release

**Comment by belzebub40k** [comment]
@rubo77 there is already a ticket #728 to modify the default banner but the implementation is postponed because of @NeoRaider rework of the configuration system.

**Comment by rotanid** [comment]
let's keep only one issue on this, #728 as @belzebub40k already said.
