### ISSUE TITLE
Excluding some packages for a specific model 

### ISSUE THREAD

**Issue by Byggvir** [freifunk-gluon/gluon#904]
Hello,

I build an image with USB support. In the ar71xx-generic target there is a Model TP-LINK TL-MR3020 which has a USB port but not enough memory to support USB and the (new) status page. Even without the status page only some USB packages can be used.

I would like an option to exclude or replace a package (in this case the status page) from the GLUON_SITE_PACKAGES for a specific model.

Maybe there is an option but I didn't found an example or description.

Thanks

**Comment by NeoRaider** [comment]
This can be done using the following site.mk line:

```
GLUON_TLMR3020_SITE_PACKAGES := -gluon-status-page # ... all packages you want to exclude, each prepended with a -
```

Note that this is not officially supported at the moment (which is why it is undocumented) and will change in the next Gluon release (as we're currently rewriting the Gluon build system while switching to LEDE).
