### ISSUE TITLE
Ubiquiti Unifi AC Lite: Problems with eth0 persist

### ISSUE THREAD

**Issue by smoe** [freifunk-gluon/gluon#911]
We found an issue with the 0.6.2 release concerning the AC Lite that was already mentioned on https://github.com/freifunk-gluon/gluon/issues/689 : the wlan works fine, but the ethernet connection fails. Eth0 is seen by the tools and IP number can be assigned, however tcpdump indicated no traffic on the connection at all. In contrast, the latest Lede-image is running flawlessly.
Could that driver of Lede possibly be backported?

Best regards,

Zafer and Steffen

**Comment by rotanid** [comment]
what is the "0.6.2" release?
we need to know which exact gluon version you or your community are using.

**Comment by smoe** [comment]
I checked out tag v2016.2 and the git log's most recent entry says
```
commit 6964d30ff24eef9fc436e97bc909dc4c5e048ad4
Author: Matthias Schiffer <mschiffer@universe-factory.net>
Date:   Wed Sep 21 20:04:57 2016 +0200

    docs, README: change current release to v2016.2
```
Many thanks for looking into this!

**Comment by NeoRaider** [comment]
Thanks for the report, please provide the contents of:
* /etc/config/network
* /tmp/sysinfo/board_name
* /tmp/sysinfo/model

**Comment by Garunda** [comment]
Hello,

here are the desired file-contents:
/tmp/sysinfo/board_name:
`unifiac-lite`
/tmp/sysinfo/model:
`Ubiquiti UniFi-AC-LITE`

The file /etc/config/network content is attached.
[network.txt](https://github.com/freifunk-gluon/gluon/files/612232/network.txt)

**Comment by SunboX** [comment]
Same for me! 😢  Please find the mentioned files attached.
[model.txt](https://github.com/freifunk-gluon/gluon/files/615043/model.txt)
[board_name.txt](https://github.com/freifunk-gluon/gluon/files/615042/board_name.txt)
[network.txt](https://github.com/freifunk-gluon/gluon/files/615044/network.txt)

**Comment by ecsv** [comment]
I had some problems in the past with the AR803x PHYs. There are patches in LEDE which work around them. For example  https://git.lede-project.org/?p=source.git;a=blob;f=target/linux/generic/patches-3.18/735-net-phy-at803x-fix-at8033-sgmii-mode.patch;h=4a8f532aa36f729339e01ebadd6ea3cb292d7ac9;hb=HEAD

There are also other RFCs which I've submitted in the past related to SGMII with this PHY (but with QCA955x as SoC) like https://patchwork.ozlabs.org/patch/606468/ (and other changes in this series). But these aren't in LEDE and thus I would expect to LEDE to be still affected.

**Comment by SunboX** [comment]
The fix was apllied to my router by @ecsv (http://vogtland.freifunk.net/map/#!v:m;n:802aa848b87c)

Uplink seems to be stable by now on the Config-Mode works also using DHCP.

**Comment by smoe** [comment]
Heya @NeoRaider,
These changes appear not made it to the 0.6.2.2 release tag while @Garunda's  experimeal build just works smoothly. Since it is not so straight forward to reflash the device without Ethernet access, please kindly consider to forward those Ubiquity AC Lite changes to the next release.
Cheers,
Steffen

**Comment by NeoRaider** [comment]
@smoe, the changes are in v2016.2.x; make sure you always `make update` and `make clean` after pulling.
