### ISSUE TITLE
HW and image id's mismatch. Wrong vendor and hardware version.

### ISSUE THREAD

**Issue by kiwinet** [freifunk-gluon/gluon#926]
I have Tp-Link TL-WR740 v3. 
gluon image detect wrong hw version. It's not the problem as wr740 v3 ~= wr741 v2. But reported hw version is not full and autoupgrade dos not working.

```
# With vendor and hardware version (example: "tp-link-tl-wdr4300-v1")
lua -e 'print(require("platform_info").get_image_name())'
Result: tp-link-tl-wr741nd
```

Second bug is the hw and image id mismatch. I tested with v2016.2 and v2016.2.1 versions. 
```
sysupgrade gluon-ksia-0.6-experimental-16-11-09.1307-tp-link-tl-wr740n
-nd-v3-sysupgrade.bin 
Invalid image, hardware ID mismatch, hw:07400300 00000001 image:07400003 00000001.
Image check 'platform_check_image' failed.
```

It would be good if you're able to fix it.

**Comment by NeoRaider** [comment]
Both issues have the same cause: For some reason, the hardware ID in your flash is incorrect (07400003 is the correct ID, 07400300 is in the flash). Flashing once using `sysupgrade -F` will ignore the mismatch, after that the ID in the flash will be correct again.
