### ISSUE TITLE
shorter image-names so the tp-link interface accepts them

### ISSUE THREAD

**Issue by rubo77** [freifunk-gluon/gluon#931]
the TP-LINK interface doesn't accept filenames longer than 64 characters.

this is easily getting too long, if you create images with the version for example `2016.2~exp1611100047`

the filename already gets too long:

    gluon-ffki-2016.2~exp1611100047-tp-link-tl-wr841n-nd-v10-sysupgrade.bin (72 chars)

So maybe we can automatically create symlinks in the output folder of the Firmware images with shorter names to the tp-link images that have too long names. Or instead of adding the extension `-sysupgrade` just add `-upgrd` or such.

 see:

https://forum.openwrt.org/viewtopic.php?pid=334978#p334978

**Comment by NeoRaider** [comment]
The sysupgrade image is the wrong one anyways, and we don't have a -factory suffix for this reason?

**Comment by rubo77** [comment]
OK, so this issue can be closed then?
