### ISSUE TITLE
wasting space in FW uci_defaults 01_leds  02_network  

### ISSUE THREAD

**Issue by viisauksena** [freifunk-gluon/gluon#932]
defaults for all router modells are in specific firmware - and using quite big amount of space
like this example with **01_leds** and **02_network**  - this 2 account for 37 kbyte

-rw-r--r--    1 root     root         25685 Oct 15 01:33 /rom/etc/uci-defaults/01_leds
-rwxr-xr-x    1 root     root         12302 Oct 15 01:33 /rom/etc/uci-defaults/02_network

there are for sure more examples - my 841 only need his specifics and not all others

**Comment by NeoRaider** [comment]
These files contain a lot of redundancy, 01_leds compresses to 3.5K and 02_network to 2.3K using gzip. The uncompressed sizes don't matter at all.

Also, we'll stop building device-specific rootfs as much as possible as soon as we've switched to LEDE (and build only one rootfs for each set of packages), after that including model-specific files should be avoided as much as possible to keep the build times low.
