### ISSUE TITLE
switch IP of gluon-client-bridge and local-node

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/gluon#939]
- [ ] decide whether this is a good idea and 
- [ ] use the above package for both babel and gluon networks
OR
implement a gluon-client-bridge-babel package that does this just for babel networks.

**Comment by lemoer** [comment]
Could you elaborate why you want to switch the IPs?

**Comment by christf** [comment]
the babel branch should hopefully be able to run without macvlan reducing complexity. Switching the IPs allows to
- use the same package (gluon-client-bridge) for batman and babel networks
- allow for the local-node feature in a babel network while keeping the node properly available in the client net. If not switched, Babel will distribute bogus routes via the local-node IP inside the net.
