### ISSUE TITLE
simple-tc: commit and reboot is necessary to make it work

### ISSUE THREAD

**Issue by Tarnatos** [freifunk-gluon/gluon#940]
gluon: 2016.2.1

To get the bandwidth limitation using simple-tc working, a commit and a reboot is necessary. This should be improved to make it more flexible and to increase the flash lifetime.

https://forum.freifunk.net/t/bandbreitenbegrenzung-simple-tc-ohne-funktion/13855/

**Comment by rotanid** [comment]
please make sure to also try
/etc/init.d/network restart
after the changes, first without comitting.
this could help without a reboot.

**Comment by NeoRaider** [comment]
The values are applied when the interface appears, so restarting fastd should work (`/etc/init.d/network restart` won't have an effect).

**Comment by Tarnatos** [comment]
Unfortunately, restarting fastd has no effect. I've tried it.

**Comment by NeoRaider** [comment]
I can't reproduce this issue. Restarting fastd reliably applies the new settings, even without committing them.
