### ISSUE TITLE
gluon-mesh-batman-adv-core: respondd: doesn't detect VLAN-on-IBSS interfaces as wireless

### ISSUE THREAD

**Issue by NeoRaider** [freifunk-gluon/gluon#941]

**Comment by mokkin** [comment]
Please conside the forum entry 111 and following:
https://forum.freifunk.net/t/hopglass-development-thread/10984/111

**Comment by mokkin** [comment]
Half work done. I built a test version and one direction is showing correctly "Wifi". But the other direction is still showing "cable". Just look at the example as the is no physical wired connection to the mesh, only by wlan:
http://gadow.freifunk.net:8018/hopglass/#!v:g;n:60e327ee3370

**Comment by NeoRaider** [comment]
Did you update both sides of these links?

**Comment by rotanid** [comment]
he, @mokkin, obviously hasn't, if the shown version numbers are correct ;-)

**Comment by mokkin** [comment]
yes, you are right :) stupid of me to forget the other side... Here you can see with two new devices that it's working fine:
http://gadow.freifunk.net:8018/hopglass/#!v:g;n:ec086b2bbee4

**Comment by rubo77** [comment]
Can you add some description, why this was a problem, that had to be fixed?

what was the impact before this was fixed?

**Comment by NeoRaider** [comment]
@rubo77 When VLAN-on-IBSS was used instead of plain IBSS, all wireless mesh links were announced as "other"/wired and displayed as such in maps. Very few sites use VLAN-on-IBSS.
