### ISSUE TITLE
status-page: preparing for babel

### ISSUE THREAD

**Issue by lemoer** [freifunk-gluon/gluon#945]
Current working branch: https://github.com/lemoer/gluon/tree/rebase_statuspage

TODOs
----

**gluon-mesh-babel:**

- [x] adapt a stub makefile out of [the babel pr](https://github.com/freifunk-ffm/gluon/blob/98ee489ce9a7e22d8c4cc27c1af5cba054aa195a/package/gluon-mesh-babel/Makefile)
- [x] create a respondd module
- [x] respondd-module: provide nodeinfo.network.mac
- [x] respondd-module: provide nodeinfo.network.mesh
- [x] respondd-module: provide nodeinfo.network.addresses (adresses on ```br-client```, see question 4)
- [x] create an issue to extend the respondd module for gluon-mesh-babel (see notice 1)

**status-page-api:**

- [x] add "protocol" field to /cgi-bin/dyn/neighbours-batadv
- [x] provide information about babel neighbours in /cgi-bin/dyn/routing-metrics
- [x] rename to /cgi-bin/dyn/routing-metrics
- [x] legacy symlink to /cgi-bin/dyn/neighbours-batadv
- [x] port /cgi-bin/dyn/{stations,neighbours-nodeinfo} to lua (adapt work done in #745)
- [x] use generic function to get mesh ifaces in /cgi-bin/interfaces (see question 2)
- [x] use generic function to get mesh ifaces in /cgi-bin/dyn/stations?iface (see question 2)
- [x] use generic function to get mesh ifaces in /cgi-bin/dyn/neighbours-nodeinfo?iface (see question 2)

**status-page:**

- [x] rename /cgi-bin/dyn/neighbours-batadv to /cgi-bin/dyn/routing-metrics (see [here](https://github.com/lemoer/gluon/commit/d6933def68a3eac6d8fb5248d4be338bba30182f))
- [x] differentiate between batman and babel metrics and show them differently (see [here](https://github.com/lemoer/gluon/commit/e6334488ba34e23efee7f03b27efcb174db410ec))

**general:**

- [x] test in babel
- [x] test in batman-adv
- [ ] docs: add documentation about gluon-status-page (see [here](https://github.com/lemoer/gluon/commit/39b8a5cf52006184b83d3d264374c156798dd85e))

Notices:
--------

1. these resources remain unimplemented in the gluon-mesh-babel respondd provider:
    - nodeinfo.software.babeld
    - statistics.clients
    - statistics.traffic
    - statistics.gateway
    - statistics.gateway_nexthop
    - neighbours.*

Questions:
----------

1. Why do we have providers/neighbours-batadv instead of using respondd neighbours?
2. How do we get the mesh ifaces?
3. Do we need the statistics api part of gluon-mesh-batman-core/respondd?
4. Is the ```br-client``` iface still existing in babel?
5. Can we write the needed respondd provider as general provider for both mesh protocols?

**Comment by christf** [comment]
2. can be answered with: https://github.com/freifunk-ffm/gluon/blob/n_babel-work/package/gluon-mesh-babel/files/lib/gluon/upgrade/980-gluon-mesh-babel-firewall#L9

**Comment by lemoer** [comment]
@rotanid Could you assign me on these issue?

**Comment by lemoer** [comment]
The status-page depends on the respondd facts ```nodeinfo.network.mesh.*.interfaces[] = $mac``` to find out which wifi/mesh neighbour has ```$mac```:

```
{ "nodeinfo": { "network": { "mesh": {

    "bat0": {
        "interfaces": {
            "tunnel": [
                "66:6a:b3:de:dd:58"
            ],
            "wireless": [
                "66:6b:b5:de:dd:58",
                "66:6b:b4:de:dd:58"
            ],
            "other": [
                "66:67:b4:de:dd:58"
            ]
        }
    }

} } }
```

As ```bat0``` is the interface name, we have a problem in babel to hold the convention here. We do not have an equivalent to such an interface in babel. How should we name this section in babel?

An unbeautiful solution would be using ```nodeinfo.network.mesh.babel.interfaces[]```...

**Comment by christf** [comment]
actually since in theory there could be more than one mesh protocol on one node, using  nodeinfo.network.mesh.babel.interfaces[] does not seem so ugly to me. this would also allow for leaving bat0 as it is even though it seems sensible to call it batman instead of bat0.

**Comment by christf** [comment]
4. br-client is for the moment still existing in babel however there seems to be some pull to remove it. at a later stage.
5. this is probably possible but I do not think this is a good idea - what if more than one mesh protocol is used on one node in the future? Shouldn't each report its own metrics?

**Comment by christf** [comment]
#745 is an early work which will likely be superseeded by the results of the work going into this issue.

**Comment by lemoer** [comment]
Back to the question how we get the mesh ifaces:
- How do we solve this in shell?
- Isn't there a lua function which is exported by gluon_util?
    - If not, do we want to do this?

**Comment by lemoer** [comment]
What is the current status of the ```br-client``` interface? (Q4)

**Comment by christf** [comment]
br-client will remain in gluon for quite some time. The gluon-client-bridge-babel has been obsoleted by the change in gluon-client-bridge. This was taken from an irc discussion from last week.

I feel find_meshes() is the way to go in lua-context. However I do not know where this function should be placed. If you provide the place @NeoRaider, I will put it there as part of PR #934.

**Comment by christf** [comment]
as discussed on irc with @neoraider he liked the ubus version that must be converted to lua and should be placed in gluon.util. I took the liberty of implementing this in PR #990

**Comment by christf** [comment]
I have just pulled the rebase_statuspage branch into the babel-PR and will continue the integration there.

**Comment by christf** [comment]
closing because nothing is left to do for this PR.
