### ISSUE TITLE
Add support for TL-WR1043nd-v4

### ISSUE THREAD

**Issue by thepaffy** [freifunk-gluon/gluon#961]
One of our community member told me that he bought a TL-WR1043nd-v4.
But the v4 is not supported by gluon and, as I see, not by OpenWRT.

So you can add support for the TL-WR1043nd-v4?

**Comment by rotanid** [comment]
support can't be added without someone who owns a device and is willing to work on the support, which includes attaching a serial console to the device.
i ordered a 1043 on amazon, hope it will be a v4, but i can't promise how fast the support will be added.

**Comment by Adorfer** [comment]
as always where there is new hardware which could possibly be support: Get one unit as donation to the gluon/LEDE-team. 
Other options are available, but they will take much longer and will cause more efforts for you testing build, feeding back logs and reports etc.

**Comment by rotanid** [comment]
status update:
we received a 1043nd v4 yesterday and worked the whole night on supporting it, me and @Brother-Lal .
though we are pretty new to adding support for new devices, got some help from @H4ndl3 and are now waiting for @NeoRaider to help with the final touches.
this would result in LEDE support for the device, a backport to gluon would ideally follow.

**Comment by FabianCernota** [comment]
Any updates? We got many v4's in our community

**Comment by Brother-Lal** [comment]
Support for LEDE is in staging.
After it is main, a backport has to be done for gluon.

**Comment by rotanid** [comment]
update: thanks to @Brother-Lal and @neoraider the support for the device is now in LEDE.

**Comment by thepaffy** [comment]
Thank you!
