### ISSUE TITLE
VPN status on status page

### ISSUE THREAD

**Issue by sargon** [freifunk-gluon/gluon#98]
When a node has VPN activated the local-node page should show status informations 
about the connection state. Including: to which VPN Server a connection is established
and which VPN Server is rejecting a connection. Maybe also with a detailed reason why a connection is not established, for example unknown key, can not resolve hostname or port not reachable.

**Comment by tcatm** [comment]
Could someone summarize what needs to be implemented to close this issue?

**Comment by sargon** [comment]
In the case the node has  Mesh-VPN activated, the status page should include informations about:

- [ ] traffic statistics
- [ ] list of connected vpn peers

We can limit the list to the connected once and ignore the not connected, maybe this should be site configurable. The entries of the peer list can at most include the name and the connection state, but no further details, I think nobody has to see details like IP addresses by default.

**Comment by do9xe** [comment]
* show which Gateway the Node is conneced to
* show if vpn is activ

somesthing like this:
![Example Node Page]
(http://labor19.net/freifunk/statuspage6.png)

**Comment by tcatm** [comment]
I think this counts as done now that the status-page branch has appropiate code and the old status page displays VPN status information, too.
