### ISSUE TITLE
make altitude independent of latitude and longitude

### ISSUE THREAD

**Issue by FFS-Roland** [freifunk-gluon/gluon#983]
There are situations, where the exact location (latitude / longitude) should not be published. Because at Freifunk-Stuttgart we use geolocation for assigning nodes to segments (subnets), we want to use altitude  field to store ZIP-Code while latitude / longitude may remain empty. Right now this is not possible because hard coding in "/package/gluon-config-mode-geo-location/luasrc/lib/gluon/config-mode/wizard/0400-geo-location.lua".

To be more flexible in using field altitude, i propose the change to "wizard/0400-geo-location.lua", which is attached.

[patch-0400-geo-location.txt](https://github.com/freifunk-gluon/gluon/files/659664/patch-0400-geo-location.txt)

**Comment by mweinelt** [comment]
Please create a new package for your feature, take a look at the `gluon-config-mode-contact-info` as an example: https://github.com/freifunk-gluon/gluon/tree/master/package/gluon-config-mode-contact-info.

This can then be given a dedicted language string and other communities, who'd like to use both, actually can.

**Comment by FFS-Roland** [comment]
OK, we will try. Thanx.

**Comment by Philhil** [comment]
If there is somebody in future who also need it. We made a config-mode-module: https://github.com/freifunk-stuttgart/Gluon-Packages/tree/master/gluon-config-mode-zip
